namespace DevExpress.DevAV.Modules {
    partial class Tasks {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing) {
            if(disposing && (components != null)) {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent() {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Tasks));
            DevExpress.XtraEditors.TileItemElement tileItemElement1 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement2 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement3 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement4 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement5 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement6 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement7 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement8 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement9 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement10 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement11 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement12 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement13 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement14 = new DevExpress.XtraEditors.TileItemElement();
            this.tasksGridControl = new DevExpress.XtraGrid.GridControl();
            this.tasksGridView = new DevExpress.XtraGrid.Views.Grid.GridView();
            this.AssignedTo = new DevExpress.XtraGrid.Columns.GridColumn();
            this.OwnedBy = new DevExpress.XtraGrid.Columns.GridColumn();
            this.Subject = new DevExpress.XtraGrid.Columns.GridColumn();
            this.Priority = new DevExpress.XtraGrid.Columns.GridColumn();
            this.repositoryItemComboBox1 = new DevExpress.XtraEditors.Repository.RepositoryItemImageComboBox();
            this.priorityImageList = new DevExpress.Utils.ImageCollection(this.components);
            this.DueDate = new DevExpress.XtraGrid.Columns.GridColumn();
            this.Complete = new DevExpress.XtraGrid.Columns.GridColumn();
            this.repositoryItemProgressBar1 = new DevExpress.XtraEditors.Repository.RepositoryItemProgressBar();
            this.dataLayoutControl1 = new DevExpress.XtraDataLayout.DataLayoutControl();
            this.tileControl1 = new DevExpress.XtraEditors.TileControl();
            this.tileGroup2 = new DevExpress.XtraEditors.TileGroup();
            this.tileItemAll = new DevExpress.XtraEditors.TileItem();
            this.tileItemInProgress = new DevExpress.XtraEditors.TileItem();
            this.tileItemNotStartedTask = new DevExpress.XtraEditors.TileItem();
            this.tileItemDeferred = new DevExpress.XtraEditors.TileItem();
            this.tileItemCompleted = new DevExpress.XtraEditors.TileItem();
            this.tileItemHighPriority = new DevExpress.XtraEditors.TileItem();
            this.tileItemUrgent = new DevExpress.XtraEditors.TileItem();
            this.taskBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.layoutControlGroup1 = new DevExpress.XtraLayout.LayoutControlGroup();
            this.layoutControlItem1 = new DevExpress.XtraLayout.LayoutControlItem();
            this.tileControlLCI = new DevExpress.XtraLayout.LayoutControlItem();
            this.buttonHide = new DevExpress.XtraLayout.SimpleLabelItem();
            this.tasksSLI = new DevExpress.XtraLayout.SimpleLabelItem();
            this.simpleLabelItem1 = new DevExpress.XtraLayout.SimpleLabelItem();
            this.simpleLabelItem2 = new DevExpress.XtraLayout.SimpleLabelItem();
            this.simpleLabelItem3 = new DevExpress.XtraLayout.SimpleLabelItem();
            this.simpleLabelItem4 = new DevExpress.XtraLayout.SimpleLabelItem();
            this.simpleLabelItem5 = new DevExpress.XtraLayout.SimpleLabelItem();
            this.simpleLabelItem7 = new DevExpress.XtraLayout.SimpleLabelItem();
            ((System.ComponentModel.ISupportInitialize)(this.tasksGridControl)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.tasksGridView)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.repositoryItemComboBox1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.priorityImageList)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.repositoryItemProgressBar1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dataLayoutControl1)).BeginInit();
            this.dataLayoutControl1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.taskBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.tileControlLCI)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.buttonHide)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.tasksSLI)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.simpleLabelItem1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.simpleLabelItem2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.simpleLabelItem3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.simpleLabelItem4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.simpleLabelItem5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.simpleLabelItem7)).BeginInit();
            this.SuspendLayout();
            this.tasksGridControl.Location = new System.Drawing.Point(310, 49);
            this.tasksGridControl.MainView = this.tasksGridView;
            this.tasksGridControl.Name = "tasksGridControl";
            this.tasksGridControl.RepositoryItems.AddRange(new DevExpress.XtraEditors.Repository.RepositoryItem[] {
            this.repositoryItemProgressBar1,
            this.repositoryItemComboBox1});
            this.tasksGridControl.Size = new System.Drawing.Size(1072, 538);
            this.tasksGridControl.TabIndex = 1;
            this.tasksGridControl.ViewCollection.AddRange(new DevExpress.XtraGrid.Views.Base.BaseView[] {
            this.tasksGridView});
            this.tasksGridView.Appearance.FooterPanel.Options.UseTextOptions = true;
            this.tasksGridView.Appearance.FooterPanel.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            this.tasksGridView.Appearance.GroupFooter.Options.UseTextOptions = true;
            this.tasksGridView.Appearance.GroupFooter.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            this.tasksGridView.Columns.AddRange(new DevExpress.XtraGrid.Columns.GridColumn[] {
            this.AssignedTo,
            this.OwnedBy,
            this.Subject,
            this.Priority,
            this.DueDate,
            this.Complete});
            this.tasksGridView.FocusRectStyle = DevExpress.XtraGrid.Views.Grid.DrawFocusRectStyle.None;
            this.tasksGridView.FooterPanelHeight = 60;
            this.tasksGridView.GridControl = this.tasksGridControl;
            this.tasksGridView.Name = "tasksGridView";
            this.tasksGridView.OptionsBehavior.Editable = false;
            this.tasksGridView.OptionsCustomization.AllowQuickHideColumns = false;
            this.tasksGridView.OptionsFind.AllowFindPanel = false;
            this.tasksGridView.OptionsSelection.EnableAppearanceFocusedCell = false;
            this.tasksGridView.OptionsView.ShowFilterPanelMode = DevExpress.XtraGrid.Views.Base.ShowFilterPanelMode.Never;
            this.tasksGridView.OptionsView.ShowFooter = true;
            this.tasksGridView.OptionsView.ShowGroupPanel = false;
            this.tasksGridView.OptionsView.ShowIndicator = false;
            this.tasksGridView.RowHeight = 10;
            this.tasksGridView.SortInfo.AddRange(new DevExpress.XtraGrid.Columns.GridColumnSortInfo[] {
            new DevExpress.XtraGrid.Columns.GridColumnSortInfo(this.DueDate, DevExpress.Data.ColumnSortOrder.Descending)});
            this.tasksGridView.RowClick += new DevExpress.XtraGrid.Views.Grid.RowClickEventHandler(this.tasksGridView_RowClick);
            this.tasksGridView.FocusedRowObjectChanged += new DevExpress.XtraGrid.Views.Base.FocusedRowObjectChangedEventHandler(this.tasksGridView_FocusedRowObjectChanged);
            this.AssignedTo.Caption = "Assigned To";
            this.AssignedTo.FieldName = "AssignedEmployee.FullName";
            this.AssignedTo.Name = "AssignedTo";
            this.AssignedTo.Visible = true;
            this.AssignedTo.VisibleIndex = 0;
            this.AssignedTo.Width = 180;
            this.OwnedBy.Caption = "Owned By";
            this.OwnedBy.FieldName = "Owner.FullName";
            this.OwnedBy.Name = "OwnedBy";
            this.OwnedBy.Visible = true;
            this.OwnedBy.VisibleIndex = 1;
            this.OwnedBy.Width = 176;
            this.Subject.Caption = "Subject";
            this.Subject.FieldName = "Subject";
            this.Subject.Name = "Subject";
            this.Subject.Visible = true;
            this.Subject.VisibleIndex = 2;
            this.Subject.Width = 355;
            this.Priority.AppearanceCell.Options.UseTextOptions = true;
            this.Priority.Caption = "Priority";
            this.Priority.ColumnEdit = this.repositoryItemComboBox1;
            this.Priority.FieldName = "Priority";
            this.Priority.ImageAlignment = System.Drawing.StringAlignment.Center;
            this.Priority.Name = "Priority";
            this.Priority.OptionsColumn.FixedWidth = true;
            this.Priority.OptionsFilter.AllowAutoFilter = false;
            this.Priority.OptionsFilter.AllowFilter = false;
            this.Priority.SortMode = DevExpress.XtraGrid.ColumnSortMode.Value;
            this.Priority.Visible = true;
            this.Priority.VisibleIndex = 3;
            this.Priority.Width = 92;
            this.repositoryItemComboBox1.Appearance.Options.UseTextOptions = true;
            this.repositoryItemComboBox1.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;
            this.repositoryItemComboBox1.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            this.repositoryItemComboBox1.GlyphAlignment = DevExpress.Utils.HorzAlignment.Center;
            this.repositoryItemComboBox1.Items.AddRange(new DevExpress.XtraEditors.Controls.ImageComboBoxItem[] {
            new DevExpress.XtraEditors.Controls.ImageComboBoxItem("", DevExpress.DevAV.EmployeeTaskPriority.Low, 0),
            new DevExpress.XtraEditors.Controls.ImageComboBoxItem("", DevExpress.DevAV.EmployeeTaskPriority.Normal, 1),
            new DevExpress.XtraEditors.Controls.ImageComboBoxItem("", DevExpress.DevAV.EmployeeTaskPriority.High, 2),
            new DevExpress.XtraEditors.Controls.ImageComboBoxItem("", DevExpress.DevAV.EmployeeTaskPriority.Urgent, 3)});
            this.repositoryItemComboBox1.Name = "repositoryItemComboBox1";
            this.repositoryItemComboBox1.PopupSizeable = true;
            this.repositoryItemComboBox1.SmallImages = this.priorityImageList;
            this.priorityImageList.ImageSize = new System.Drawing.Size(24, 24);
            this.priorityImageList.ImageStream = ((DevExpress.Utils.ImageCollectionStreamer)(resources.GetObject("priorityImageList.ImageStream")));
            this.priorityImageList.InsertImage(global::DevExpress.DevAV.Properties.Resources.LowPriority, "LowPriority", typeof(global::DevExpress.DevAV.Properties.Resources), 0);
            this.priorityImageList.Images.SetKeyName(0, "LowPriority");
            this.priorityImageList.InsertImage(global::DevExpress.DevAV.Properties.Resources.NormalPriority, "NormalPriority", typeof(global::DevExpress.DevAV.Properties.Resources), 1);
            this.priorityImageList.Images.SetKeyName(1, "NormalPriority");
            this.priorityImageList.InsertImage(global::DevExpress.DevAV.Properties.Resources.MediumPriority, "MediumPriority", typeof(global::DevExpress.DevAV.Properties.Resources), 2);
            this.priorityImageList.Images.SetKeyName(2, "MediumPriority");
            this.priorityImageList.InsertImage(global::DevExpress.DevAV.Properties.Resources.HighPriority, "HighPriority", typeof(global::DevExpress.DevAV.Properties.Resources), 3);
            this.priorityImageList.Images.SetKeyName(3, "HighPriority");
            this.DueDate.Caption = "Due Date";
            this.DueDate.FieldName = "DueDate";
            this.DueDate.Name = "DueDate";
            this.DueDate.OptionsColumn.FixedWidth = true;
            this.DueDate.Visible = true;
            this.DueDate.VisibleIndex = 4;
            this.DueDate.Width = 115;
            this.Complete.Caption = "% Complete";
            this.Complete.ColumnEdit = this.repositoryItemProgressBar1;
            this.Complete.FieldName = "Completion";
            this.Complete.MaxWidth = 296;
            this.Complete.Name = "Complete";
            this.Complete.Summary.AddRange(new DevExpress.XtraGrid.GridSummaryItem[] {
            new DevExpress.XtraGrid.GridColumnSummaryItem(DevExpress.Data.SummaryItemType.Count, "Completion", "<color=gray>TOTAL # OF TASKS</color><br><b>{0}</b>")});
            this.Complete.Visible = true;
            this.Complete.VisibleIndex = 5;
            this.Complete.Width = 184;
            this.repositoryItemProgressBar1.Name = "repositoryItemProgressBar1";
            this.repositoryItemProgressBar1.ProgressPadding = new System.Windows.Forms.Padding(0, 1, 0, 0);
            this.repositoryItemProgressBar1.ProgressViewStyle = DevExpress.XtraEditors.Controls.ProgressViewStyle.Solid;
            this.repositoryItemProgressBar1.ShowTitle = true;
            this.dataLayoutControl1.AllowCustomization = false;
            this.dataLayoutControl1.BackColor = System.Drawing.Color.White;
            this.dataLayoutControl1.Controls.Add(this.tileControl1);
            this.dataLayoutControl1.Controls.Add(this.tasksGridControl);
            this.dataLayoutControl1.DataSource = this.taskBindingSource;
            this.dataLayoutControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dataLayoutControl1.Location = new System.Drawing.Point(0, 0);
            this.dataLayoutControl1.Name = "dataLayoutControl1";
            this.dataLayoutControl1.OptionsCustomizationForm.DesignTimeCustomizationFormPositionAndSize = new System.Drawing.Rectangle(810, 371, 864, 732);
            this.dataLayoutControl1.Root = this.layoutControlGroup1;
            this.dataLayoutControl1.Size = new System.Drawing.Size(1424, 589);
            this.dataLayoutControl1.TabIndex = 26;
            this.dataLayoutControl1.Text = "dataLayoutControl1";
            this.tileControl1.AllowDrag = false;
            this.tileControl1.AllowGlyphSkinning = true;
            this.tileControl1.AllowSelectedItem = true;
            this.tileControl1.AppearanceItem.Hovered.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(78)))), ((int)(((byte)(114)))), ((int)(((byte)(191)))));
            this.tileControl1.AppearanceItem.Hovered.Options.UseBackColor = true;
            this.tileControl1.AppearanceItem.Normal.BackColor = System.Drawing.Color.White;
            this.tileControl1.AppearanceItem.Normal.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(195)))), ((int)(((byte)(195)))), ((int)(((byte)(195)))));
            this.tileControl1.AppearanceItem.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(87)))), ((int)(((byte)(87)))));
            this.tileControl1.AppearanceItem.Normal.Options.UseBackColor = true;
            this.tileControl1.AppearanceItem.Normal.Options.UseBorderColor = true;
            this.tileControl1.AppearanceItem.Normal.Options.UseForeColor = true;
            this.tileControl1.AppearanceItem.Pressed.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(69)))), ((int)(((byte)(148)))));
            this.tileControl1.AppearanceItem.Pressed.Options.UseBackColor = true;
            this.tileControl1.AppearanceItem.Selected.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(81)))), ((int)(((byte)(165)))));
            this.tileControl1.AppearanceItem.Selected.BorderColor = System.Drawing.Color.Transparent;
            this.tileControl1.AppearanceItem.Selected.ForeColor = System.Drawing.Color.White;
            this.tileControl1.AppearanceItem.Selected.Options.UseBackColor = true;
            this.tileControl1.AppearanceItem.Selected.Options.UseBorderColor = true;
            this.tileControl1.AppearanceItem.Selected.Options.UseForeColor = true;
            this.tileControl1.DragSize = new System.Drawing.Size(0, 0);
            this.tileControl1.Groups.Add(this.tileGroup2);
            this.tileControl1.IndentBetweenItems = 5;
            this.tileControl1.ItemPadding = new System.Windows.Forms.Padding(7, 7, 7, 4);
            this.tileControl1.ItemSize = 80;
            this.tileControl1.Location = new System.Drawing.Point(42, 47);
            this.tileControl1.Margin = new System.Windows.Forms.Padding(0);
            this.tileControl1.MaxId = 7;
            this.tileControl1.Name = "tileControl1";
            this.tileControl1.Orientation = System.Windows.Forms.Orientation.Vertical;
            this.tileControl1.Padding = new System.Windows.Forms.Padding(0);
            this.tileControl1.SelectedItem = this.tileItemAll;
            this.tileControl1.Size = new System.Drawing.Size(236, 540);
            this.tileControl1.TabIndex = 26;
            this.tileControl1.Text = "tileControl1";
            this.tileGroup2.Items.Add(this.tileItemAll);
            this.tileGroup2.Items.Add(this.tileItemInProgress);
            this.tileGroup2.Items.Add(this.tileItemNotStartedTask);
            this.tileGroup2.Items.Add(this.tileItemDeferred);
            this.tileGroup2.Items.Add(this.tileItemCompleted);
            this.tileGroup2.Items.Add(this.tileItemHighPriority);
            this.tileGroup2.Items.Add(this.tileItemUrgent);
            this.tileGroup2.Name = "tileGroup2";
            this.tileGroup2.Text = null;
            tileItemElement1.Appearance.Normal.FontSizeDelta = 128;
            tileItemElement1.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(171)))), ((int)(((byte)(171)))), ((int)(((byte)(171)))));
            tileItemElement1.Appearance.Normal.Options.UseFont = true;
            tileItemElement1.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement1.Appearance.Selected.FontSizeDelta = 128;
            tileItemElement1.Appearance.Selected.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(168)))), ((int)(((byte)(209)))));
            tileItemElement1.Appearance.Selected.Options.UseFont = true;
            tileItemElement1.Appearance.Selected.Options.UseForeColor = true;
            tileItemElement1.ImageBorderColor = System.Drawing.Color.Empty;
            tileItemElement1.Text = "183";
            tileItemElement1.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopRight;
            tileItemElement1.TextLocation = new System.Drawing.Point(-2, -12);
            tileItemElement2.Image = ((System.Drawing.Image)(resources.GetObject("tileItemElement2.Image")));
            tileItemElement2.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopLeft;
            tileItemElement2.ImageBorderColor = System.Drawing.Color.Empty;
            tileItemElement2.Text = "All Tasks";
            tileItemElement2.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomLeft;
            this.tileItemAll.Elements.Add(tileItemElement1);
            this.tileItemAll.Elements.Add(tileItemElement2);
            this.tileItemAll.Id = 0;
            this.tileItemAll.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItemAll.Name = "tileItemAll";
            this.tileItemAll.Tag = "Priority != \'null\'";
            this.tileItemAll.ItemClick += new DevExpress.XtraEditors.TileItemClickEventHandler(this.tileItem_ItemClick);
            tileItemElement3.Appearance.Normal.FontSizeDelta = 128;
            tileItemElement3.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(171)))), ((int)(((byte)(171)))), ((int)(((byte)(171)))));
            tileItemElement3.Appearance.Normal.Options.UseFont = true;
            tileItemElement3.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement3.Appearance.Selected.FontSizeDelta = 128;
            tileItemElement3.Appearance.Selected.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(168)))), ((int)(((byte)(209)))));
            tileItemElement3.Appearance.Selected.Options.UseFont = true;
            tileItemElement3.Appearance.Selected.Options.UseForeColor = true;
            tileItemElement3.ImageBorderColor = System.Drawing.Color.Empty;
            tileItemElement3.Text = "5";
            tileItemElement3.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopRight;
            tileItemElement3.TextLocation = new System.Drawing.Point(-2, -12);
            tileItemElement4.Image = ((System.Drawing.Image)(resources.GetObject("tileItemElement4.Image")));
            tileItemElement4.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopLeft;
            tileItemElement4.ImageBorderColor = System.Drawing.Color.Empty;
            tileItemElement4.Text = "In Progress";
            tileItemElement4.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomLeft;
            this.tileItemInProgress.Elements.Add(tileItemElement3);
            this.tileItemInProgress.Elements.Add(tileItemElement4);
            this.tileItemInProgress.Id = 1;
            this.tileItemInProgress.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItemInProgress.Name = "tileItemInProgress";
            this.tileItemInProgress.Tag = "Status == \'InProgress\'";
            this.tileItemInProgress.ItemClick += new DevExpress.XtraEditors.TileItemClickEventHandler(this.tileItem_ItemClick);
            tileItemElement5.Appearance.Normal.FontSizeDelta = 128;
            tileItemElement5.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(171)))), ((int)(((byte)(171)))), ((int)(((byte)(171)))));
            tileItemElement5.Appearance.Normal.Options.UseFont = true;
            tileItemElement5.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement5.Appearance.Selected.FontSizeDelta = 128;
            tileItemElement5.Appearance.Selected.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(168)))), ((int)(((byte)(209)))));
            tileItemElement5.Appearance.Selected.Options.UseFont = true;
            tileItemElement5.Appearance.Selected.Options.UseForeColor = true;
            tileItemElement5.ImageBorderColor = System.Drawing.Color.Empty;
            tileItemElement5.Text = "5";
            tileItemElement5.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopRight;
            tileItemElement5.TextLocation = new System.Drawing.Point(-2, -12);
            tileItemElement6.Image = ((System.Drawing.Image)(resources.GetObject("tileItemElement6.Image")));
            tileItemElement6.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopLeft;
            tileItemElement6.ImageBorderColor = System.Drawing.Color.Empty;
            tileItemElement6.Text = "Not Started";
            tileItemElement6.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomLeft;
            this.tileItemNotStartedTask.Elements.Add(tileItemElement5);
            this.tileItemNotStartedTask.Elements.Add(tileItemElement6);
            this.tileItemNotStartedTask.Id = 2;
            this.tileItemNotStartedTask.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItemNotStartedTask.Name = "tileItemNotStartedTask";
            this.tileItemNotStartedTask.Tag = "Status == \'NotStarted\'";
            this.tileItemNotStartedTask.ItemClick += new DevExpress.XtraEditors.TileItemClickEventHandler(this.tileItem_ItemClick);
            tileItemElement7.Appearance.Normal.FontSizeDelta = 128;
            tileItemElement7.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(171)))), ((int)(((byte)(171)))), ((int)(((byte)(171)))));
            tileItemElement7.Appearance.Normal.Options.UseFont = true;
            tileItemElement7.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement7.Appearance.Selected.FontSizeDelta = 128;
            tileItemElement7.Appearance.Selected.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(168)))), ((int)(((byte)(209)))));
            tileItemElement7.Appearance.Selected.Options.UseFont = true;
            tileItemElement7.Appearance.Selected.Options.UseForeColor = true;
            tileItemElement7.ImageBorderColor = System.Drawing.Color.Empty;
            tileItemElement7.Text = "5";
            tileItemElement7.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopRight;
            tileItemElement7.TextLocation = new System.Drawing.Point(-2, -12);
            tileItemElement8.Image = ((System.Drawing.Image)(resources.GetObject("tileItemElement8.Image")));
            tileItemElement8.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopLeft;
            tileItemElement8.ImageBorderColor = System.Drawing.Color.Empty;
            tileItemElement8.Text = "Deferred";
            tileItemElement8.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomLeft;
            this.tileItemDeferred.Elements.Add(tileItemElement7);
            this.tileItemDeferred.Elements.Add(tileItemElement8);
            this.tileItemDeferred.Id = 3;
            this.tileItemDeferred.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItemDeferred.Name = "tileItemDeferred";
            this.tileItemDeferred.Tag = "Status = \'Deferred\'";
            this.tileItemDeferred.ItemClick += new DevExpress.XtraEditors.TileItemClickEventHandler(this.tileItem_ItemClick);
            tileItemElement9.Appearance.Normal.FontSizeDelta = 128;
            tileItemElement9.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(171)))), ((int)(((byte)(171)))), ((int)(((byte)(171)))));
            tileItemElement9.Appearance.Normal.Options.UseFont = true;
            tileItemElement9.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement9.Appearance.Selected.FontSizeDelta = 128;
            tileItemElement9.Appearance.Selected.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(168)))), ((int)(((byte)(209)))));
            tileItemElement9.Appearance.Selected.Options.UseFont = true;
            tileItemElement9.Appearance.Selected.Options.UseForeColor = true;
            tileItemElement9.ImageBorderColor = System.Drawing.Color.Empty;
            tileItemElement9.Text = "5";
            tileItemElement9.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopRight;
            tileItemElement9.TextLocation = new System.Drawing.Point(-2, -12);
            tileItemElement10.Image = ((System.Drawing.Image)(resources.GetObject("tileItemElement10.Image")));
            tileItemElement10.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopLeft;
            tileItemElement10.ImageBorderColor = System.Drawing.Color.Empty;
            tileItemElement10.Text = "Completed";
            tileItemElement10.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomLeft;
            this.tileItemCompleted.Elements.Add(tileItemElement9);
            this.tileItemCompleted.Elements.Add(tileItemElement10);
            this.tileItemCompleted.Id = 4;
            this.tileItemCompleted.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItemCompleted.Name = "tileItemCompleted";
            this.tileItemCompleted.Tag = "Status == \'Completed\'";
            this.tileItemCompleted.ItemClick += new DevExpress.XtraEditors.TileItemClickEventHandler(this.tileItem_ItemClick);
            tileItemElement11.Appearance.Normal.FontSizeDelta = 128;
            tileItemElement11.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(171)))), ((int)(((byte)(171)))), ((int)(((byte)(171)))));
            tileItemElement11.Appearance.Normal.Options.UseFont = true;
            tileItemElement11.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement11.Appearance.Selected.FontSizeDelta = 128;
            tileItemElement11.Appearance.Selected.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(168)))), ((int)(((byte)(209)))));
            tileItemElement11.Appearance.Selected.Options.UseFont = true;
            tileItemElement11.Appearance.Selected.Options.UseForeColor = true;
            tileItemElement11.ImageBorderColor = System.Drawing.Color.Empty;
            tileItemElement11.Text = "5";
            tileItemElement11.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopRight;
            tileItemElement11.TextLocation = new System.Drawing.Point(-2, -12);
            tileItemElement12.Image = ((System.Drawing.Image)(resources.GetObject("tileItemElement12.Image")));
            tileItemElement12.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopLeft;
            tileItemElement12.ImageBorderColor = System.Drawing.Color.Empty;
            tileItemElement12.Text = "High Priority";
            tileItemElement12.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomLeft;
            this.tileItemHighPriority.Elements.Add(tileItemElement11);
            this.tileItemHighPriority.Elements.Add(tileItemElement12);
            this.tileItemHighPriority.Id = 6;
            this.tileItemHighPriority.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItemHighPriority.Name = "tileItemHighPriority";
            this.tileItemHighPriority.Tag = "Priority == \'High\'";
            this.tileItemHighPriority.ItemClick += new DevExpress.XtraEditors.TileItemClickEventHandler(this.tileItem_ItemClick);
            tileItemElement13.Appearance.Normal.FontSizeDelta = 128;
            tileItemElement13.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(171)))), ((int)(((byte)(171)))), ((int)(((byte)(171)))));
            tileItemElement13.Appearance.Normal.Options.UseFont = true;
            tileItemElement13.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement13.Appearance.Selected.FontSizeDelta = 128;
            tileItemElement13.Appearance.Selected.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(168)))), ((int)(((byte)(209)))));
            tileItemElement13.Appearance.Selected.Options.UseFont = true;
            tileItemElement13.Appearance.Selected.Options.UseForeColor = true;
            tileItemElement13.ImageBorderColor = System.Drawing.Color.Empty;
            tileItemElement13.Text = "5";
            tileItemElement13.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopRight;
            tileItemElement13.TextLocation = new System.Drawing.Point(-2, -12);
            tileItemElement14.Image = ((System.Drawing.Image)(resources.GetObject("tileItemElement14.Image")));
            tileItemElement14.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopLeft;
            tileItemElement14.ImageBorderColor = System.Drawing.Color.Empty;
            tileItemElement14.Text = "Urgent";
            tileItemElement14.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomLeft;
            this.tileItemUrgent.Elements.Add(tileItemElement13);
            this.tileItemUrgent.Elements.Add(tileItemElement14);
            this.tileItemUrgent.Id = 5;
            this.tileItemUrgent.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItemUrgent.Name = "tileItemUrgent";
            this.tileItemUrgent.Tag = "Priority == \'Urgent\'";
            this.tileItemUrgent.ItemClick += new DevExpress.XtraEditors.TileItemClickEventHandler(this.tileItem_ItemClick);
            this.taskBindingSource.DataSource = typeof(DevExpress.DevAV.EmployeeTask);
            this.layoutControlGroup1.CustomizationFormText = "Root";
            this.layoutControlGroup1.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True;
            this.layoutControlGroup1.GroupBordersVisible = false;
            this.layoutControlGroup1.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.layoutControlItem1,
            this.tileControlLCI,
            this.buttonHide,
            this.tasksSLI});
            this.layoutControlGroup1.Location = new System.Drawing.Point(0, 0);
            this.layoutControlGroup1.Name = "Root";
            this.layoutControlGroup1.Padding = new DevExpress.XtraLayout.Utils.Padding(40, 40, 0, 0);
            this.layoutControlGroup1.Size = new System.Drawing.Size(1424, 589);
            this.layoutControlGroup1.TextVisible = false;
            this.layoutControlItem1.Control = this.tasksGridControl;
            this.layoutControlItem1.CustomizationFormText = "layoutControlItem1";
            this.layoutControlItem1.Location = new System.Drawing.Point(268, 45);
            this.layoutControlItem1.Name = "layoutControlItem1";
            this.layoutControlItem1.Padding = new DevExpress.XtraLayout.Utils.Padding(2, 2, 4, 2);
            this.layoutControlItem1.Size = new System.Drawing.Size(1076, 544);
            this.layoutControlItem1.TextSize = new System.Drawing.Size(0, 0);
            this.layoutControlItem1.TextVisible = false;
            this.tileControlLCI.Control = this.tileControl1;
            this.tileControlLCI.CustomizationFormText = "tileControlLCI";
            this.tileControlLCI.Location = new System.Drawing.Point(0, 45);
            this.tileControlLCI.MaxSize = new System.Drawing.Size(240, 0);
            this.tileControlLCI.MinSize = new System.Drawing.Size(240, 24);
            this.tileControlLCI.Name = "tileControlLCI";
            this.tileControlLCI.OptionsPrint.AllowPrint = false;
            this.tileControlLCI.Size = new System.Drawing.Size(240, 544);
            this.tileControlLCI.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.tileControlLCI.TextSize = new System.Drawing.Size(0, 0);
            this.tileControlLCI.TextVisible = false;
            this.buttonHide.AllowHotTrack = false;
            this.buttonHide.CustomizationFormText = " ";
            this.buttonHide.Image = ((System.Drawing.Image)(resources.GetObject("buttonHide.Image")));
            this.buttonHide.Location = new System.Drawing.Point(240, 45);
            this.buttonHide.MaxSize = new System.Drawing.Size(28, 0);
            this.buttonHide.MinSize = new System.Drawing.Size(28, 1);
            this.buttonHide.Name = "buttonHide";
            this.buttonHide.Size = new System.Drawing.Size(28, 544);
            this.buttonHide.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.buttonHide.Text = " ";
            this.buttonHide.TextSize = new System.Drawing.Size(53, 25);
            this.buttonHide.Click += new System.EventHandler(this.collapseButton_Click);
            this.tasksSLI.AllowHotTrack = false;
            this.tasksSLI.AllowHtmlStringInCaption = true;
            this.tasksSLI.AppearanceItemCaption.FontSizeDelta = 3;
            this.tasksSLI.AppearanceItemCaption.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(82)))), ((int)(((byte)(163)))));
            this.tasksSLI.AppearanceItemCaption.Options.UseFont = true;
            this.tasksSLI.AppearanceItemCaption.Options.UseForeColor = true;
            this.tasksSLI.CustomizationFormText = "TASKS";
            this.tasksSLI.Location = new System.Drawing.Point(0, 0);
            this.tasksSLI.Name = "tasksSLI";
            this.tasksSLI.Padding = new DevExpress.XtraLayout.Utils.Padding(4, 2, 10, 10);
            this.tasksSLI.Size = new System.Drawing.Size(1344, 45);
            this.tasksSLI.Text = "TASKS";
            this.tasksSLI.TextSize = new System.Drawing.Size(53, 25);
            this.simpleLabelItem1.AllowHotTrack = false;
            this.simpleLabelItem1.AppearanceItemCaption.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.BackwardDiagonal;
            this.simpleLabelItem1.CustomizationFormText = " ";
            this.simpleLabelItem1.Image = ((System.Drawing.Image)(resources.GetObject("simpleLabelItem1.Image")));
            this.simpleLabelItem1.ImageAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.simpleLabelItem1.Location = new System.Drawing.Point(200, 34);
            this.simpleLabelItem1.MaxSize = new System.Drawing.Size(28, 0);
            this.simpleLabelItem1.MinSize = new System.Drawing.Size(28, 17);
            this.simpleLabelItem1.Name = "buttonHide";
            this.simpleLabelItem1.Size = new System.Drawing.Size(28, 512);
            this.simpleLabelItem1.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.simpleLabelItem1.Text = " ";
            this.simpleLabelItem1.TextSize = new System.Drawing.Size(127, 13);
            this.simpleLabelItem2.AllowHotTrack = false;
            this.simpleLabelItem2.AppearanceItemCaption.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.BackwardDiagonal;
            this.simpleLabelItem2.CustomizationFormText = " ";
            this.simpleLabelItem2.Image = ((System.Drawing.Image)(resources.GetObject("simpleLabelItem2.Image")));
            this.simpleLabelItem2.ImageAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.simpleLabelItem2.Location = new System.Drawing.Point(200, 34);
            this.simpleLabelItem2.MaxSize = new System.Drawing.Size(28, 0);
            this.simpleLabelItem2.MinSize = new System.Drawing.Size(28, 17);
            this.simpleLabelItem2.Name = "buttonHide";
            this.simpleLabelItem2.Size = new System.Drawing.Size(28, 512);
            this.simpleLabelItem2.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.simpleLabelItem2.Text = " ";
            this.simpleLabelItem2.TextSize = new System.Drawing.Size(127, 13);
            this.simpleLabelItem3.AllowHotTrack = false;
            this.simpleLabelItem3.AppearanceItemCaption.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.BackwardDiagonal;
            this.simpleLabelItem3.CustomizationFormText = " ";
            this.simpleLabelItem3.Image = ((System.Drawing.Image)(resources.GetObject("simpleLabelItem3.Image")));
            this.simpleLabelItem3.ImageAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.simpleLabelItem3.Location = new System.Drawing.Point(200, 34);
            this.simpleLabelItem3.MaxSize = new System.Drawing.Size(28, 0);
            this.simpleLabelItem3.MinSize = new System.Drawing.Size(28, 17);
            this.simpleLabelItem3.Name = "buttonHide";
            this.simpleLabelItem3.Size = new System.Drawing.Size(28, 512);
            this.simpleLabelItem3.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.simpleLabelItem3.Text = " ";
            this.simpleLabelItem3.TextSize = new System.Drawing.Size(127, 13);
            this.simpleLabelItem4.AllowHotTrack = false;
            this.simpleLabelItem4.AppearanceItemCaption.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.BackwardDiagonal;
            this.simpleLabelItem4.CustomizationFormText = " ";
            this.simpleLabelItem4.Image = ((System.Drawing.Image)(resources.GetObject("simpleLabelItem4.Image")));
            this.simpleLabelItem4.ImageAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.simpleLabelItem4.Location = new System.Drawing.Point(200, 34);
            this.simpleLabelItem4.MaxSize = new System.Drawing.Size(28, 0);
            this.simpleLabelItem4.MinSize = new System.Drawing.Size(28, 17);
            this.simpleLabelItem4.Name = "buttonHide";
            this.simpleLabelItem4.Size = new System.Drawing.Size(28, 512);
            this.simpleLabelItem4.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.simpleLabelItem4.Text = " ";
            this.simpleLabelItem4.TextSize = new System.Drawing.Size(127, 13);
            this.simpleLabelItem5.AllowHotTrack = false;
            this.simpleLabelItem5.AppearanceItemCaption.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.BackwardDiagonal;
            this.simpleLabelItem5.CustomizationFormText = " ";
            this.simpleLabelItem5.Image = ((System.Drawing.Image)(resources.GetObject("simpleLabelItem5.Image")));
            this.simpleLabelItem5.ImageAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.simpleLabelItem5.Location = new System.Drawing.Point(200, 34);
            this.simpleLabelItem5.MaxSize = new System.Drawing.Size(28, 0);
            this.simpleLabelItem5.MinSize = new System.Drawing.Size(28, 17);
            this.simpleLabelItem5.Name = "buttonHide";
            this.simpleLabelItem5.Size = new System.Drawing.Size(28, 512);
            this.simpleLabelItem5.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.simpleLabelItem5.Text = " ";
            this.simpleLabelItem5.TextSize = new System.Drawing.Size(127, 13);
            this.simpleLabelItem7.AllowHotTrack = false;
            this.simpleLabelItem7.AppearanceItemCaption.FontSizeDelta = 5;
            this.simpleLabelItem7.AppearanceItemCaption.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(82)))), ((int)(((byte)(163)))));
            this.simpleLabelItem7.AppearanceItemCaption.Options.UseFont = true;
            this.simpleLabelItem7.AppearanceItemCaption.Options.UseForeColor = true;
            this.simpleLabelItem7.CustomizationFormText = "Status";
            this.simpleLabelItem7.Location = new System.Drawing.Point(151, 0);
            this.simpleLabelItem7.Name = "simpleLabelItem1";
            this.simpleLabelItem7.Size = new System.Drawing.Size(830, 34);
            this.simpleLabelItem7.Text = "Status";
            this.simpleLabelItem7.TextSize = new System.Drawing.Size(127, 30);
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 20F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.dataLayoutControl1);
            this.Name = "Tasks";
            this.Size = new System.Drawing.Size(1424, 589);
            ((System.ComponentModel.ISupportInitialize)(this.tasksGridControl)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.tasksGridView)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.repositoryItemComboBox1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.priorityImageList)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.repositoryItemProgressBar1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dataLayoutControl1)).EndInit();
            this.dataLayoutControl1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.taskBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.tileControlLCI)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.buttonHide)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.tasksSLI)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.simpleLabelItem1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.simpleLabelItem2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.simpleLabelItem3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.simpleLabelItem4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.simpleLabelItem5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.simpleLabelItem7)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private XtraGrid.GridControl tasksGridControl;
        private XtraGrid.Views.Grid.GridView tasksGridView;
        private XtraGrid.Columns.GridColumn AssignedTo;
        private XtraGrid.Columns.GridColumn OwnedBy;
        private XtraGrid.Columns.GridColumn Subject;
        private XtraGrid.Columns.GridColumn Priority;
        private XtraEditors.Repository.RepositoryItemImageComboBox repositoryItemComboBox1;
        private XtraGrid.Columns.GridColumn DueDate;
        private XtraGrid.Columns.GridColumn Complete;
        private XtraEditors.Repository.RepositoryItemProgressBar repositoryItemProgressBar1;
        private XtraDataLayout.DataLayoutControl dataLayoutControl1;
        private System.Windows.Forms.BindingSource taskBindingSource;
        private XtraLayout.LayoutControlGroup layoutControlGroup1;
        private XtraLayout.LayoutControlItem layoutControlItem1;
        private XtraEditors.TileControl tileControl1;
        private XtraEditors.TileGroup tileGroup2;
        private XtraEditors.TileItem tileItemAll;
        private XtraEditors.TileItem tileItemInProgress;
        private XtraEditors.TileItem tileItemDeferred;
        private XtraEditors.TileItem tileItemNotStartedTask;
        private XtraEditors.TileItem tileItemCompleted;
        private XtraEditors.TileItem tileItemUrgent;
        private XtraLayout.LayoutControlItem tileControlLCI;
        private XtraLayout.SimpleLabelItem simpleLabelItem1;
        private XtraLayout.SimpleLabelItem simpleLabelItem2;
        private XtraLayout.SimpleLabelItem simpleLabelItem3;
        private XtraLayout.SimpleLabelItem simpleLabelItem4;
        private XtraLayout.SimpleLabelItem simpleLabelItem5;
        private XtraLayout.SimpleLabelItem buttonHide;
        private XtraLayout.SimpleLabelItem simpleLabelItem7;
        private XtraLayout.SimpleLabelItem tasksSLI;
        private XtraEditors.TileItem tileItemHighPriority;
        private Utils.ImageCollection priorityImageList;



    }
}
