#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".
#import sys
#import subprocess

#subprocess.Popen("../../check_copyright.py", shell=True)
ERROR=0
if ! (.githooks/license_check.py Installer/gpl-banner.txt)
then
  ERROR=1
  echo '********** license_check error **********'
fi
if ! (.githooks/check_copyright.py)
then
  ERROR=1
  echo '********** check_copyright error **********'
fi
if [ $ERROR = 1 ]
then
  echo '********** ERROR **********'
  exit 1
fi
exit 0
