namespace DevExpress.DevAV.Modules {
    partial class Dashboard {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing) {
            if(disposing && (components != null)) {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent() {
            this.components = new System.ComponentModel.Container();
            DevExpress.XtraGrid.GridLevelNode gridLevelNode1 = new DevExpress.XtraGrid.GridLevelNode();
            DevExpress.XtraCharts.SimpleDiagram simpleDiagram1 = new DevExpress.XtraCharts.SimpleDiagram();
            DevExpress.XtraCharts.Series series1 = new DevExpress.XtraCharts.Series();
            DevExpress.XtraCharts.FunnelSeriesLabel funnelSeriesLabel1 = new DevExpress.XtraCharts.FunnelSeriesLabel();
            DevExpress.XtraCharts.FunnelSeriesView funnelSeriesView1 = new DevExpress.XtraCharts.FunnelSeriesView();
            DevExpress.XtraCharts.FunnelSeriesView funnelSeriesView2 = new DevExpress.XtraCharts.FunnelSeriesView();
            DevExpress.XtraCharts.SimpleDiagram simpleDiagram2 = new DevExpress.XtraCharts.SimpleDiagram();
            DevExpress.XtraCharts.Series series2 = new DevExpress.XtraCharts.Series();
            DevExpress.XtraCharts.DoughnutSeriesLabel doughnutSeriesLabel1 = new DevExpress.XtraCharts.DoughnutSeriesLabel();
            DevExpress.XtraCharts.DoughnutSeriesView doughnutSeriesView1 = new DevExpress.XtraCharts.DoughnutSeriesView();
            DevExpress.XtraCharts.DoughnutSeriesView doughnutSeriesView2 = new DevExpress.XtraCharts.DoughnutSeriesView();
            DevExpress.XtraCharts.XYDiagram xyDiagram1 = new DevExpress.XtraCharts.XYDiagram();
            DevExpress.XtraCharts.Series series3 = new DevExpress.XtraCharts.Series();
            DevExpress.XtraCharts.SideBySideBarSeriesLabel sideBySideBarSeriesLabel1 = new DevExpress.XtraCharts.SideBySideBarSeriesLabel();
            DevExpress.XtraCharts.SideBySideBarSeriesView sideBySideBarSeriesView1 = new DevExpress.XtraCharts.SideBySideBarSeriesView();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Dashboard));
            this.orderItemsGridView = new DevExpress.XtraGrid.Views.Grid.GridView();
            this.ProductGC = new DevExpress.XtraGrid.Columns.GridColumn();
            this.unitsGridColumn = new DevExpress.XtraGrid.Columns.GridColumn();
            this.unitPriceGridColumn = new DevExpress.XtraGrid.Columns.GridColumn();
            this.totalGridColumn = new DevExpress.XtraGrid.Columns.GridColumn();
            this.discountGridColumn = new DevExpress.XtraGrid.Columns.GridColumn();
            this.salesGridControl = new DevExpress.XtraGrid.GridControl();
            this.salesBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.salesGridView = new DevExpress.XtraGrid.Views.Grid.GridView();
            this.colInvoiceNumber = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colCustomer = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colStore = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colOrderDate = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colTotalAmount = new DevExpress.XtraGrid.Columns.GridColumn();
            this.repositoryItemProgressBar1 = new DevExpress.XtraEditors.Repository.RepositoryItemProgressBar();
            this.repositoryItemComboBox1 = new DevExpress.XtraEditors.Repository.RepositoryItemImageComboBox();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.dataLayoutControl1 = new DevExpress.XtraDataLayout.DataLayoutControl();
            this.opportunitiesChartControl = new DevExpress.XtraCharts.ChartControl();
            this.opportunitiesLayoutControl = new DevExpress.XtraLayout.LayoutControl();
            this.opportunitiesLabelControl = new DevExpress.XtraEditors.LabelControl();
            this.layoutControlGroup4 = new DevExpress.XtraLayout.LayoutControlGroup();
            this.opportunitiesLabelLCI = new DevExpress.XtraLayout.LayoutControlItem();
            this.revenuesChartControl = new DevExpress.XtraCharts.ChartControl();
            this.costLayoutControl = new DevExpress.XtraLayout.LayoutControl();
            this.todayCostSimpleButton = new DevExpress.XtraEditors.CheckButton();
            this.yearCostSimpleButton = new DevExpress.XtraEditors.CheckButton();
            this.monthCostSimpleButton = new DevExpress.XtraEditors.CheckButton();
            this.costLabelControl = new DevExpress.XtraEditors.LabelControl();
            this.layoutControlGroup3 = new DevExpress.XtraLayout.LayoutControlGroup();
            this.costLabelControlLCI = new DevExpress.XtraLayout.LayoutControlItem();
            this.monthCostSimpleButtonLCI = new DevExpress.XtraLayout.LayoutControlItem();
            this.yearCostSimpleButtonLCI = new DevExpress.XtraLayout.LayoutControlItem();
            this.todayCostSimpleButtonLCI = new DevExpress.XtraLayout.LayoutControlItem();
            this.revenuesLayoutControl = new DevExpress.XtraLayout.LayoutControl();
            this.yearRevenuesSimpleButton = new DevExpress.XtraEditors.CheckButton();
            this.monthRevenuesSimpleButton = new DevExpress.XtraEditors.CheckButton();
            this.todayRevenuesSimpleButton = new DevExpress.XtraEditors.CheckButton();
            this.revenuesLabelControl = new DevExpress.XtraEditors.LabelControl();
            this.layoutControlGroup2 = new DevExpress.XtraLayout.LayoutControlGroup();
            this.revenuesLabelLCI = new DevExpress.XtraLayout.LayoutControlItem();
            this.todayRevenuesSimpleButtonLCI = new DevExpress.XtraLayout.LayoutControlItem();
            this.monthRevenuesSimpleButtonLCI = new DevExpress.XtraLayout.LayoutControlItem();
            this.yearRevenuesSimpleButtonLCI = new DevExpress.XtraLayout.LayoutControlItem();
            this.costChartControl = new DevExpress.XtraCharts.ChartControl();
            this.salesLayoutControl = new DevExpress.XtraLayout.LayoutControl();
            this.labelControl1 = new DevExpress.XtraEditors.LabelControl();
            this.searchControl = new DevExpress.XtraEditors.SearchControl();
            this.Root = new DevExpress.XtraLayout.LayoutControlGroup();
            this.searchControlLCI = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem1 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem2 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlGroup1 = new DevExpress.XtraLayout.LayoutControlGroup();
            this.opportunitiesGroup = new DevExpress.XtraLayout.LayoutControlGroup();
            this.opportunitiesLayoutLCI = new DevExpress.XtraLayout.LayoutControlItem();
            this.opportunitiesChartLCI = new DevExpress.XtraLayout.LayoutControlItem();
            this.lgSalesGroup = new DevExpress.XtraLayout.LayoutControlGroup();
            this.emptySpaceItem3 = new DevExpress.XtraLayout.EmptySpaceItem();
            this.revenuesGroup = new DevExpress.XtraLayout.LayoutControlGroup();
            this.revenuesLayoutLCI = new DevExpress.XtraLayout.LayoutControlItem();
            this.revenuesChartLCI = new DevExpress.XtraLayout.LayoutControlItem();
            this.costSoldGroup = new DevExpress.XtraLayout.LayoutControlGroup();
            this.costLayoutLCI = new DevExpress.XtraLayout.LayoutControlItem();
            this.costChartLCI = new DevExpress.XtraLayout.LayoutControlItem();
            this.salesTodayGroup = new DevExpress.XtraLayout.LayoutControlGroup();
            this.salesTodayLayoutLCI = new DevExpress.XtraLayout.LayoutControlItem();
            this.emptySpaceItem1 = new DevExpress.XtraLayout.EmptySpaceItem();
            this.emptySpaceItem2 = new DevExpress.XtraLayout.EmptySpaceItem();
            ((System.ComponentModel.ISupportInitialize)(this.orderItemsGridView)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.salesGridControl)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.salesBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.salesGridView)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.repositoryItemProgressBar1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.repositoryItemComboBox1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dataLayoutControl1)).BeginInit();
            this.dataLayoutControl1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.opportunitiesChartControl)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(simpleDiagram1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(series1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(funnelSeriesLabel1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(funnelSeriesView1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(funnelSeriesView2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.opportunitiesLayoutControl)).BeginInit();
            this.opportunitiesLayoutControl.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.opportunitiesLabelLCI)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.revenuesChartControl)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(simpleDiagram2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(series2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(doughnutSeriesLabel1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(doughnutSeriesView1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(doughnutSeriesView2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.costLayoutControl)).BeginInit();
            this.costLayoutControl.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.costLabelControlLCI)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.monthCostSimpleButtonLCI)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.yearCostSimpleButtonLCI)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.todayCostSimpleButtonLCI)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.revenuesLayoutControl)).BeginInit();
            this.revenuesLayoutControl.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.revenuesLabelLCI)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.todayRevenuesSimpleButtonLCI)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.monthRevenuesSimpleButtonLCI)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.yearRevenuesSimpleButtonLCI)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.costChartControl)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(xyDiagram1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(series3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(sideBySideBarSeriesLabel1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(sideBySideBarSeriesView1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.salesLayoutControl)).BeginInit();
            this.salesLayoutControl.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.searchControl.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.Root)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.searchControlLCI)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.opportunitiesGroup)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.opportunitiesLayoutLCI)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.opportunitiesChartLCI)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.lgSalesGroup)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.revenuesGroup)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.revenuesLayoutLCI)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.revenuesChartLCI)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.costSoldGroup)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.costLayoutLCI)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.costChartLCI)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.salesTodayGroup)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.salesTodayLayoutLCI)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem2)).BeginInit();
            this.SuspendLayout();
            this.orderItemsGridView.Columns.AddRange(new DevExpress.XtraGrid.Columns.GridColumn[] {
            this.ProductGC,
            this.unitsGridColumn,
            this.unitPriceGridColumn,
            this.totalGridColumn,
            this.discountGridColumn});
            this.orderItemsGridView.FocusRectStyle = DevExpress.XtraGrid.Views.Grid.DrawFocusRectStyle.None;
            this.orderItemsGridView.GridControl = this.salesGridControl;
            this.orderItemsGridView.Name = "orderItemsGridView";
            this.orderItemsGridView.OptionsBehavior.Editable = false;
            this.orderItemsGridView.OptionsSelection.EnableAppearanceFocusedCell = false;
            this.orderItemsGridView.OptionsView.ShowGroupPanel = false;
            this.orderItemsGridView.OptionsView.ShowIndicator = false;
            this.orderItemsGridView.PreviewFieldName = "OrderItems";
            this.ProductGC.Caption = "Product";
            this.ProductGC.FieldName = "Product.Name";
            this.ProductGC.Name = "ProductGC";
            this.ProductGC.Visible = true;
            this.ProductGC.VisibleIndex = 0;
            this.ProductGC.Width = 159;
            this.unitsGridColumn.Caption = "Units";
            this.unitsGridColumn.FieldName = "ProductUnits";
            this.unitsGridColumn.Name = "unitsGridColumn";
            this.unitsGridColumn.OptionsColumn.FixedWidth = true;
            this.unitsGridColumn.Visible = true;
            this.unitsGridColumn.VisibleIndex = 1;
            this.unitsGridColumn.Width = 120;
            this.unitPriceGridColumn.Caption = "Unit Price";
            this.unitPriceGridColumn.DisplayFormat.FormatString = "c";
            this.unitPriceGridColumn.DisplayFormat.FormatType = DevExpress.Utils.FormatType.Numeric;
            this.unitPriceGridColumn.FieldName = "ProductPrice";
            this.unitPriceGridColumn.Name = "unitPriceGridColumn";
            this.unitPriceGridColumn.OptionsColumn.FixedWidth = true;
            this.unitPriceGridColumn.Visible = true;
            this.unitPriceGridColumn.VisibleIndex = 2;
            this.unitPriceGridColumn.Width = 120;
            this.totalGridColumn.Caption = "Total";
            this.totalGridColumn.DisplayFormat.FormatString = "c";
            this.totalGridColumn.DisplayFormat.FormatType = DevExpress.Utils.FormatType.Numeric;
            this.totalGridColumn.FieldName = "Total";
            this.totalGridColumn.Name = "totalGridColumn";
            this.totalGridColumn.OptionsColumn.FixedWidth = true;
            this.totalGridColumn.Visible = true;
            this.totalGridColumn.VisibleIndex = 3;
            this.totalGridColumn.Width = 120;
            this.discountGridColumn.Caption = "Discount";
            this.discountGridColumn.DisplayFormat.FormatString = "c";
            this.discountGridColumn.DisplayFormat.FormatType = DevExpress.Utils.FormatType.Numeric;
            this.discountGridColumn.FieldName = "Discount";
            this.discountGridColumn.Name = "discountGridColumn";
            this.discountGridColumn.OptionsColumn.FixedWidth = true;
            this.discountGridColumn.Visible = true;
            this.discountGridColumn.VisibleIndex = 4;
            this.discountGridColumn.Width = 120;
            this.salesGridControl.DataSource = this.salesBindingSource;
            gridLevelNode1.LevelTemplate = this.orderItemsGridView;
            gridLevelNode1.RelationName = "OrderItems";
            this.salesGridControl.LevelTree.Nodes.AddRange(new DevExpress.XtraGrid.GridLevelNode[] {
            gridLevelNode1});
            this.salesGridControl.Location = new System.Drawing.Point(-1, 57);
            this.salesGridControl.MainView = this.salesGridView;
            this.salesGridControl.Name = "salesGridControl";
            this.salesGridControl.RepositoryItems.AddRange(new DevExpress.XtraEditors.Repository.RepositoryItem[] {
            this.repositoryItemProgressBar1,
            this.repositoryItemComboBox1});
            this.salesGridControl.Size = new System.Drawing.Size(763, 307);
            this.salesGridControl.TabIndex = 2;
            this.salesGridControl.ViewCollection.AddRange(new DevExpress.XtraGrid.Views.Base.BaseView[] {
            this.salesGridView,
            this.orderItemsGridView});
            this.salesBindingSource.DataSource = typeof(DevExpress.DevAV.Order);
            this.salesGridView.Columns.AddRange(new DevExpress.XtraGrid.Columns.GridColumn[] {
            this.colInvoiceNumber,
            this.colCustomer,
            this.colStore,
            this.colOrderDate,
            this.colTotalAmount});
            this.salesGridView.FocusRectStyle = DevExpress.XtraGrid.Views.Grid.DrawFocusRectStyle.None;
            this.salesGridView.GridControl = this.salesGridControl;
            this.salesGridView.Name = "salesGridView";
            this.salesGridView.OptionsBehavior.AutoExpandAllGroups = true;
            this.salesGridView.OptionsBehavior.Editable = false;
            this.salesGridView.OptionsCustomization.AllowQuickHideColumns = false;
            this.salesGridView.OptionsDetail.EnableMasterViewMode = false;
            this.salesGridView.OptionsSelection.EnableAppearanceFocusedCell = false;
            this.salesGridView.OptionsView.ShowFilterPanelMode = DevExpress.XtraGrid.Views.Base.ShowFilterPanelMode.Never;
            this.salesGridView.OptionsView.ShowGroupPanel = false;
            this.salesGridView.OptionsView.ShowIndicator = false;
            this.salesGridView.RowHeight = 10;
            this.salesGridView.SortInfo.AddRange(new DevExpress.XtraGrid.Columns.GridColumnSortInfo[] {
            new DevExpress.XtraGrid.Columns.GridColumnSortInfo(this.colInvoiceNumber, DevExpress.Data.ColumnSortOrder.Descending)});
            this.colInvoiceNumber.Caption = "Invoice";
            this.colInvoiceNumber.FieldName = "InvoiceNumber";
            this.colInvoiceNumber.Name = "colInvoiceNumber";
            this.colInvoiceNumber.OptionsColumn.FixedWidth = true;
            this.colInvoiceNumber.Visible = true;
            this.colInvoiceNumber.VisibleIndex = 0;
            this.colInvoiceNumber.Width = 120;
            this.colCustomer.Caption = "Company";
            this.colCustomer.FieldName = "Store.CustomerName";
            this.colCustomer.Name = "colCustomer";
            this.colCustomer.Visible = true;
            this.colCustomer.VisibleIndex = 2;
            this.colCustomer.Width = 117;
            this.colStore.Caption = "Store";
            this.colStore.FieldName = "Store.Address.City";
            this.colStore.Name = "colStore";
            this.colStore.Visible = true;
            this.colStore.VisibleIndex = 3;
            this.colStore.Width = 112;
            this.colOrderDate.FieldName = "OrderDate";
            this.colOrderDate.Name = "colOrderDate";
            this.colOrderDate.OptionsColumn.FixedWidth = true;
            this.colOrderDate.Visible = true;
            this.colOrderDate.VisibleIndex = 1;
            this.colOrderDate.Width = 100;
            this.colTotalAmount.DisplayFormat.FormatString = "c";
            this.colTotalAmount.DisplayFormat.FormatType = DevExpress.Utils.FormatType.Numeric;
            this.colTotalAmount.FieldName = "TotalAmount";
            this.colTotalAmount.Name = "colTotalAmount";
            this.colTotalAmount.OptionsColumn.FixedWidth = true;
            this.colTotalAmount.Visible = true;
            this.colTotalAmount.VisibleIndex = 4;
            this.colTotalAmount.Width = 129;
            this.repositoryItemProgressBar1.Name = "repositoryItemProgressBar1";
            this.repositoryItemProgressBar1.ProgressViewStyle = DevExpress.XtraEditors.Controls.ProgressViewStyle.Solid;
            this.repositoryItemProgressBar1.ShowTitle = true;
            this.repositoryItemComboBox1.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            this.repositoryItemComboBox1.Items.AddRange(new DevExpress.XtraEditors.Controls.ImageComboBoxItem[] {
            new DevExpress.XtraEditors.Controls.ImageComboBoxItem("", DevExpress.DevAV.EmployeeTaskPriority.Low, 0),
            new DevExpress.XtraEditors.Controls.ImageComboBoxItem("", DevExpress.DevAV.EmployeeTaskPriority.Normal, 2),
            new DevExpress.XtraEditors.Controls.ImageComboBoxItem("", DevExpress.DevAV.EmployeeTaskPriority.High, 1),
            new DevExpress.XtraEditors.Controls.ImageComboBoxItem("", DevExpress.DevAV.EmployeeTaskPriority.Urgent, 1)});
            this.repositoryItemComboBox1.Name = "repositoryItemComboBox1";
            this.repositoryItemComboBox1.PopupSizeable = true;
            this.pictureBox1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pictureBox1.InitialImage = null;
            this.pictureBox1.Location = new System.Drawing.Point(0, 0);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(1166, 617);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.AutoSize;
            this.pictureBox1.TabIndex = 0;
            this.pictureBox1.TabStop = false;
            this.dataLayoutControl1.AllowCustomization = false;
            this.dataLayoutControl1.Controls.Add(this.opportunitiesChartControl);
            this.dataLayoutControl1.Controls.Add(this.opportunitiesLayoutControl);
            this.dataLayoutControl1.Controls.Add(this.revenuesChartControl);
            this.dataLayoutControl1.Controls.Add(this.costLayoutControl);
            this.dataLayoutControl1.Controls.Add(this.revenuesLayoutControl);
            this.dataLayoutControl1.Controls.Add(this.costChartControl);
            this.dataLayoutControl1.Controls.Add(this.salesLayoutControl);
            this.dataLayoutControl1.DataSource = this.salesBindingSource;
            this.dataLayoutControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dataLayoutControl1.Location = new System.Drawing.Point(0, 0);
            this.dataLayoutControl1.Name = "dataLayoutControl1";
            this.dataLayoutControl1.OptionsCustomizationForm.DesignTimeCustomizationFormPositionAndSize = new System.Drawing.Rectangle(773, 662, 830, 674);
            this.dataLayoutControl1.Root = this.layoutControlGroup1;
            this.dataLayoutControl1.Size = new System.Drawing.Size(1166, 617);
            this.dataLayoutControl1.TabIndex = 1;
            this.dataLayoutControl1.Text = "dataLayoutControl1";
            this.opportunitiesChartControl.AccessibleName = "";
            this.opportunitiesChartControl.AllowDrop = true;
            this.opportunitiesChartControl.BorderOptions.Visibility = DevExpress.Utils.DefaultBoolean.False;
            simpleDiagram1.EqualPieSize = false;
            this.opportunitiesChartControl.Diagram = simpleDiagram1;
            this.opportunitiesChartControl.Legend.AlignmentHorizontal = DevExpress.XtraCharts.LegendAlignmentHorizontal.Center;
            this.opportunitiesChartControl.Legend.AlignmentVertical = DevExpress.XtraCharts.LegendAlignmentVertical.BottomOutside;
            this.opportunitiesChartControl.Legend.Antialiasing = true;
            this.opportunitiesChartControl.Legend.Border.Visibility = DevExpress.Utils.DefaultBoolean.False;
            this.opportunitiesChartControl.Legend.Direction = DevExpress.XtraCharts.LegendDirection.LeftToRight;
            this.opportunitiesChartControl.Legend.Font = new System.Drawing.Font("Segoe UI", 8F);
            this.opportunitiesChartControl.Legend.Margins.Bottom = 0;
            this.opportunitiesChartControl.Legend.Margins.Left = 0;
            this.opportunitiesChartControl.Legend.Margins.Right = 0;
            this.opportunitiesChartControl.Legend.Margins.Top = 0;
            this.opportunitiesChartControl.Legend.MarkerSize = new System.Drawing.Size(26, 20);
            this.opportunitiesChartControl.Legend.Padding.Bottom = 0;
            this.opportunitiesChartControl.Legend.Padding.Left = 0;
            this.opportunitiesChartControl.Legend.Padding.Right = 0;
            this.opportunitiesChartControl.Legend.Padding.Top = 40;
            this.opportunitiesChartControl.Location = new System.Drawing.Point(794, 77);
            this.opportunitiesChartControl.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.opportunitiesChartControl.Name = "opportunitiesChartControl";
            this.opportunitiesChartControl.PaletteName = "Palette 1";
            this.opportunitiesChartControl.PaletteRepository.Add("Palette 1", new DevExpress.XtraCharts.Palette("Palette 1", DevExpress.XtraCharts.PaletteScaleMode.Repeat, new DevExpress.XtraCharts.PaletteEntry[] {
                new DevExpress.XtraCharts.PaletteEntry(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(133)))), ((int)(((byte)(156))))), System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(133)))), ((int)(((byte)(156)))))),
                new DevExpress.XtraCharts.PaletteEntry(System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(85)))), ((int)(((byte)(85))))), System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(85)))), ((int)(((byte)(85)))))),
                new DevExpress.XtraCharts.PaletteEntry(System.Drawing.Color.FromArgb(((int)(((byte)(206)))), ((int)(((byte)(113)))), ((int)(((byte)(0))))), System.Drawing.Color.FromArgb(((int)(((byte)(206)))), ((int)(((byte)(113)))), ((int)(((byte)(0)))))),
                new DevExpress.XtraCharts.PaletteEntry(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(114)))), ((int)(((byte)(198))))), System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(114)))), ((int)(((byte)(198))))))}));
            funnelSeriesLabel1.Antialiasing = true;
            funnelSeriesLabel1.BackColor = System.Drawing.Color.Transparent;
            funnelSeriesLabel1.Border.Visibility = DevExpress.Utils.DefaultBoolean.False;
            funnelSeriesLabel1.Font = new System.Drawing.Font("Segoe UI", 10F);
            funnelSeriesLabel1.Position = DevExpress.XtraCharts.FunnelSeriesLabelPosition.Center;
            funnelSeriesLabel1.TextColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            funnelSeriesLabel1.TextPattern = "{V:$##,#0}";
            series1.Label = funnelSeriesLabel1;
            series1.LegendTextPattern = "{A}";
            series1.Name = "Series 1";
            funnelSeriesView1.AlignToCenter = true;
            series1.View = funnelSeriesView1;
            this.opportunitiesChartControl.SeriesSerializable = new DevExpress.XtraCharts.Series[] {
        series1};
            this.opportunitiesChartControl.SeriesTemplate.View = funnelSeriesView2;
            this.opportunitiesChartControl.Size = new System.Drawing.Size(351, 519);
            this.opportunitiesChartControl.TabIndex = 6;
            this.opportunitiesChartControl.CustomDrawSeriesPoint += new DevExpress.XtraCharts.CustomDrawSeriesPointEventHandler(this.opportunitiesChartControl_CustomDrawSeriesPoint);
            this.opportunitiesLayoutControl.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(246)))), ((int)(((byte)(246)))));
            this.opportunitiesLayoutControl.Controls.Add(this.opportunitiesLabelControl);
            this.opportunitiesLayoutControl.Location = new System.Drawing.Point(794, 21);
            this.opportunitiesLayoutControl.Name = "opportunitiesLayoutControl";
            this.opportunitiesLayoutControl.OptionsCustomizationForm.DesignTimeCustomizationFormPositionAndSize = new System.Drawing.Rectangle(946, 87, 915, 863);
            this.opportunitiesLayoutControl.Root = this.layoutControlGroup4;
            this.opportunitiesLayoutControl.Size = new System.Drawing.Size(351, 56);
            this.opportunitiesLayoutControl.TabIndex = 21;
            this.opportunitiesLayoutControl.Text = "layoutControl2";
            this.opportunitiesLabelControl.Appearance.ForeColor = System.Drawing.Color.Black;
            this.opportunitiesLabelControl.Location = new System.Drawing.Point(10, 2);
            this.opportunitiesLabelControl.Name = "opportunitiesLabelControl";
            this.opportunitiesLabelControl.Size = new System.Drawing.Size(339, 52);
            this.opportunitiesLabelControl.StyleController = this.opportunitiesLayoutControl;
            this.opportunitiesLabelControl.TabIndex = 19;
            this.opportunitiesLabelControl.Text = "OPPORTUNITIES";
            this.layoutControlGroup4.CustomizationFormText = "Root";
            this.layoutControlGroup4.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True;
            this.layoutControlGroup4.GroupBordersVisible = false;
            this.layoutControlGroup4.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.opportunitiesLabelLCI});
            this.layoutControlGroup4.Location = new System.Drawing.Point(0, 0);
            this.layoutControlGroup4.Name = "Root";
            this.layoutControlGroup4.Padding = new DevExpress.XtraLayout.Utils.Padding(0, 0, 0, 0);
            this.layoutControlGroup4.Size = new System.Drawing.Size(351, 56);
            this.layoutControlGroup4.TextVisible = false;
            this.opportunitiesLabelLCI.Control = this.opportunitiesLabelControl;
            this.opportunitiesLabelLCI.CustomizationFormText = "layoutControlItem4";
            this.opportunitiesLabelLCI.Location = new System.Drawing.Point(0, 0);
            this.opportunitiesLabelLCI.MaxSize = new System.Drawing.Size(0, 56);
            this.opportunitiesLabelLCI.MinSize = new System.Drawing.Size(94, 56);
            this.opportunitiesLabelLCI.Name = "opportunitiesLabelLCI";
            this.opportunitiesLabelLCI.Padding = new DevExpress.XtraLayout.Utils.Padding(10, 2, 2, 2);
            this.opportunitiesLabelLCI.Size = new System.Drawing.Size(351, 56);
            this.opportunitiesLabelLCI.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.opportunitiesLabelLCI.TextSize = new System.Drawing.Size(0, 0);
            this.opportunitiesLabelLCI.TextVisible = false;
            this.revenuesChartControl.BorderOptions.Visibility = DevExpress.Utils.DefaultBoolean.False;
            simpleDiagram2.EqualPieSize = false;
            this.revenuesChartControl.Diagram = simpleDiagram2;
            this.revenuesChartControl.Legend.AlignmentVertical = DevExpress.XtraCharts.LegendAlignmentVertical.Center;
            this.revenuesChartControl.Legend.Antialiasing = true;
            this.revenuesChartControl.Legend.Border.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.revenuesChartControl.Legend.Border.Visibility = DevExpress.Utils.DefaultBoolean.False;
            this.revenuesChartControl.Legend.EquallySpacedItems = false;
            this.revenuesChartControl.Legend.Font = new System.Drawing.Font("Segoe UI", 8F);
            this.revenuesChartControl.Location = new System.Drawing.Point(23, 454);
            this.revenuesChartControl.Name = "revenuesChartControl";
            this.revenuesChartControl.OptionsPrint.SizeMode = DevExpress.XtraCharts.Printing.PrintSizeMode.Zoom;
            this.revenuesChartControl.PaletteName = "Palette 11";
            this.revenuesChartControl.PaletteRepository.Add("Palette 1", new DevExpress.XtraCharts.Palette("Palette 1", DevExpress.XtraCharts.PaletteScaleMode.Repeat, new DevExpress.XtraCharts.PaletteEntry[] {
                new DevExpress.XtraCharts.PaletteEntry(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(133)))), ((int)(((byte)(156))))), System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(133)))), ((int)(((byte)(156)))))),
                new DevExpress.XtraCharts.PaletteEntry(System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(85)))), ((int)(((byte)(85))))), System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(85)))), ((int)(((byte)(85)))))),
                new DevExpress.XtraCharts.PaletteEntry(System.Drawing.Color.FromArgb(((int)(((byte)(206)))), ((int)(((byte)(113)))), ((int)(((byte)(0))))), System.Drawing.Color.FromArgb(((int)(((byte)(206)))), ((int)(((byte)(113)))), ((int)(((byte)(0)))))),
                new DevExpress.XtraCharts.PaletteEntry(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(114)))), ((int)(((byte)(198))))), System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(114)))), ((int)(((byte)(198)))))),
                new DevExpress.XtraCharts.PaletteEntry(System.Drawing.Color.FromArgb(((int)(((byte)(62)))), ((int)(((byte)(112)))), ((int)(((byte)(56))))), System.Drawing.Color.FromArgb(((int)(((byte)(62)))), ((int)(((byte)(112)))), ((int)(((byte)(56))))))}));
            this.revenuesChartControl.PaletteRepository.Add("Palette 11", new DevExpress.XtraCharts.Palette("Palette 11", DevExpress.XtraCharts.PaletteScaleMode.Repeat, new DevExpress.XtraCharts.PaletteEntry[] {
                new DevExpress.XtraCharts.PaletteEntry(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(133)))), ((int)(((byte)(156))))), System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(133)))), ((int)(((byte)(156)))))),
                new DevExpress.XtraCharts.PaletteEntry(System.Drawing.Color.FromArgb(((int)(((byte)(206)))), ((int)(((byte)(113)))), ((int)(((byte)(0))))), System.Drawing.Color.FromArgb(((int)(((byte)(206)))), ((int)(((byte)(113)))), ((int)(((byte)(0)))))),
                new DevExpress.XtraCharts.PaletteEntry(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(114)))), ((int)(((byte)(198))))), System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(114)))), ((int)(((byte)(198)))))),
                new DevExpress.XtraCharts.PaletteEntry(System.Drawing.Color.FromArgb(((int)(((byte)(61)))), ((int)(((byte)(113)))), ((int)(((byte)(56))))), System.Drawing.Color.FromArgb(((int)(((byte)(61)))), ((int)(((byte)(113)))), ((int)(((byte)(56)))))),
                new DevExpress.XtraCharts.PaletteEntry(System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(85)))), ((int)(((byte)(85))))), System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(85)))), ((int)(((byte)(85))))))}));
            doughnutSeriesLabel1.Antialiasing = true;
            doughnutSeriesLabel1.Font = new System.Drawing.Font("Segoe UI", 10F);
            doughnutSeriesLabel1.TextPattern = "{V:$##,#0}";
            series2.Label = doughnutSeriesLabel1;
            series2.LabelsVisibility = DevExpress.Utils.DefaultBoolean.False;
            series2.LegendTextPattern = "{A} {V:c}";
            series2.Name = "Series 1";
            doughnutSeriesView1.HoleRadiusPercent = 56;
            doughnutSeriesView1.RuntimeExploding = false;
            doughnutSeriesView1.SweepDirection = DevExpress.XtraCharts.PieSweepDirection.Counterclockwise;
            series2.View = doughnutSeriesView1;
            this.revenuesChartControl.SeriesSerializable = new DevExpress.XtraCharts.Series[] {
        series2};
            doughnutSeriesView2.RuntimeExploding = false;
            doughnutSeriesView2.SweepDirection = DevExpress.XtraCharts.PieSweepDirection.Counterclockwise;
            this.revenuesChartControl.SeriesTemplate.View = doughnutSeriesView2;
            this.revenuesChartControl.Size = new System.Drawing.Size(367, 140);
            this.revenuesChartControl.SmallChartText.Text = "Increase the chart\'s size,\r\nto view its layout.\r\n";
            this.revenuesChartControl.TabIndex = 5;
            this.revenuesChartControl.CustomDrawSeriesPoint += new DevExpress.XtraCharts.CustomDrawSeriesPointEventHandler(this.revenuesChartControl_CustomDrawSeriesPoint);
            this.costLayoutControl.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(246)))), ((int)(((byte)(246)))));
            this.costLayoutControl.Controls.Add(this.todayCostSimpleButton);
            this.costLayoutControl.Controls.Add(this.yearCostSimpleButton);
            this.costLayoutControl.Controls.Add(this.monthCostSimpleButton);
            this.costLayoutControl.Controls.Add(this.costLabelControl);
            this.costLayoutControl.Location = new System.Drawing.Point(404, 396);
            this.costLayoutControl.Name = "costLayoutControl";
            this.costLayoutControl.OptionsCustomizationForm.DesignTimeCustomizationFormPositionAndSize = new System.Drawing.Rectangle(1082, 51, 821, 894);
            this.costLayoutControl.Root = this.layoutControlGroup3;
            this.costLayoutControl.Size = new System.Drawing.Size(378, 56);
            this.costLayoutControl.TabIndex = 24;
            this.costLayoutControl.Text = "layoutControl3";
            this.todayCostSimpleButton.GroupIndex = 2;
            this.todayCostSimpleButton.Location = new System.Drawing.Point(153, 15);
            this.todayCostSimpleButton.Name = "todayCostSimpleButton";
            this.todayCostSimpleButton.Size = new System.Drawing.Size(57, 25);
            this.todayCostSimpleButton.StyleController = this.costLayoutControl;
            this.todayCostSimpleButton.TabIndex = 8;
            this.todayCostSimpleButton.TabStop = false;
            this.todayCostSimpleButton.Text = "Today";
            this.todayCostSimpleButton.Click += new System.EventHandler(this.todayCostSimpleButton_Click);
            this.yearCostSimpleButton.Checked = true;
            this.yearCostSimpleButton.GroupIndex = 2;
            this.yearCostSimpleButton.Location = new System.Drawing.Point(309, 15);
            this.yearCostSimpleButton.Name = "yearCostSimpleButton";
            this.yearCostSimpleButton.Size = new System.Drawing.Size(44, 25);
            this.yearCostSimpleButton.StyleController = this.costLayoutControl;
            this.yearCostSimpleButton.TabIndex = 8;
            this.yearCostSimpleButton.Text = "YTD";
            this.yearCostSimpleButton.Click += new System.EventHandler(this.yearCostSimpleButton_Click);
            this.monthCostSimpleButton.GroupIndex = 2;
            this.monthCostSimpleButton.Location = new System.Drawing.Point(214, 15);
            this.monthCostSimpleButton.Name = "monthCostSimpleButton";
            this.monthCostSimpleButton.Size = new System.Drawing.Size(91, 25);
            this.monthCostSimpleButton.StyleController = this.costLayoutControl;
            this.monthCostSimpleButton.TabIndex = 8;
            this.monthCostSimpleButton.TabStop = false;
            this.monthCostSimpleButton.Text = "This Month";
            this.monthCostSimpleButton.Click += new System.EventHandler(this.monthCostSimpleButton_Click);
            this.costLabelControl.Appearance.ForeColor = System.Drawing.Color.Black;
            this.costLabelControl.Location = new System.Drawing.Point(10, 2);
            this.costLabelControl.Name = "costLabelControl";
            this.costLabelControl.Size = new System.Drawing.Size(139, 52);
            this.costLabelControl.StyleController = this.costLayoutControl;
            this.costLabelControl.TabIndex = 4;
            this.costLabelControl.Text = "COST OF GOODS SOLD";
            this.layoutControlGroup3.CustomizationFormText = "layoutControlGroup3";
            this.layoutControlGroup3.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True;
            this.layoutControlGroup3.GroupBordersVisible = false;
            this.layoutControlGroup3.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.costLabelControlLCI,
            this.monthCostSimpleButtonLCI,
            this.yearCostSimpleButtonLCI,
            this.todayCostSimpleButtonLCI});
            this.layoutControlGroup3.Location = new System.Drawing.Point(0, 0);
            this.layoutControlGroup3.Name = "layoutControlGroup3";
            this.layoutControlGroup3.Padding = new DevExpress.XtraLayout.Utils.Padding(0, 0, 0, 0);
            this.layoutControlGroup3.Size = new System.Drawing.Size(378, 56);
            this.layoutControlGroup3.TextVisible = false;
            this.costLabelControlLCI.Control = this.costLabelControl;
            this.costLabelControlLCI.CustomizationFormText = "costLabelControlLCI";
            this.costLabelControlLCI.Location = new System.Drawing.Point(0, 0);
            this.costLabelControlLCI.MinSize = new System.Drawing.Size(94, 24);
            this.costLabelControlLCI.Name = "costLabelControlLCI";
            this.costLabelControlLCI.Padding = new DevExpress.XtraLayout.Utils.Padding(10, 2, 2, 2);
            this.costLabelControlLCI.Size = new System.Drawing.Size(151, 56);
            this.costLabelControlLCI.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.costLabelControlLCI.TextSize = new System.Drawing.Size(0, 0);
            this.costLabelControlLCI.TextVisible = false;
            this.monthCostSimpleButtonLCI.Control = this.monthCostSimpleButton;
            this.monthCostSimpleButtonLCI.ControlAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.monthCostSimpleButtonLCI.CustomizationFormText = "monthCostSimpleButtonLCI";
            this.monthCostSimpleButtonLCI.Location = new System.Drawing.Point(212, 0);
            this.monthCostSimpleButtonLCI.Name = "monthCostSimpleButtonLCI";
            this.monthCostSimpleButtonLCI.OptionsPrint.AllowPrint = false;
            this.monthCostSimpleButtonLCI.Size = new System.Drawing.Size(95, 56);
            this.monthCostSimpleButtonLCI.TextSize = new System.Drawing.Size(0, 0);
            this.monthCostSimpleButtonLCI.TextVisible = false;
            this.monthCostSimpleButtonLCI.TrimClientAreaToControl = false;
            this.yearCostSimpleButtonLCI.Control = this.yearCostSimpleButton;
            this.yearCostSimpleButtonLCI.ControlAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.yearCostSimpleButtonLCI.CustomizationFormText = "yearCostSimpleButtonLCI";
            this.yearCostSimpleButtonLCI.Location = new System.Drawing.Point(307, 0);
            this.yearCostSimpleButtonLCI.Name = "yearCostSimpleButtonLCI";
            this.yearCostSimpleButtonLCI.OptionsPrint.AllowPrint = false;
            this.yearCostSimpleButtonLCI.Padding = new DevExpress.XtraLayout.Utils.Padding(2, 25, 2, 2);
            this.yearCostSimpleButtonLCI.Size = new System.Drawing.Size(71, 56);
            this.yearCostSimpleButtonLCI.TextSize = new System.Drawing.Size(0, 0);
            this.yearCostSimpleButtonLCI.TextVisible = false;
            this.yearCostSimpleButtonLCI.TrimClientAreaToControl = false;
            this.todayCostSimpleButtonLCI.Control = this.todayCostSimpleButton;
            this.todayCostSimpleButtonLCI.ControlAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.todayCostSimpleButtonLCI.CustomizationFormText = "todayCostSimpleButtonLCI";
            this.todayCostSimpleButtonLCI.Location = new System.Drawing.Point(151, 0);
            this.todayCostSimpleButtonLCI.Name = "todayCostSimpleButtonLCI";
            this.todayCostSimpleButtonLCI.OptionsPrint.AllowPrint = false;
            this.todayCostSimpleButtonLCI.Size = new System.Drawing.Size(61, 56);
            this.todayCostSimpleButtonLCI.TextSize = new System.Drawing.Size(0, 0);
            this.todayCostSimpleButtonLCI.TextVisible = false;
            this.todayCostSimpleButtonLCI.TrimClientAreaToControl = false;
            this.revenuesLayoutControl.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(246)))), ((int)(((byte)(246)))));
            this.revenuesLayoutControl.Controls.Add(this.yearRevenuesSimpleButton);
            this.revenuesLayoutControl.Controls.Add(this.monthRevenuesSimpleButton);
            this.revenuesLayoutControl.Controls.Add(this.todayRevenuesSimpleButton);
            this.revenuesLayoutControl.Controls.Add(this.revenuesLabelControl);
            this.revenuesLayoutControl.Location = new System.Drawing.Point(21, 396);
            this.revenuesLayoutControl.Name = "revenuesLayoutControl";
            this.revenuesLayoutControl.OptionsCustomizationForm.DesignTimeCustomizationFormPositionAndSize = new System.Drawing.Rectangle(687, 50, 450, 350);
            this.revenuesLayoutControl.Root = this.layoutControlGroup2;
            this.revenuesLayoutControl.Size = new System.Drawing.Size(371, 56);
            this.revenuesLayoutControl.TabIndex = 23;
            this.revenuesLayoutControl.Text = "layoutControl2";
            this.yearRevenuesSimpleButton.Checked = true;
            this.yearRevenuesSimpleButton.GroupIndex = 1;
            this.yearRevenuesSimpleButton.Location = new System.Drawing.Point(308, 15);
            this.yearRevenuesSimpleButton.Name = "yearRevenuesSimpleButton";
            this.yearRevenuesSimpleButton.Size = new System.Drawing.Size(38, 25);
            this.yearRevenuesSimpleButton.StyleController = this.revenuesLayoutControl;
            this.yearRevenuesSimpleButton.TabIndex = 7;
            this.yearRevenuesSimpleButton.Text = "YTD";
            this.yearRevenuesSimpleButton.Click += new System.EventHandler(this.yearRevenuesSimpleButton_Click);
            this.monthRevenuesSimpleButton.GroupIndex = 1;
            this.monthRevenuesSimpleButton.Location = new System.Drawing.Point(220, 15);
            this.monthRevenuesSimpleButton.Name = "monthRevenuesSimpleButton";
            this.monthRevenuesSimpleButton.Size = new System.Drawing.Size(84, 25);
            this.monthRevenuesSimpleButton.StyleController = this.revenuesLayoutControl;
            this.monthRevenuesSimpleButton.TabIndex = 6;
            this.monthRevenuesSimpleButton.TabStop = false;
            this.monthRevenuesSimpleButton.Text = "This Month";
            this.monthRevenuesSimpleButton.Click += new System.EventHandler(this.monthRevenuesSimpleButton_Click);
            this.todayRevenuesSimpleButton.GroupIndex = 1;
            this.todayRevenuesSimpleButton.Location = new System.Drawing.Point(164, 15);
            this.todayRevenuesSimpleButton.Name = "todayRevenuesSimpleButton";
            this.todayRevenuesSimpleButton.Size = new System.Drawing.Size(52, 25);
            this.todayRevenuesSimpleButton.StyleController = this.revenuesLayoutControl;
            this.todayRevenuesSimpleButton.TabIndex = 5;
            this.todayRevenuesSimpleButton.TabStop = false;
            this.todayRevenuesSimpleButton.Text = "Today";
            this.todayRevenuesSimpleButton.Click += new System.EventHandler(this.todayRevenuesSimpleButton_Click);
            this.revenuesLabelControl.Appearance.ForeColor = System.Drawing.Color.Black;
            this.revenuesLabelControl.Location = new System.Drawing.Point(10, 2);
            this.revenuesLabelControl.Name = "revenuesLabelControl";
            this.revenuesLabelControl.Size = new System.Drawing.Size(150, 52);
            this.revenuesLabelControl.StyleController = this.revenuesLayoutControl;
            this.revenuesLabelControl.TabIndex = 4;
            this.revenuesLabelControl.Text = "REVENUES";
            this.layoutControlGroup2.CustomizationFormText = "layoutControlGroup2";
            this.layoutControlGroup2.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True;
            this.layoutControlGroup2.GroupBordersVisible = false;
            this.layoutControlGroup2.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.revenuesLabelLCI,
            this.todayRevenuesSimpleButtonLCI,
            this.monthRevenuesSimpleButtonLCI,
            this.yearRevenuesSimpleButtonLCI});
            this.layoutControlGroup2.Location = new System.Drawing.Point(0, 0);
            this.layoutControlGroup2.Name = "layoutControlGroup2";
            this.layoutControlGroup2.Padding = new DevExpress.XtraLayout.Utils.Padding(0, 0, 0, 0);
            this.layoutControlGroup2.Size = new System.Drawing.Size(371, 56);
            this.layoutControlGroup2.TextVisible = false;
            this.revenuesLabelLCI.Control = this.revenuesLabelControl;
            this.revenuesLabelLCI.CustomizationFormText = "revenuesLabelLCI";
            this.revenuesLabelLCI.Location = new System.Drawing.Point(0, 0);
            this.revenuesLabelLCI.MinSize = new System.Drawing.Size(94, 24);
            this.revenuesLabelLCI.Name = "revenuesLabelLCI";
            this.revenuesLabelLCI.Padding = new DevExpress.XtraLayout.Utils.Padding(10, 2, 2, 2);
            this.revenuesLabelLCI.Size = new System.Drawing.Size(162, 56);
            this.revenuesLabelLCI.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.revenuesLabelLCI.TextSize = new System.Drawing.Size(0, 0);
            this.revenuesLabelLCI.TextVisible = false;
            this.todayRevenuesSimpleButtonLCI.Control = this.todayRevenuesSimpleButton;
            this.todayRevenuesSimpleButtonLCI.ControlAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.todayRevenuesSimpleButtonLCI.CustomizationFormText = "todayRevenuesSimpleButtonLCI";
            this.todayRevenuesSimpleButtonLCI.Location = new System.Drawing.Point(162, 0);
            this.todayRevenuesSimpleButtonLCI.Name = "todayRevenuesSimpleButtonLCI";
            this.todayRevenuesSimpleButtonLCI.OptionsPrint.AllowPrint = false;
            this.todayRevenuesSimpleButtonLCI.Size = new System.Drawing.Size(56, 56);
            this.todayRevenuesSimpleButtonLCI.TextSize = new System.Drawing.Size(0, 0);
            this.todayRevenuesSimpleButtonLCI.TextVisible = false;
            this.todayRevenuesSimpleButtonLCI.TrimClientAreaToControl = false;
            this.monthRevenuesSimpleButtonLCI.Control = this.monthRevenuesSimpleButton;
            this.monthRevenuesSimpleButtonLCI.ControlAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.monthRevenuesSimpleButtonLCI.CustomizationFormText = "monthRevenuesSimpleButtonLCI";
            this.monthRevenuesSimpleButtonLCI.Location = new System.Drawing.Point(218, 0);
            this.monthRevenuesSimpleButtonLCI.Name = "monthRevenuesSimpleButtonLCI";
            this.monthRevenuesSimpleButtonLCI.OptionsPrint.AllowPrint = false;
            this.monthRevenuesSimpleButtonLCI.Size = new System.Drawing.Size(88, 56);
            this.monthRevenuesSimpleButtonLCI.TextSize = new System.Drawing.Size(0, 0);
            this.monthRevenuesSimpleButtonLCI.TextVisible = false;
            this.monthRevenuesSimpleButtonLCI.TrimClientAreaToControl = false;
            this.yearRevenuesSimpleButtonLCI.Control = this.yearRevenuesSimpleButton;
            this.yearRevenuesSimpleButtonLCI.ControlAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.yearRevenuesSimpleButtonLCI.CustomizationFormText = "yearRevenuesSimpleButtonLCI";
            this.yearRevenuesSimpleButtonLCI.Location = new System.Drawing.Point(306, 0);
            this.yearRevenuesSimpleButtonLCI.Name = "yearRevenuesSimpleButtonLCI";
            this.yearRevenuesSimpleButtonLCI.OptionsPrint.AllowPrint = false;
            this.yearRevenuesSimpleButtonLCI.Padding = new DevExpress.XtraLayout.Utils.Padding(2, 25, 2, 2);
            this.yearRevenuesSimpleButtonLCI.Size = new System.Drawing.Size(65, 56);
            this.yearRevenuesSimpleButtonLCI.TextSize = new System.Drawing.Size(0, 0);
            this.yearRevenuesSimpleButtonLCI.TextVisible = false;
            this.yearRevenuesSimpleButtonLCI.TrimClientAreaToControl = false;
            this.costChartControl.BorderOptions.Visibility = DevExpress.Utils.DefaultBoolean.False;
            xyDiagram1.AxisX.Label.Font = new System.Drawing.Font("Segoe UI", 8F);
            xyDiagram1.AxisX.Visibility = DevExpress.Utils.DefaultBoolean.False;
            xyDiagram1.AxisX.VisibleInPanesSerializable = "-1";
            xyDiagram1.AxisY.Label.EnableAntialiasing = DevExpress.Utils.DefaultBoolean.True;
            xyDiagram1.AxisY.Label.Font = new System.Drawing.Font("Segoe UI", 8F);
            xyDiagram1.AxisY.Label.TextPattern = "{V:$##,#0}";
            xyDiagram1.AxisY.VisibleInPanesSerializable = "-1";
            xyDiagram1.DefaultPane.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            xyDiagram1.Margins.Bottom = 0;
            xyDiagram1.Margins.Left = 0;
            xyDiagram1.Margins.Right = 0;
            xyDiagram1.Margins.Top = 0;
            xyDiagram1.PaneDistance = 14;
            xyDiagram1.Rotated = true;
            this.costChartControl.Diagram = xyDiagram1;
            this.costChartControl.EmptyChartText.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.costChartControl.Legend.AlignmentHorizontal = DevExpress.XtraCharts.LegendAlignmentHorizontal.Center;
            this.costChartControl.Legend.AlignmentVertical = DevExpress.XtraCharts.LegendAlignmentVertical.BottomOutside;
            this.costChartControl.Legend.Antialiasing = true;
            this.costChartControl.Legend.Border.Visibility = DevExpress.Utils.DefaultBoolean.False;
            this.costChartControl.Legend.Direction = DevExpress.XtraCharts.LegendDirection.LeftToRight;
            this.costChartControl.Legend.Font = new System.Drawing.Font("Segoe UI", 8F);
            this.costChartControl.Legend.Margins.Bottom = 0;
            this.costChartControl.Legend.Margins.Left = 0;
            this.costChartControl.Legend.Margins.Right = 0;
            this.costChartControl.Legend.Margins.Top = 40;
            this.costChartControl.Location = new System.Drawing.Point(404, 452);
            this.costChartControl.Name = "costChartControl";
            this.costChartControl.OptionsPrint.SizeMode = DevExpress.XtraCharts.Printing.PrintSizeMode.Zoom;
            this.costChartControl.PaletteName = "Palette 1";
            this.costChartControl.PaletteRepository.Add("Palette 1", new DevExpress.XtraCharts.Palette("Palette 1", DevExpress.XtraCharts.PaletteScaleMode.Repeat, new DevExpress.XtraCharts.PaletteEntry[] {
                new DevExpress.XtraCharts.PaletteEntry(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(133)))), ((int)(((byte)(156))))), System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(133)))), ((int)(((byte)(156)))))),
                new DevExpress.XtraCharts.PaletteEntry(System.Drawing.Color.FromArgb(((int)(((byte)(206)))), ((int)(((byte)(113)))), ((int)(((byte)(0))))), System.Drawing.Color.FromArgb(((int)(((byte)(206)))), ((int)(((byte)(113)))), ((int)(((byte)(0)))))),
                new DevExpress.XtraCharts.PaletteEntry(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(114)))), ((int)(((byte)(198))))), System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(114)))), ((int)(((byte)(198)))))),
                new DevExpress.XtraCharts.PaletteEntry(System.Drawing.Color.FromArgb(((int)(((byte)(61)))), ((int)(((byte)(113)))), ((int)(((byte)(56))))), System.Drawing.Color.FromArgb(((int)(((byte)(61)))), ((int)(((byte)(113)))), ((int)(((byte)(56)))))),
                new DevExpress.XtraCharts.PaletteEntry(System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(85)))), ((int)(((byte)(85))))), System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(85)))), ((int)(((byte)(85))))))}));
            series3.CrosshairLabelPattern = "{A} : {V:$##,#0}";
            sideBySideBarSeriesLabel1.TextPattern = "{A}";
            series3.Label = sideBySideBarSeriesLabel1;
            series3.Name = "Series";
            series3.ToolTipSeriesPattern = "{V:$##,#0} ";
            sideBySideBarSeriesView1.BarWidth = 0.8D;
            sideBySideBarSeriesView1.ColorEach = true;
            series3.View = sideBySideBarSeriesView1;
            this.costChartControl.SeriesSerializable = new DevExpress.XtraCharts.Series[] {
        series3};
            this.costChartControl.SideBySideBarDistanceVariable = 1D;
            this.costChartControl.Size = new System.Drawing.Size(378, 144);
            this.costChartControl.SmallChartText.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.costChartControl.TabIndex = 22;
            this.salesLayoutControl.AllowCustomization = false;
            this.salesLayoutControl.Appearance.DisabledLayoutGroupCaption.BackColor = System.Drawing.Color.Transparent;
            this.salesLayoutControl.Appearance.DisabledLayoutGroupCaption.Options.UseBackColor = true;
            this.salesLayoutControl.Appearance.DisabledLayoutItem.BackColor = System.Drawing.Color.Transparent;
            this.salesLayoutControl.Appearance.DisabledLayoutItem.Options.UseBackColor = true;
            this.salesLayoutControl.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(246)))), ((int)(((byte)(246)))));
            this.salesLayoutControl.Controls.Add(this.labelControl1);
            this.salesLayoutControl.Controls.Add(this.searchControl);
            this.salesLayoutControl.Controls.Add(this.salesGridControl);
            this.salesLayoutControl.Location = new System.Drawing.Point(21, 21);
            this.salesLayoutControl.Name = "salesLayoutControl";
            this.salesLayoutControl.OptionsCustomizationForm.DesignTimeCustomizationFormPositionAndSize = new System.Drawing.Rectangle(62, 122, 915, 863);
            this.salesLayoutControl.OptionsView.ShareLookAndFeelWithChildren = false;
            this.salesLayoutControl.Root = this.Root;
            this.salesLayoutControl.Size = new System.Drawing.Size(761, 363);
            this.salesLayoutControl.TabIndex = 20;
            this.salesLayoutControl.Text = "layoutControl1";
            this.labelControl1.Appearance.ForeColor = System.Drawing.Color.Black;
            this.labelControl1.Location = new System.Drawing.Point(8, 18);
            this.labelControl1.Name = "labelControl1";
            this.labelControl1.Size = new System.Drawing.Size(41, 20);
            this.labelControl1.TabIndex = 8;
            this.labelControl1.Text = "SALES";
            this.searchControl.Client = this.salesGridControl;
            this.searchControl.EditValue = "";
            this.searchControl.Location = new System.Drawing.Point(451, 9);
            this.searchControl.MaximumSize = new System.Drawing.Size(300, 38);
            this.searchControl.MinimumSize = new System.Drawing.Size(100, 20);
            this.searchControl.Name = "searchControl";
            this.searchControl.Properties.AutoHeight = false;
            this.searchControl.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Repository.SearchButton(40, DevExpress.XtraEditors.ImageLocation.MiddleCenter, ((System.Drawing.Image)(resources.GetObject("searchControl.Properties.Buttons"))), true, true)});
            this.searchControl.Properties.Client = this.salesGridControl;
            this.searchControl.Properties.ShowClearButton = false;
            this.searchControl.Size = new System.Drawing.Size(300, 38);
            this.searchControl.TabIndex = 18;
            this.Root.CustomizationFormText = "Root";
            this.Root.GroupBordersVisible = false;
            this.Root.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.searchControlLCI,
            this.layoutControlItem1,
            this.layoutControlItem2});
            this.Root.Location = new System.Drawing.Point(0, 0);
            this.Root.Name = "Root";
            this.Root.Padding = new DevExpress.XtraLayout.Utils.Padding(10, 0, 0, 0);
            this.Root.Size = new System.Drawing.Size(761, 363);
            this.Root.TextVisible = false;
            this.searchControlLCI.Control = this.searchControl;
            this.searchControlLCI.ControlAlignment = System.Drawing.ContentAlignment.MiddleRight;
            this.searchControlLCI.CustomizationFormText = "searchControlLCI";
            this.searchControlLCI.FillControlToClientArea = false;
            this.searchControlLCI.Location = new System.Drawing.Point(51, 0);
            this.searchControlLCI.MaxSize = new System.Drawing.Size(0, 57);
            this.searchControlLCI.MinSize = new System.Drawing.Size(112, 57);
            this.searchControlLCI.Name = "searchControlLCI";
            this.searchControlLCI.Padding = new DevExpress.XtraLayout.Utils.Padding(2, 10, 2, 2);
            this.searchControlLCI.Size = new System.Drawing.Size(710, 57);
            this.searchControlLCI.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.searchControlLCI.TextSize = new System.Drawing.Size(0, 0);
            this.searchControlLCI.TextVisible = false;
            this.searchControlLCI.TrimClientAreaToControl = false;
            this.layoutControlItem1.Control = this.labelControl1;
            this.layoutControlItem1.ControlAlignment = System.Drawing.ContentAlignment.MiddleLeft;
            this.layoutControlItem1.CustomizationFormText = "layoutControlItem1";
            this.layoutControlItem1.Location = new System.Drawing.Point(0, 0);
            this.layoutControlItem1.Name = "layoutControlItem1";
            this.layoutControlItem1.Padding = new DevExpress.XtraLayout.Utils.Padding(8, 2, 2, 2);
            this.layoutControlItem1.Size = new System.Drawing.Size(51, 57);
            this.layoutControlItem1.TextSize = new System.Drawing.Size(0, 0);
            this.layoutControlItem1.TextVisible = false;
            this.layoutControlItem1.TrimClientAreaToControl = false;
            this.layoutControlItem2.Control = this.salesGridControl;
            this.layoutControlItem2.CustomizationFormText = "layoutControlItem2";
            this.layoutControlItem2.Location = new System.Drawing.Point(0, 57);
            this.layoutControlItem2.Name = "layoutControlItem2";
            this.layoutControlItem2.Padding = new DevExpress.XtraLayout.Utils.Padding(-1, -1, 0, -1);
            this.layoutControlItem2.Size = new System.Drawing.Size(761, 306);
            this.layoutControlItem2.TextSize = new System.Drawing.Size(0, 0);
            this.layoutControlItem2.TextVisible = false;
            this.layoutControlGroup1.AppearanceGroup.BackColor = System.Drawing.Color.White;
            this.layoutControlGroup1.AppearanceGroup.Options.UseBackColor = true;
            this.layoutControlGroup1.CustomizationFormText = "Root";
            this.layoutControlGroup1.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True;
            this.layoutControlGroup1.GroupBordersVisible = false;
            this.layoutControlGroup1.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.opportunitiesGroup,
            this.lgSalesGroup,
            this.emptySpaceItem2});
            this.layoutControlGroup1.Location = new System.Drawing.Point(0, 0);
            this.layoutControlGroup1.Name = "Root";
            this.layoutControlGroup1.Padding = new DevExpress.XtraLayout.Utils.Padding(20, 20, 20, 20);
            this.layoutControlGroup1.Size = new System.Drawing.Size(1166, 617);
            this.layoutControlGroup1.TextVisible = false;
            this.opportunitiesGroup.BestFitWeight = 200;
            this.opportunitiesGroup.CustomizationFormText = "opportunitiesGroup";
            this.opportunitiesGroup.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.opportunitiesLayoutLCI,
            this.opportunitiesChartLCI});
            this.opportunitiesGroup.Location = new System.Drawing.Point(773, 0);
            this.opportunitiesGroup.Name = "opportunitiesGroup";
            this.opportunitiesGroup.Padding = new DevExpress.XtraLayout.Utils.Padding(0, 0, 0, 0);
            this.opportunitiesGroup.Size = new System.Drawing.Size(353, 577);
            this.opportunitiesGroup.Spacing = new DevExpress.XtraLayout.Utils.Padding(0, 0, 0, 0);
            this.opportunitiesGroup.TextVisible = false;
            this.opportunitiesLayoutLCI.Control = this.opportunitiesLayoutControl;
            this.opportunitiesLayoutLCI.CustomizationFormText = "opportunitiesLayoutLCI";
            this.opportunitiesLayoutLCI.Location = new System.Drawing.Point(0, 0);
            this.opportunitiesLayoutLCI.MaxSize = new System.Drawing.Size(0, 56);
            this.opportunitiesLayoutLCI.MinSize = new System.Drawing.Size(94, 56);
            this.opportunitiesLayoutLCI.Name = "opportunitiesLayoutLCI";
            this.opportunitiesLayoutLCI.Padding = new DevExpress.XtraLayout.Utils.Padding(0, 0, 0, 0);
            this.opportunitiesLayoutLCI.Size = new System.Drawing.Size(351, 56);
            this.opportunitiesLayoutLCI.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.opportunitiesLayoutLCI.TextSize = new System.Drawing.Size(0, 0);
            this.opportunitiesLayoutLCI.TextVisible = false;
            this.opportunitiesChartLCI.Control = this.opportunitiesChartControl;
            this.opportunitiesChartLCI.CustomizationFormText = "opportunitiesChartLCI";
            this.opportunitiesChartLCI.Location = new System.Drawing.Point(0, 56);
            this.opportunitiesChartLCI.MaxSize = new System.Drawing.Size(500, 0);
            this.opportunitiesChartLCI.MinSize = new System.Drawing.Size(351, 20);
            this.opportunitiesChartLCI.Name = "opportunitiesChartLCI";
            this.opportunitiesChartLCI.Padding = new DevExpress.XtraLayout.Utils.Padding(0, 0, 0, 0);
            this.opportunitiesChartLCI.Size = new System.Drawing.Size(351, 519);
            this.opportunitiesChartLCI.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.opportunitiesChartLCI.TextSize = new System.Drawing.Size(0, 0);
            this.opportunitiesChartLCI.TextVisible = false;
            this.lgSalesGroup.CustomizationFormText = "lgSalesGroup";
            this.lgSalesGroup.GroupBordersVisible = false;
            this.lgSalesGroup.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.emptySpaceItem3,
            this.revenuesGroup,
            this.costSoldGroup,
            this.salesTodayGroup,
            this.emptySpaceItem1});
            this.lgSalesGroup.Location = new System.Drawing.Point(0, 0);
            this.lgSalesGroup.Name = "lgSalesGroup";
            this.lgSalesGroup.Size = new System.Drawing.Size(763, 577);
            this.emptySpaceItem3.AllowHotTrack = false;
            this.emptySpaceItem3.CustomizationFormText = "emptySpaceItem3";
            this.emptySpaceItem3.Location = new System.Drawing.Point(373, 375);
            this.emptySpaceItem3.MaxSize = new System.Drawing.Size(10, 0);
            this.emptySpaceItem3.MinSize = new System.Drawing.Size(10, 10);
            this.emptySpaceItem3.Name = "emptySpaceItem3";
            this.emptySpaceItem3.Size = new System.Drawing.Size(10, 202);
            this.emptySpaceItem3.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.emptySpaceItem3.TextSize = new System.Drawing.Size(0, 0);
            this.revenuesGroup.CustomizationFormText = "revenuesGroup";
            this.revenuesGroup.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.revenuesLayoutLCI,
            this.revenuesChartLCI});
            this.revenuesGroup.Location = new System.Drawing.Point(0, 375);
            this.revenuesGroup.Name = "revenuesGroup";
            this.revenuesGroup.Padding = new DevExpress.XtraLayout.Utils.Padding(0, 0, 0, 0);
            this.revenuesGroup.Size = new System.Drawing.Size(373, 202);
            this.revenuesGroup.Spacing = new DevExpress.XtraLayout.Utils.Padding(0, 0, 0, 0);
            this.revenuesGroup.TextVisible = false;
            this.revenuesLayoutLCI.Control = this.revenuesLayoutControl;
            this.revenuesLayoutLCI.CustomizationFormText = "revenuesLayoutLCI";
            this.revenuesLayoutLCI.Location = new System.Drawing.Point(0, 0);
            this.revenuesLayoutLCI.MaxSize = new System.Drawing.Size(0, 56);
            this.revenuesLayoutLCI.MinSize = new System.Drawing.Size(280, 56);
            this.revenuesLayoutLCI.Name = "revenuesLayoutLCI";
            this.revenuesLayoutLCI.Padding = new DevExpress.XtraLayout.Utils.Padding(0, 0, 0, 0);
            this.revenuesLayoutLCI.Size = new System.Drawing.Size(371, 56);
            this.revenuesLayoutLCI.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.revenuesLayoutLCI.TextSize = new System.Drawing.Size(0, 0);
            this.revenuesLayoutLCI.TextVisible = false;
            this.revenuesChartLCI.Control = this.revenuesChartControl;
            this.revenuesChartLCI.CustomizationFormText = "revenuesChartLCI";
            this.revenuesChartLCI.Location = new System.Drawing.Point(0, 56);
            this.revenuesChartLCI.MinSize = new System.Drawing.Size(104, 24);
            this.revenuesChartLCI.Name = "revenuesChartLCI";
            this.revenuesChartLCI.Size = new System.Drawing.Size(371, 144);
            this.revenuesChartLCI.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.revenuesChartLCI.TextSize = new System.Drawing.Size(0, 0);
            this.revenuesChartLCI.TextVisible = false;
            this.costSoldGroup.CustomizationFormText = "costSoldGroup";
            this.costSoldGroup.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.costLayoutLCI,
            this.costChartLCI});
            this.costSoldGroup.Location = new System.Drawing.Point(383, 375);
            this.costSoldGroup.Name = "costSoldGroup";
            this.costSoldGroup.Padding = new DevExpress.XtraLayout.Utils.Padding(0, 0, 0, 0);
            this.costSoldGroup.Size = new System.Drawing.Size(380, 202);
            this.costSoldGroup.Spacing = new DevExpress.XtraLayout.Utils.Padding(0, 0, 0, 0);
            this.costSoldGroup.TextVisible = false;
            this.costLayoutLCI.Control = this.costLayoutControl;
            this.costLayoutLCI.CustomizationFormText = "costLayoutLCI";
            this.costLayoutLCI.Location = new System.Drawing.Point(0, 0);
            this.costLayoutLCI.MaxSize = new System.Drawing.Size(0, 56);
            this.costLayoutLCI.MinSize = new System.Drawing.Size(280, 56);
            this.costLayoutLCI.Name = "costLayoutLCI";
            this.costLayoutLCI.Padding = new DevExpress.XtraLayout.Utils.Padding(0, 0, 0, 0);
            this.costLayoutLCI.Size = new System.Drawing.Size(378, 56);
            this.costLayoutLCI.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.costLayoutLCI.TextSize = new System.Drawing.Size(0, 0);
            this.costLayoutLCI.TextVisible = false;
            this.costChartLCI.Control = this.costChartControl;
            this.costChartLCI.CustomizationFormText = "costChartLCI";
            this.costChartLCI.Location = new System.Drawing.Point(0, 56);
            this.costChartLCI.MinSize = new System.Drawing.Size(100, 20);
            this.costChartLCI.Name = "costChartLCI";
            this.costChartLCI.Padding = new DevExpress.XtraLayout.Utils.Padding(0, 0, 0, 0);
            this.costChartLCI.Size = new System.Drawing.Size(378, 144);
            this.costChartLCI.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.costChartLCI.TextSize = new System.Drawing.Size(0, 0);
            this.costChartLCI.TextVisible = false;
            this.salesTodayGroup.CustomizationFormText = "salesTodayGroup";
            this.salesTodayGroup.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.salesTodayLayoutLCI});
            this.salesTodayGroup.Location = new System.Drawing.Point(0, 0);
            this.salesTodayGroup.Name = "salesTodayGroup";
            this.salesTodayGroup.Padding = new DevExpress.XtraLayout.Utils.Padding(0, 0, 0, 0);
            this.salesTodayGroup.Size = new System.Drawing.Size(763, 365);
            this.salesTodayGroup.Spacing = new DevExpress.XtraLayout.Utils.Padding(0, 0, 0, 0);
            this.salesTodayGroup.TextVisible = false;
            this.salesTodayLayoutLCI.Control = this.salesLayoutControl;
            this.salesTodayLayoutLCI.CustomizationFormText = "salesTodayLayoutLCI";
            this.salesTodayLayoutLCI.Location = new System.Drawing.Point(0, 0);
            this.salesTodayLayoutLCI.MinSize = new System.Drawing.Size(24, 325);
            this.salesTodayLayoutLCI.Name = "salesTodayLayoutLCI";
            this.salesTodayLayoutLCI.Padding = new DevExpress.XtraLayout.Utils.Padding(0, 0, 0, 0);
            this.salesTodayLayoutLCI.Size = new System.Drawing.Size(761, 363);
            this.salesTodayLayoutLCI.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.salesTodayLayoutLCI.TextSize = new System.Drawing.Size(0, 0);
            this.salesTodayLayoutLCI.TextVisible = false;
            this.emptySpaceItem1.AllowHotTrack = false;
            this.emptySpaceItem1.CustomizationFormText = "emptySpaceItem1";
            this.emptySpaceItem1.Location = new System.Drawing.Point(0, 365);
            this.emptySpaceItem1.MaxSize = new System.Drawing.Size(0, 10);
            this.emptySpaceItem1.MinSize = new System.Drawing.Size(10, 10);
            this.emptySpaceItem1.Name = "emptySpaceItem1";
            this.emptySpaceItem1.Size = new System.Drawing.Size(763, 10);
            this.emptySpaceItem1.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.emptySpaceItem1.TextSize = new System.Drawing.Size(0, 0);
            this.emptySpaceItem2.AllowHotTrack = false;
            this.emptySpaceItem2.CustomizationFormText = "emptySpaceItem2";
            this.emptySpaceItem2.Location = new System.Drawing.Point(763, 0);
            this.emptySpaceItem2.MaxSize = new System.Drawing.Size(10, 0);
            this.emptySpaceItem2.MinSize = new System.Drawing.Size(10, 10);
            this.emptySpaceItem2.Name = "emptySpaceItem2";
            this.emptySpaceItem2.Size = new System.Drawing.Size(10, 577);
            this.emptySpaceItem2.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.emptySpaceItem2.TextSize = new System.Drawing.Size(0, 0);
            this.Appearance.BackColor = System.Drawing.Color.White;
            this.Appearance.Options.UseBackColor = true;
            this.Controls.Add(this.dataLayoutControl1);
            this.Controls.Add(this.pictureBox1);
            this.Name = "Dashboard";
            this.Size = new System.Drawing.Size(1166, 617);
            ((System.ComponentModel.ISupportInitialize)(this.orderItemsGridView)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.salesGridControl)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.salesBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.salesGridView)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.repositoryItemProgressBar1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.repositoryItemComboBox1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dataLayoutControl1)).EndInit();
            this.dataLayoutControl1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(simpleDiagram1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(funnelSeriesLabel1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(funnelSeriesView1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(series1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(funnelSeriesView2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.opportunitiesChartControl)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.opportunitiesLayoutControl)).EndInit();
            this.opportunitiesLayoutControl.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.opportunitiesLabelLCI)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(simpleDiagram2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(doughnutSeriesLabel1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(doughnutSeriesView1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(series2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(doughnutSeriesView2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.revenuesChartControl)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.costLayoutControl)).EndInit();
            this.costLayoutControl.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.costLabelControlLCI)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.monthCostSimpleButtonLCI)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.yearCostSimpleButtonLCI)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.todayCostSimpleButtonLCI)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.revenuesLayoutControl)).EndInit();
            this.revenuesLayoutControl.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.revenuesLabelLCI)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.todayRevenuesSimpleButtonLCI)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.monthRevenuesSimpleButtonLCI)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.yearRevenuesSimpleButtonLCI)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(xyDiagram1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(sideBySideBarSeriesLabel1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(sideBySideBarSeriesView1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(series3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.costChartControl)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.salesLayoutControl)).EndInit();
            this.salesLayoutControl.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.searchControl.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.Root)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.searchControlLCI)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.opportunitiesGroup)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.opportunitiesLayoutLCI)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.opportunitiesChartLCI)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.lgSalesGroup)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.revenuesGroup)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.revenuesLayoutLCI)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.revenuesChartLCI)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.costSoldGroup)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.costLayoutLCI)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.costChartLCI)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.salesTodayGroup)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.salesTodayLayoutLCI)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem2)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.PictureBox pictureBox1;
        private XtraDataLayout.DataLayoutControl dataLayoutControl1;
        private XtraLayout.LayoutControlGroup layoutControlGroup1;
        private System.Windows.Forms.BindingSource salesBindingSource;
        private XtraGrid.GridControl salesGridControl;
        private XtraGrid.Views.Grid.GridView orderItemsGridView;
        private XtraGrid.Columns.GridColumn ProductGC;
        private XtraGrid.Columns.GridColumn unitsGridColumn;
        private XtraGrid.Columns.GridColumn unitPriceGridColumn;
        private XtraGrid.Columns.GridColumn totalGridColumn;
        private XtraGrid.Columns.GridColumn discountGridColumn;
        private XtraGrid.Views.Grid.GridView salesGridView;
        private XtraGrid.Columns.GridColumn colInvoiceNumber;
        private XtraGrid.Columns.GridColumn colCustomer;
        private XtraGrid.Columns.GridColumn colStore;
        private XtraGrid.Columns.GridColumn colOrderDate;
        private XtraGrid.Columns.GridColumn colTotalAmount;
        private XtraEditors.Repository.RepositoryItemProgressBar repositoryItemProgressBar1;
        private XtraEditors.Repository.RepositoryItemImageComboBox repositoryItemComboBox1;
        public XtraEditors.SearchControl searchControl;
        private XtraLayout.LayoutControl salesLayoutControl;
        private XtraLayout.LayoutControlGroup Root;
        private XtraLayout.LayoutControlItem searchControlLCI;
        private XtraLayout.LayoutControl costLayoutControl;
        private XtraEditors.CheckButton yearCostSimpleButton;
        private XtraEditors.CheckButton monthCostSimpleButton;
        private XtraEditors.LabelControl costLabelControl;
        private XtraLayout.LayoutControlGroup layoutControlGroup3;
        private XtraLayout.LayoutControlItem costLabelControlLCI;
        private XtraLayout.LayoutControlItem monthCostSimpleButtonLCI;
        private XtraLayout.LayoutControlItem yearCostSimpleButtonLCI;
        private XtraLayout.LayoutControl revenuesLayoutControl;
        private XtraEditors.CheckButton yearRevenuesSimpleButton;
        private XtraEditors.CheckButton monthRevenuesSimpleButton;
        private XtraEditors.CheckButton todayRevenuesSimpleButton;
        private XtraEditors.LabelControl revenuesLabelControl;
        private XtraLayout.LayoutControlGroup layoutControlGroup2;
        private XtraLayout.LayoutControlItem revenuesLabelLCI;
        private XtraLayout.LayoutControlItem todayRevenuesSimpleButtonLCI;
        private XtraLayout.LayoutControlItem monthRevenuesSimpleButtonLCI;
        private XtraLayout.LayoutControlItem yearRevenuesSimpleButtonLCI;
        private XtraCharts.ChartControl costChartControl;
        private XtraLayout.LayoutControlItem costChartLCI;
        private XtraLayout.LayoutControlItem revenuesLayoutLCI;
        private XtraLayout.LayoutControlItem costLayoutLCI;
        private XtraEditors.CheckButton todayCostSimpleButton;
        private XtraLayout.LayoutControlItem todayCostSimpleButtonLCI;
        private XtraLayout.LayoutControlGroup salesTodayGroup;
        private XtraLayout.EmptySpaceItem emptySpaceItem1;
        private XtraLayout.EmptySpaceItem emptySpaceItem2;
        private XtraLayout.EmptySpaceItem emptySpaceItem3;
        private XtraLayout.LayoutControlGroup revenuesGroup;
        private XtraLayout.LayoutControlGroup costSoldGroup;
        private XtraLayout.LayoutControlItem salesTodayLayoutLCI;
        private XtraCharts.ChartControl revenuesChartControl;
        private XtraLayout.LayoutControlItem revenuesChartLCI;
        private XtraLayout.LayoutControl opportunitiesLayoutControl;
        private XtraEditors.LabelControl opportunitiesLabelControl;
        private XtraLayout.LayoutControlGroup layoutControlGroup4;
        private XtraLayout.LayoutControlItem opportunitiesLabelLCI;
        private XtraLayout.LayoutControlGroup opportunitiesGroup;
        private XtraLayout.LayoutControlItem opportunitiesLayoutLCI;
        private XtraCharts.ChartControl opportunitiesChartControl;
        private XtraLayout.LayoutControlItem opportunitiesChartLCI;
        private XtraEditors.LabelControl labelControl1;
        private XtraLayout.LayoutControlItem layoutControlItem1;
        private XtraLayout.LayoutControlItem layoutControlItem2;
        private XtraLayout.LayoutControlGroup lgSalesGroup;

    }
}
