using DevExpress.DevAV.ViewModels;
namespace DevExpress.DevAV.Modules {
    partial class Employees {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing) {
            if(disposing && (components != null)) {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent() {
            this.components = new System.ComponentModel.Container();
            DevExpress.XtraEditors.TileItemElement tileItemElement1 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement2 = new DevExpress.XtraEditors.TileItemElement();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Employees));
            DevExpress.XtraEditors.TileItemElement tileItemElement3 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement4 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement5 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement6 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement7 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement8 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement9 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement10 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement11 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement12 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraGrid.Views.Tile.TileViewItemElement tileViewItemElement1 = new DevExpress.XtraGrid.Views.Tile.TileViewItemElement();
            DevExpress.XtraGrid.Views.Tile.TileViewItemElement tileViewItemElement2 = new DevExpress.XtraGrid.Views.Tile.TileViewItemElement();
            DevExpress.XtraGrid.Views.Tile.TileViewItemElement tileViewItemElement3 = new DevExpress.XtraGrid.Views.Tile.TileViewItemElement();
            DevExpress.XtraGrid.Views.Tile.TileViewItemElement tileViewItemElement4 = new DevExpress.XtraGrid.Views.Tile.TileViewItemElement();
            DevExpress.XtraGrid.Views.Tile.TileViewItemElement tileViewItemElement5 = new DevExpress.XtraGrid.Views.Tile.TileViewItemElement();
            DevExpress.XtraGrid.Views.Tile.TileViewItemElement tileViewItemElement6 = new DevExpress.XtraGrid.Views.Tile.TileViewItemElement();
            DevExpress.XtraGrid.Views.Tile.TileViewItemElement tileViewItemElement7 = new DevExpress.XtraGrid.Views.Tile.TileViewItemElement();
            DevExpress.XtraGrid.Views.Tile.TileViewItemElement tileViewItemElement8 = new DevExpress.XtraGrid.Views.Tile.TileViewItemElement();
            DevExpress.XtraGrid.Views.Tile.TileViewItemElement tileViewItemElement9 = new DevExpress.XtraGrid.Views.Tile.TileViewItemElement();
            this.colPhoto = new DevExpress.XtraGrid.Columns.TileViewColumn();
            this.colFullName = new DevExpress.XtraGrid.Columns.TileViewColumn();
            this.colAddress = new DevExpress.XtraGrid.Columns.TileViewColumn();
            this.colHomePhone = new DevExpress.XtraGrid.Columns.TileViewColumn();
            this.colEmail = new DevExpress.XtraGrid.Columns.TileViewColumn();
            this.colMobilePhone = new DevExpress.XtraGrid.Columns.TileViewColumn();
            this.employeeBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.filterTileControl = new DevExpress.XtraEditors.TileControl();
            this.tileGroup2 = new DevExpress.XtraEditors.TileGroup();
            this.tileItemAll = new DevExpress.XtraEditors.TileItem();
            this.tileItemSalaried = new DevExpress.XtraEditors.TileItem();
            this.tileItemCommission = new DevExpress.XtraEditors.TileItem();
            this.tileItemContract = new DevExpress.XtraEditors.TileItem();
            this.tileItemTerminated = new DevExpress.XtraEditors.TileItem();
            this.tileItemOnLeave = new DevExpress.XtraEditors.TileItem();
            this.layoutControl1 = new DevExpress.XtraLayout.LayoutControl();
            this.gridControl1 = new DevExpress.XtraGrid.GridControl();
            this.tileView1 = new DevExpress.XtraGrid.Views.Tile.TileView();
            this.colDepartment = new DevExpress.XtraGrid.Columns.TileViewColumn();
            this.colTitle = new DevExpress.XtraGrid.Columns.TileViewColumn();
            this.colStatus = new DevExpress.XtraGrid.Columns.TileViewColumn();
            this.colHireDate = new DevExpress.XtraGrid.Columns.TileViewColumn();
            this.colPersonalProfile = new DevExpress.XtraGrid.Columns.TileViewColumn();
            this.colProbationReason = new DevExpress.XtraGrid.Columns.TileViewColumn();
            this.colFirstName = new DevExpress.XtraGrid.Columns.TileViewColumn();
            this.colLastName = new DevExpress.XtraGrid.Columns.TileViewColumn();
            this.colPrefix = new DevExpress.XtraGrid.Columns.TileViewColumn();
            this.colSkype = new DevExpress.XtraGrid.Columns.TileViewColumn();
            this.colBirthDate = new DevExpress.XtraGrid.Columns.TileViewColumn();
            this.colPicture = new DevExpress.XtraGrid.Columns.TileViewColumn();
            this.colPictureId = new DevExpress.XtraGrid.Columns.TileViewColumn();
            this.colFullNameBindable = new DevExpress.XtraGrid.Columns.TileViewColumn();
            this.colId = new DevExpress.XtraGrid.Columns.TileViewColumn();
            this.flyoutPanel1 = new DevExpress.Utils.FlyoutPanel();
            this.layoutControlGroup1 = new DevExpress.XtraLayout.LayoutControlGroup();
            this.tileControlLayoutItem = new DevExpress.XtraLayout.LayoutControlItem();
            this.buttonHide = new DevExpress.XtraLayout.SimpleLabelItem();
            this.simpleLabelItem2 = new DevExpress.XtraLayout.SimpleLabelItem();
            this.layoutControlItem1 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControl2 = new DevExpress.XtraLayout.LayoutControl();
            this.printEmployeeListButton = new DevExpress.XtraEditors.PictureEdit();
            this.printEmployeeDirectoryButton = new DevExpress.XtraEditors.PictureEdit();
            this.printEmployeeProfile = new DevExpress.XtraEditors.PictureEdit();
            this.layoutControlGroup2 = new DevExpress.XtraLayout.LayoutControlGroup();
            this.printEmployeeProfileItem = new DevExpress.XtraLayout.LayoutControlItem();
            this.printEmployeeDirectoryItem = new DevExpress.XtraLayout.LayoutControlItem();
            this.printEmployeeListItem = new DevExpress.XtraLayout.LayoutControlItem();
            this.emptySpaceItem1 = new DevExpress.XtraLayout.EmptySpaceItem();
            ((System.ComponentModel.ISupportInitialize)(this.employeeBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControl1)).BeginInit();
            this.layoutControl1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.gridControl1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.tileView1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.flyoutPanel1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.tileControlLayoutItem)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.buttonHide)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.simpleLabelItem2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControl2)).BeginInit();
            this.layoutControl2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.printEmployeeListButton.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.printEmployeeDirectoryButton.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.printEmployeeProfile.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.printEmployeeProfileItem)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.printEmployeeDirectoryItem)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.printEmployeeListItem)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem1)).BeginInit();
            this.SuspendLayout();
            this.colPhoto.FieldName = "Photo";
            this.colPhoto.Name = "colPhoto";
            this.colPhoto.Visible = true;
            this.colPhoto.VisibleIndex = 18;
            this.colFullName.FieldName = "FullName";
            this.colFullName.Name = "colFullName";
            this.colFullName.Visible = true;
            this.colFullName.VisibleIndex = 8;
            this.colAddress.FieldName = "Address";
            this.colAddress.Name = "colAddress";
            this.colAddress.Visible = true;
            this.colAddress.VisibleIndex = 17;
            this.colHomePhone.FieldName = "HomePhone";
            this.colHomePhone.Name = "colHomePhone";
            this.colHomePhone.Visible = true;
            this.colHomePhone.VisibleIndex = 10;
            this.colEmail.FieldName = "Email";
            this.colEmail.Name = "colEmail";
            this.colEmail.Visible = true;
            this.colEmail.VisibleIndex = 12;
            this.colMobilePhone.FieldName = "MobilePhone";
            this.colMobilePhone.Name = "colMobilePhone";
            this.colMobilePhone.Visible = true;
            this.colMobilePhone.VisibleIndex = 11;
            this.employeeBindingSource.DataSource = typeof(DevExpress.DevAV.Employee);
            this.filterTileControl.AllowDrag = false;
            this.filterTileControl.AllowGlyphSkinning = true;
            this.filterTileControl.AllowSelectedItem = true;
            this.filterTileControl.AppearanceItem.Hovered.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(78)))), ((int)(((byte)(114)))), ((int)(((byte)(191)))));
            this.filterTileControl.AppearanceItem.Hovered.Options.UseBackColor = true;
            this.filterTileControl.AppearanceItem.Normal.BackColor = System.Drawing.Color.White;
            this.filterTileControl.AppearanceItem.Normal.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(195)))), ((int)(((byte)(195)))), ((int)(((byte)(195)))));
            this.filterTileControl.AppearanceItem.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(89)))), ((int)(((byte)(89)))), ((int)(((byte)(89)))));
            this.filterTileControl.AppearanceItem.Normal.Options.UseBackColor = true;
            this.filterTileControl.AppearanceItem.Normal.Options.UseBorderColor = true;
            this.filterTileControl.AppearanceItem.Normal.Options.UseForeColor = true;
            this.filterTileControl.AppearanceItem.Pressed.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(69)))), ((int)(((byte)(148)))));
            this.filterTileControl.AppearanceItem.Pressed.Options.UseBackColor = true;
            this.filterTileControl.AppearanceItem.Selected.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(81)))), ((int)(((byte)(165)))));
            this.filterTileControl.AppearanceItem.Selected.BorderColor = System.Drawing.Color.Transparent;
            this.filterTileControl.AppearanceItem.Selected.ForeColor = System.Drawing.Color.White;
            this.filterTileControl.AppearanceItem.Selected.Options.UseBackColor = true;
            this.filterTileControl.AppearanceItem.Selected.Options.UseBorderColor = true;
            this.filterTileControl.AppearanceItem.Selected.Options.UseForeColor = true;
            this.filterTileControl.DragSize = new System.Drawing.Size(0, 0);
            this.filterTileControl.Groups.Add(this.tileGroup2);
            this.filterTileControl.IndentBetweenItems = 5;
            this.filterTileControl.ItemPadding = new System.Windows.Forms.Padding(7, 7, 7, 4);
            this.filterTileControl.ItemSize = 80;
            this.filterTileControl.Location = new System.Drawing.Point(44, 47);
            this.filterTileControl.Margin = new System.Windows.Forms.Padding(0);
            this.filterTileControl.MaxId = 7;
            this.filterTileControl.Name = "filterTileControl";
            this.filterTileControl.Orientation = System.Windows.Forms.Orientation.Vertical;
            this.filterTileControl.Padding = new System.Windows.Forms.Padding(0, 6, 0, 0);
            this.filterTileControl.SelectedItem = this.tileItemAll;
            this.filterTileControl.Size = new System.Drawing.Size(236, 519);
            this.filterTileControl.TabIndex = 0;
            this.filterTileControl.Text = "tileControl1";
            this.filterTileControl.ItemClick += new DevExpress.XtraEditors.TileItemClickEventHandler(this.filterTileControl_ItemClick);
            this.tileGroup2.Items.Add(this.tileItemAll);
            this.tileGroup2.Items.Add(this.tileItemSalaried);
            this.tileGroup2.Items.Add(this.tileItemCommission);
            this.tileGroup2.Items.Add(this.tileItemContract);
            this.tileGroup2.Items.Add(this.tileItemTerminated);
            this.tileGroup2.Items.Add(this.tileItemOnLeave);
            this.tileGroup2.Name = "tileGroup2";
            this.tileGroup2.Text = null;
            tileItemElement1.Appearance.Normal.FontSizeDelta = 128;
            tileItemElement1.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(171)))), ((int)(((byte)(171)))), ((int)(((byte)(171)))));
            tileItemElement1.Appearance.Normal.Options.UseFont = true;
            tileItemElement1.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement1.Appearance.Selected.FontSizeDelta = 128;
            tileItemElement1.Appearance.Selected.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(168)))), ((int)(((byte)(209)))));
            tileItemElement1.Appearance.Selected.Options.UseFont = true;
            tileItemElement1.Appearance.Selected.Options.UseForeColor = true;
            tileItemElement1.ImageBorderColor = System.Drawing.Color.Empty;
            tileItemElement1.Text = "5";
            tileItemElement1.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopRight;
            tileItemElement1.TextLocation = new System.Drawing.Point(-2, -12);
            tileItemElement2.Image = ((System.Drawing.Image)(resources.GetObject("tileItemElement2.Image")));
            tileItemElement2.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopLeft;
            tileItemElement2.ImageBorderColor = System.Drawing.Color.Empty;
            tileItemElement2.Text = "All";
            tileItemElement2.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomLeft;
            this.tileItemAll.Elements.Add(tileItemElement1);
            this.tileItemAll.Elements.Add(tileItemElement2);
            this.tileItemAll.Id = 0;
            this.tileItemAll.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItemAll.Name = "tileItemAll";
            tileItemElement3.Appearance.Normal.FontSizeDelta = 128;
            tileItemElement3.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(171)))), ((int)(((byte)(171)))), ((int)(((byte)(171)))));
            tileItemElement3.Appearance.Normal.Options.UseFont = true;
            tileItemElement3.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement3.Appearance.Selected.FontSizeDelta = 128;
            tileItemElement3.Appearance.Selected.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(168)))), ((int)(((byte)(209)))));
            tileItemElement3.Appearance.Selected.Options.UseFont = true;
            tileItemElement3.Appearance.Selected.Options.UseForeColor = true;
            tileItemElement3.ImageBorderColor = System.Drawing.Color.Empty;
            tileItemElement3.Text = "5";
            tileItemElement3.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopRight;
            tileItemElement3.TextLocation = new System.Drawing.Point(-2, -12);
            tileItemElement4.Image = ((System.Drawing.Image)(resources.GetObject("tileItemElement4.Image")));
            tileItemElement4.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopLeft;
            tileItemElement4.ImageBorderColor = System.Drawing.Color.Empty;
            tileItemElement4.Text = "Salaried";
            tileItemElement4.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomLeft;
            this.tileItemSalaried.Elements.Add(tileItemElement3);
            this.tileItemSalaried.Elements.Add(tileItemElement4);
            this.tileItemSalaried.Id = 1;
            this.tileItemSalaried.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItemSalaried.Name = "tileItemSalaried";
            this.tileItemSalaried.Tag = "Salaried";
            tileItemElement5.Appearance.Normal.FontSizeDelta = 128;
            tileItemElement5.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(171)))), ((int)(((byte)(171)))), ((int)(((byte)(171)))));
            tileItemElement5.Appearance.Normal.Options.UseFont = true;
            tileItemElement5.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement5.Appearance.Selected.FontSizeDelta = 128;
            tileItemElement5.Appearance.Selected.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(168)))), ((int)(((byte)(209)))));
            tileItemElement5.Appearance.Selected.Options.UseFont = true;
            tileItemElement5.Appearance.Selected.Options.UseForeColor = true;
            tileItemElement5.ImageBorderColor = System.Drawing.Color.Empty;
            tileItemElement5.Text = "5";
            tileItemElement5.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopRight;
            tileItemElement5.TextLocation = new System.Drawing.Point(-2, -12);
            tileItemElement6.Image = ((System.Drawing.Image)(resources.GetObject("tileItemElement6.Image")));
            tileItemElement6.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopLeft;
            tileItemElement6.ImageBorderColor = System.Drawing.Color.Empty;
            tileItemElement6.Text = "Commission";
            tileItemElement6.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomLeft;
            this.tileItemCommission.Elements.Add(tileItemElement5);
            this.tileItemCommission.Elements.Add(tileItemElement6);
            this.tileItemCommission.Id = 2;
            this.tileItemCommission.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItemCommission.Name = "tileItemCommission";
            this.tileItemCommission.Tag = "Commission";
            tileItemElement7.Appearance.Normal.FontSizeDelta = 128;
            tileItemElement7.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(171)))), ((int)(((byte)(171)))), ((int)(((byte)(171)))));
            tileItemElement7.Appearance.Normal.Options.UseFont = true;
            tileItemElement7.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement7.Appearance.Selected.FontSizeDelta = 128;
            tileItemElement7.Appearance.Selected.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(168)))), ((int)(((byte)(209)))));
            tileItemElement7.Appearance.Selected.Options.UseFont = true;
            tileItemElement7.Appearance.Selected.Options.UseForeColor = true;
            tileItemElement7.ImageBorderColor = System.Drawing.Color.Empty;
            tileItemElement7.Text = "5";
            tileItemElement7.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopRight;
            tileItemElement7.TextLocation = new System.Drawing.Point(-2, -12);
            tileItemElement8.Image = ((System.Drawing.Image)(resources.GetObject("tileItemElement8.Image")));
            tileItemElement8.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopLeft;
            tileItemElement8.ImageBorderColor = System.Drawing.Color.Empty;
            tileItemElement8.Text = "Contract";
            tileItemElement8.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomLeft;
            this.tileItemContract.Elements.Add(tileItemElement7);
            this.tileItemContract.Elements.Add(tileItemElement8);
            this.tileItemContract.Id = 3;
            this.tileItemContract.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItemContract.Name = "tileItemContract";
            this.tileItemContract.Tag = "Contract";
            tileItemElement9.Appearance.Normal.FontSizeDelta = 128;
            tileItemElement9.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(171)))), ((int)(((byte)(171)))), ((int)(((byte)(171)))));
            tileItemElement9.Appearance.Normal.Options.UseFont = true;
            tileItemElement9.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement9.Appearance.Selected.FontSizeDelta = 128;
            tileItemElement9.Appearance.Selected.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(168)))), ((int)(((byte)(209)))));
            tileItemElement9.Appearance.Selected.Options.UseFont = true;
            tileItemElement9.Appearance.Selected.Options.UseForeColor = true;
            tileItemElement9.ImageBorderColor = System.Drawing.Color.Empty;
            tileItemElement9.Text = "5";
            tileItemElement9.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopRight;
            tileItemElement9.TextLocation = new System.Drawing.Point(-2, -12);
            tileItemElement10.Image = ((System.Drawing.Image)(resources.GetObject("tileItemElement10.Image")));
            tileItemElement10.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopLeft;
            tileItemElement10.ImageBorderColor = System.Drawing.Color.Empty;
            tileItemElement10.Text = "Terminated";
            tileItemElement10.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomLeft;
            this.tileItemTerminated.Elements.Add(tileItemElement9);
            this.tileItemTerminated.Elements.Add(tileItemElement10);
            this.tileItemTerminated.Id = 4;
            this.tileItemTerminated.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItemTerminated.Name = "tileItemTerminated";
            this.tileItemTerminated.Tag = "Terminated";
            tileItemElement11.Appearance.Normal.FontSizeDelta = 128;
            tileItemElement11.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(171)))), ((int)(((byte)(171)))), ((int)(((byte)(171)))));
            tileItemElement11.Appearance.Normal.Options.UseFont = true;
            tileItemElement11.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement11.Appearance.Selected.FontSizeDelta = 128;
            tileItemElement11.Appearance.Selected.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(168)))), ((int)(((byte)(209)))));
            tileItemElement11.Appearance.Selected.Options.UseFont = true;
            tileItemElement11.Appearance.Selected.Options.UseForeColor = true;
            tileItemElement11.ImageBorderColor = System.Drawing.Color.Empty;
            tileItemElement11.Text = "5";
            tileItemElement11.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopRight;
            tileItemElement11.TextLocation = new System.Drawing.Point(-2, -12);
            tileItemElement12.Image = ((System.Drawing.Image)(resources.GetObject("tileItemElement12.Image")));
            tileItemElement12.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopLeft;
            tileItemElement12.ImageBorderColor = System.Drawing.Color.Empty;
            tileItemElement12.Text = "On Leave";
            tileItemElement12.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomLeft;
            this.tileItemOnLeave.Elements.Add(tileItemElement11);
            this.tileItemOnLeave.Elements.Add(tileItemElement12);
            this.tileItemOnLeave.Id = 5;
            this.tileItemOnLeave.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItemOnLeave.Name = "tileItemOnLeave";
            this.tileItemOnLeave.Tag = "OnLeave";
            this.layoutControl1.AllowCustomization = false;
            this.layoutControl1.Controls.Add(this.gridControl1);
            this.layoutControl1.Controls.Add(this.flyoutPanel1);
            this.layoutControl1.Controls.Add(this.filterTileControl);
            this.layoutControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.layoutControl1.Location = new System.Drawing.Point(0, 0);
            this.layoutControl1.Margin = new System.Windows.Forms.Padding(5, 8, 5, 8);
            this.layoutControl1.Name = "layoutControl1";
            this.layoutControl1.OptionsCustomizationForm.DesignTimeCustomizationFormPositionAndSize = new System.Drawing.Rectangle(-981, 125, 771, 817);
            this.layoutControl1.Root = this.layoutControlGroup1;
            this.layoutControl1.Size = new System.Drawing.Size(948, 568);
            this.layoutControl1.TabIndex = 2;
            this.layoutControl1.Text = "layoutControl1";
            this.gridControl1.DataSource = this.employeeBindingSource;
            this.gridControl1.Location = new System.Drawing.Point(308, 35);
            this.gridControl1.MainView = this.tileView1;
            this.gridControl1.Name = "gridControl1";
            this.gridControl1.Size = new System.Drawing.Size(600, 533);
            this.gridControl1.TabIndex = 5;
            this.gridControl1.ViewCollection.AddRange(new DevExpress.XtraGrid.Views.Base.BaseView[] {
            this.tileView1});
            this.gridControl1.Load += new System.EventHandler(this.gridControl1_Load);
            this.tileView1.Columns.AddRange(new DevExpress.XtraGrid.Columns.GridColumn[] {
            this.colDepartment,
            this.colTitle,
            this.colStatus,
            this.colHireDate,
            this.colPersonalProfile,
            this.colProbationReason,
            this.colFirstName,
            this.colLastName,
            this.colFullName,
            this.colPrefix,
            this.colHomePhone,
            this.colMobilePhone,
            this.colEmail,
            this.colSkype,
            this.colBirthDate,
            this.colPicture,
            this.colPictureId,
            this.colAddress,
            this.colPhoto,
            this.colFullNameBindable,
            this.colId});
            this.tileView1.FocusBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(168)))), ((int)(((byte)(210)))));
            this.tileView1.GridControl = this.gridControl1;
            this.tileView1.Name = "tileView1";
            this.tileView1.OptionsTiles.AllowPressAnimation = false;
            this.tileView1.OptionsTiles.HorizontalContentAlignment = DevExpress.Utils.HorzAlignment.Near;
            this.tileView1.OptionsTiles.IndentBetweenItems = 20;
            this.tileView1.OptionsTiles.ItemPadding = new System.Windows.Forms.Padding(12, 10, 12, 10);
            this.tileView1.OptionsTiles.ItemSize = new System.Drawing.Size(335, 210);
            this.tileView1.OptionsTiles.Padding = new System.Windows.Forms.Padding(18);
            this.tileView1.OptionsTiles.RowCount = 8;
            this.tileView1.OptionsTiles.ShowGroupText = false;
            this.tileView1.OptionsTiles.VerticalContentAlignment = DevExpress.Utils.VertAlignment.Top;
            tileViewItemElement1.Appearance.Normal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(246)))), ((int)(((byte)(246)))));
            tileViewItemElement1.Appearance.Normal.Options.UseBackColor = true;
            tileViewItemElement1.Column = null;
            tileViewItemElement1.Height = 31;
            tileViewItemElement1.ImageBorderColor = System.Drawing.Color.Empty;
            tileViewItemElement1.StretchHorizontal = true;
            tileViewItemElement1.Text = "";
            tileViewItemElement1.TextLocation = new System.Drawing.Point(0, -9);
            tileViewItemElement2.Column = this.colPhoto;
            tileViewItemElement2.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomLeft;
            tileViewItemElement2.ImageBorder = DevExpress.XtraEditors.TileItemElementImageBorderMode.SingleBorder;
            tileViewItemElement2.ImageBorderColor = System.Drawing.Color.Empty;
            tileViewItemElement2.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomOutside;
            tileViewItemElement2.ImageSize = new System.Drawing.Size(122, 153);
            tileViewItemElement2.Text = "colPhoto";
            tileViewItemElement3.Column = this.colFullName;
            tileViewItemElement3.ImageBorderColor = System.Drawing.Color.Empty;
            tileViewItemElement3.Text = "colFullName";
            tileViewItemElement3.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopLeft;
            tileViewItemElement3.TextLocation = new System.Drawing.Point(0, -3);
            tileViewItemElement4.AnchorAlignment = DevExpress.Utils.AnchorAlignment.Right;
            tileViewItemElement4.AnchorElementIndex = 1;
            tileViewItemElement4.AnchorIndent = 10;
            tileViewItemElement4.Appearance.Normal.ForeColor = System.Drawing.Color.Gray;
            tileViewItemElement4.Appearance.Normal.Options.UseForeColor = true;
            tileViewItemElement4.Column = null;
            tileViewItemElement4.ImageBorderColor = System.Drawing.Color.Empty;
            tileViewItemElement4.Text = "ADDRESS";
            tileViewItemElement5.AnchorElementIndex = 3;
            tileViewItemElement5.AnchorIndent = 0;
            tileViewItemElement5.Column = this.colAddress;
            tileViewItemElement5.ImageBorderColor = System.Drawing.Color.Empty;
            tileViewItemElement5.Height = 40;
            tileViewItemElement5.MaxWidth = 160;
            tileViewItemElement5.Text = "colAddress";
            tileViewItemElement6.AnchorElementIndex = 4;
            tileViewItemElement6.AnchorIndent = 10;
            tileViewItemElement6.Appearance.Normal.ForeColor = System.Drawing.Color.Gray;
            tileViewItemElement6.Appearance.Normal.Options.UseForeColor = true;
            tileViewItemElement6.Column = null;
            tileViewItemElement6.ImageBorderColor = System.Drawing.Color.Empty;
            tileViewItemElement6.Text = "PHONE";
            tileViewItemElement7.AnchorElementIndex = 5;
            tileViewItemElement7.AnchorIndent = 0;
            tileViewItemElement7.Column = this.colHomePhone;
            tileViewItemElement7.ImageBorderColor = System.Drawing.Color.Empty;
            tileViewItemElement7.Text = "colHomePhone";
            tileViewItemElement8.AnchorElementIndex = 6;
            tileViewItemElement8.Appearance.Normal.ForeColor = System.Drawing.Color.Gray;
            tileViewItemElement8.Appearance.Normal.Options.UseForeColor = true;
            tileViewItemElement8.Column = null;
            tileViewItemElement8.ImageBorderColor = System.Drawing.Color.Empty;
            tileViewItemElement8.Text = "EMAIL";
            tileViewItemElement9.AnchorElementIndex = 7;
            tileViewItemElement9.AnchorIndent = 0;
            tileViewItemElement9.Column = this.colEmail;
            tileViewItemElement9.ImageBorderColor = System.Drawing.Color.Empty;
            tileViewItemElement9.Text = "colEmail";
            this.tileView1.TileTemplate.Add(tileViewItemElement1);
            this.tileView1.TileTemplate.Add(tileViewItemElement2);
            this.tileView1.TileTemplate.Add(tileViewItemElement3);
            this.tileView1.TileTemplate.Add(tileViewItemElement4);
            this.tileView1.TileTemplate.Add(tileViewItemElement5);
            this.tileView1.TileTemplate.Add(tileViewItemElement6);
            this.tileView1.TileTemplate.Add(tileViewItemElement7);
            this.tileView1.TileTemplate.Add(tileViewItemElement8);
            this.tileView1.TileTemplate.Add(tileViewItemElement9);
            this.colDepartment.FieldName = "Department";
            this.colDepartment.Name = "colDepartment";
            this.colDepartment.Visible = true;
            this.colDepartment.VisibleIndex = 0;
            this.colTitle.FieldName = "Title";
            this.colTitle.Name = "colTitle";
            this.colTitle.Visible = true;
            this.colTitle.VisibleIndex = 1;
            this.colStatus.FieldName = "Status";
            this.colStatus.Name = "colStatus";
            this.colStatus.Visible = true;
            this.colStatus.VisibleIndex = 2;
            this.colHireDate.FieldName = "HireDate";
            this.colHireDate.Name = "colHireDate";
            this.colHireDate.Visible = true;
            this.colHireDate.VisibleIndex = 3;
            this.colPersonalProfile.FieldName = "PersonalProfile";
            this.colPersonalProfile.Name = "colPersonalProfile";
            this.colPersonalProfile.Visible = true;
            this.colPersonalProfile.VisibleIndex = 4;
            this.colProbationReason.FieldName = "ProbationReason";
            this.colProbationReason.Name = "colProbationReason";
            this.colProbationReason.Visible = true;
            this.colProbationReason.VisibleIndex = 5;
            this.colFirstName.FieldName = "FirstName";
            this.colFirstName.Name = "colFirstName";
            this.colFirstName.Visible = true;
            this.colFirstName.VisibleIndex = 6;
            this.colLastName.FieldName = "LastName";
            this.colLastName.Name = "colLastName";
            this.colLastName.Visible = true;
            this.colLastName.VisibleIndex = 7;
            this.colPrefix.FieldName = "Prefix";
            this.colPrefix.Name = "colPrefix";
            this.colPrefix.Visible = true;
            this.colPrefix.VisibleIndex = 9;
            this.colSkype.FieldName = "Skype";
            this.colSkype.Name = "colSkype";
            this.colSkype.Visible = true;
            this.colSkype.VisibleIndex = 13;
            this.colBirthDate.FieldName = "BirthDate";
            this.colBirthDate.Name = "colBirthDate";
            this.colBirthDate.Visible = true;
            this.colBirthDate.VisibleIndex = 14;
            this.colPicture.FieldName = "Picture";
            this.colPicture.Name = "colPicture";
            this.colPicture.Visible = true;
            this.colPicture.VisibleIndex = 15;
            this.colPictureId.FieldName = "PictureId";
            this.colPictureId.Name = "colPictureId";
            this.colPictureId.Visible = true;
            this.colPictureId.VisibleIndex = 16;
            this.colFullNameBindable.FieldName = "FullNameBindable";
            this.colFullNameBindable.Name = "colFullNameBindable";
            this.colFullNameBindable.Visible = true;
            this.colFullNameBindable.VisibleIndex = 19;
            this.colId.FieldName = "Id";
            this.colId.Name = "colId";
            this.colId.Visible = true;
            this.colId.VisibleIndex = 20;
            this.flyoutPanel1.Location = new System.Drawing.Point(1184, 95);
            this.flyoutPanel1.Margin = new System.Windows.Forms.Padding(5, 8, 5, 8);
            this.flyoutPanel1.Name = "flyoutPanel1";
            this.flyoutPanel1.Size = new System.Drawing.Size(241, 298);
            this.flyoutPanel1.TabIndex = 4;
            this.layoutControlGroup1.CustomizationFormText = "Root";
            this.layoutControlGroup1.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True;
            this.layoutControlGroup1.GroupBordersVisible = false;
            this.layoutControlGroup1.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.tileControlLayoutItem,
            this.buttonHide,
            this.simpleLabelItem2,
            this.layoutControlItem1});
            this.layoutControlGroup1.Location = new System.Drawing.Point(0, 0);
            this.layoutControlGroup1.Name = "Root";
            this.layoutControlGroup1.Padding = new DevExpress.XtraLayout.Utils.Padding(40, 40, 0, 0);
            this.layoutControlGroup1.Size = new System.Drawing.Size(948, 568);
            this.layoutControlGroup1.TextVisible = false;
            this.tileControlLayoutItem.Control = this.filterTileControl;
            this.tileControlLayoutItem.CustomizationFormText = "tileControlLayoutItem";
            this.tileControlLayoutItem.Location = new System.Drawing.Point(0, 45);
            this.tileControlLayoutItem.MaxSize = new System.Drawing.Size(240, 0);
            this.tileControlLayoutItem.MinSize = new System.Drawing.Size(240, 24);
            this.tileControlLayoutItem.Name = "tileControlLayoutItem";
            this.tileControlLayoutItem.OptionsPrint.AllowPrint = false;
            this.tileControlLayoutItem.Padding = new DevExpress.XtraLayout.Utils.Padding(4, 0, 2, 2);
            this.tileControlLayoutItem.Size = new System.Drawing.Size(240, 523);
            this.tileControlLayoutItem.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.tileControlLayoutItem.TextSize = new System.Drawing.Size(0, 0);
            this.tileControlLayoutItem.TextVisible = false;
            this.buttonHide.AllowHotTrack = false;
            this.buttonHide.AppearanceItemCaption.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.BackwardDiagonal;
            this.buttonHide.CustomizationFormText = " ";
            this.buttonHide.Image = ((System.Drawing.Image)(resources.GetObject("buttonHide.Image")));
            this.buttonHide.ImageAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.buttonHide.Location = new System.Drawing.Point(240, 45);
            this.buttonHide.MaxSize = new System.Drawing.Size(28, 0);
            this.buttonHide.MinSize = new System.Drawing.Size(28, 17);
            this.buttonHide.Name = "buttonHide";
            this.buttonHide.Size = new System.Drawing.Size(28, 523);
            this.buttonHide.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.buttonHide.Text = " ";
            this.buttonHide.TextSize = new System.Drawing.Size(148, 20);
            this.buttonHide.MouseDown += new System.Windows.Forms.MouseEventHandler(this.simpleLabelItem1_MouseDown);
            this.simpleLabelItem2.AllowHotTrack = false;
            this.simpleLabelItem2.AllowHtmlStringInCaption = true;
            this.simpleLabelItem2.AppearanceItemCaption.FontSizeDelta = 3;
            this.simpleLabelItem2.AppearanceItemCaption.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(140)))), ((int)(((byte)(140)))), ((int)(((byte)(140)))));
            this.simpleLabelItem2.AppearanceItemCaption.Options.UseFont = true;
            this.simpleLabelItem2.AppearanceItemCaption.Options.UseForeColor = true;
            this.simpleLabelItem2.AppearanceItemCaption.Options.UseTextOptions = true;
            this.simpleLabelItem2.AppearanceItemCaption.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Near;
            this.simpleLabelItem2.CustomizationFormText = " ";
            this.simpleLabelItem2.Location = new System.Drawing.Point(0, 0);
            this.simpleLabelItem2.Name = "simpleLabelItem2";
            this.simpleLabelItem2.Padding = new DevExpress.XtraLayout.Utils.Padding(4, 2, 10, 10);
            this.simpleLabelItem2.Size = new System.Drawing.Size(868, 45);
            this.simpleLabelItem2.Text = "EMPLOYEE <color=47, 81, 165>Status";
            this.simpleLabelItem2.TextSize = new System.Drawing.Size(148, 25);
            this.layoutControlItem1.Control = this.gridControl1;
            this.layoutControlItem1.CustomizationFormText = "layoutControlItem1";
            this.layoutControlItem1.Location = new System.Drawing.Point(268, 45);
            this.layoutControlItem1.Name = "layoutControlItem1";
            this.layoutControlItem1.Padding = new DevExpress.XtraLayout.Utils.Padding(0, 0, -10, 0);
            this.layoutControlItem1.Size = new System.Drawing.Size(600, 523);
            this.layoutControlItem1.TextSize = new System.Drawing.Size(0, 0);
            this.layoutControlItem1.TextVisible = false;
            this.layoutControl2.AutoScroll = false;
            this.layoutControl2.Controls.Add(this.printEmployeeListButton);
            this.layoutControl2.Controls.Add(this.printEmployeeDirectoryButton);
            this.layoutControl2.Controls.Add(this.printEmployeeProfile);
            this.layoutControl2.Location = new System.Drawing.Point(0, 0);
            this.layoutControl2.Margin = new System.Windows.Forms.Padding(5, 8, 5, 8);
            this.layoutControl2.MaximumSize = new System.Drawing.Size(215, 273);
            this.layoutControl2.MinimumSize = new System.Drawing.Size(215, 273);
            this.layoutControl2.Name = "layoutControl2";
            this.layoutControl2.OptionsView.AllowGlyphSkinning = true;
            this.layoutControl2.OptionsView.AllowHotTrack = true;
            this.layoutControl2.OptionsView.HighlightFocusedItem = true;
            this.layoutControl2.OptionsView.UseParentAutoScaleFactor = true;
            this.layoutControl2.Root = this.layoutControlGroup2;
            this.layoutControl2.Size = new System.Drawing.Size(215, 273);
            this.layoutControl2.TabIndex = 0;
            this.layoutControl2.Text = "layoutControl2";
            this.printEmployeeListButton.EditValue = ((object)(resources.GetObject("printEmployeeListButton.EditValue")));
            this.printEmployeeListButton.Location = new System.Drawing.Point(15, 185);
            this.printEmployeeListButton.Margin = new System.Windows.Forms.Padding(5, 8, 5, 8);
            this.printEmployeeListButton.MaximumSize = new System.Drawing.Size(57, 75);
            this.printEmployeeListButton.MinimumSize = new System.Drawing.Size(57, 75);
            this.printEmployeeListButton.Name = "printEmployeeListButton";
            this.printEmployeeListButton.Size = new System.Drawing.Size(57, 75);
            this.printEmployeeListButton.StyleController = this.layoutControl2;
            this.printEmployeeListButton.TabIndex = 6;
            this.printEmployeeListButton.Click += new System.EventHandler(this.printEmployeeListItem_Click);
            this.printEmployeeDirectoryButton.EditValue = ((object)(resources.GetObject("printEmployeeDirectoryButton.EditValue")));
            this.printEmployeeDirectoryButton.Location = new System.Drawing.Point(15, 100);
            this.printEmployeeDirectoryButton.Margin = new System.Windows.Forms.Padding(5, 8, 5, 8);
            this.printEmployeeDirectoryButton.MaximumSize = new System.Drawing.Size(57, 75);
            this.printEmployeeDirectoryButton.MinimumSize = new System.Drawing.Size(57, 75);
            this.printEmployeeDirectoryButton.Name = "printEmployeeDirectoryButton";
            this.printEmployeeDirectoryButton.Size = new System.Drawing.Size(57, 75);
            this.printEmployeeDirectoryButton.StyleController = this.layoutControl2;
            this.printEmployeeDirectoryButton.TabIndex = 5;
            this.printEmployeeDirectoryButton.Click += new System.EventHandler(this.printEmployeeDirectoryItem_Click);
            this.printEmployeeProfile.EditValue = ((object)(resources.GetObject("printEmployeeProfile.EditValue")));
            this.printEmployeeProfile.Location = new System.Drawing.Point(15, 15);
            this.printEmployeeProfile.Margin = new System.Windows.Forms.Padding(5, 8, 5, 8);
            this.printEmployeeProfile.MaximumSize = new System.Drawing.Size(57, 75);
            this.printEmployeeProfile.MinimumSize = new System.Drawing.Size(57, 75);
            this.printEmployeeProfile.Name = "printEmployeeProfile";
            this.printEmployeeProfile.Size = new System.Drawing.Size(57, 75);
            this.printEmployeeProfile.StyleController = this.layoutControl2;
            this.printEmployeeProfile.TabIndex = 4;
            this.printEmployeeProfile.Click += new System.EventHandler(this.printEmployeeProfileItem_Click);
            this.layoutControlGroup2.CustomizationFormText = "layoutControlGroup2";
            this.layoutControlGroup2.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True;
            this.layoutControlGroup2.GroupBordersVisible = false;
            this.layoutControlGroup2.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.printEmployeeProfileItem,
            this.printEmployeeDirectoryItem,
            this.printEmployeeListItem,
            this.emptySpaceItem1});
            this.layoutControlGroup2.Location = new System.Drawing.Point(0, 0);
            this.layoutControlGroup2.Name = "layoutControlGroup2";
            this.layoutControlGroup2.Size = new System.Drawing.Size(221, 285);
            this.layoutControlGroup2.TextVisible = false;
            this.printEmployeeProfileItem.Control = this.printEmployeeProfile;
            this.printEmployeeProfileItem.CustomizationFormText = "Employee Profile";
            this.printEmployeeProfileItem.Location = new System.Drawing.Point(0, 0);
            this.printEmployeeProfileItem.Name = "printEmployeeProfileItem";
            this.printEmployeeProfileItem.Padding = new DevExpress.XtraLayout.Utils.Padding(5, 5, 5, 5);
            this.printEmployeeProfileItem.Size = new System.Drawing.Size(201, 85);
            this.printEmployeeProfileItem.Text = "Employee Profile";
            this.printEmployeeProfileItem.TextLocation = DevExpress.Utils.Locations.Right;
            this.printEmployeeProfileItem.TextSize = new System.Drawing.Size(131, 20);
            this.printEmployeeProfileItem.Click += new System.EventHandler(this.printEmployeeProfileItem_Click);
            this.printEmployeeDirectoryItem.Control = this.printEmployeeDirectoryButton;
            this.printEmployeeDirectoryItem.CustomizationFormText = "Employee Directory";
            this.printEmployeeDirectoryItem.Location = new System.Drawing.Point(0, 85);
            this.printEmployeeDirectoryItem.Name = "printEmployeeDirectoryItem";
            this.printEmployeeDirectoryItem.Padding = new DevExpress.XtraLayout.Utils.Padding(5, 5, 5, 5);
            this.printEmployeeDirectoryItem.Size = new System.Drawing.Size(201, 85);
            this.printEmployeeDirectoryItem.Text = "Employee Directory";
            this.printEmployeeDirectoryItem.TextLocation = DevExpress.Utils.Locations.Right;
            this.printEmployeeDirectoryItem.TextSize = new System.Drawing.Size(131, 20);
            this.printEmployeeDirectoryItem.Click += new System.EventHandler(this.printEmployeeDirectoryItem_Click);
            this.printEmployeeListItem.Control = this.printEmployeeListButton;
            this.printEmployeeListItem.CustomizationFormText = "Employee List";
            this.printEmployeeListItem.Location = new System.Drawing.Point(0, 170);
            this.printEmployeeListItem.Name = "printEmployeeListItem";
            this.printEmployeeListItem.Padding = new DevExpress.XtraLayout.Utils.Padding(5, 5, 5, 5);
            this.printEmployeeListItem.Size = new System.Drawing.Size(201, 85);
            this.printEmployeeListItem.Text = "Employee List";
            this.printEmployeeListItem.TextLocation = DevExpress.Utils.Locations.Right;
            this.printEmployeeListItem.TextSize = new System.Drawing.Size(131, 20);
            this.printEmployeeListItem.Click += new System.EventHandler(this.printEmployeeListItem_Click);
            this.emptySpaceItem1.AllowHotTrack = false;
            this.emptySpaceItem1.CustomizationFormText = "emptySpaceItem1";
            this.emptySpaceItem1.Location = new System.Drawing.Point(0, 255);
            this.emptySpaceItem1.Name = "emptySpaceItem1";
            this.emptySpaceItem1.Size = new System.Drawing.Size(201, 10);
            this.emptySpaceItem1.TextSize = new System.Drawing.Size(0, 0);
            this.Appearance.BackColor = System.Drawing.Color.White;
            this.Appearance.Options.UseBackColor = true;
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 20F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.layoutControl1);
            this.Controls.Add(this.layoutControl2);
            this.Margin = new System.Windows.Forms.Padding(5, 8, 5, 8);
            this.Name = "Employees";
            this.Size = new System.Drawing.Size(948, 568);
            ((System.ComponentModel.ISupportInitialize)(this.employeeBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControl1)).EndInit();
            this.layoutControl1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.gridControl1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.tileView1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.flyoutPanel1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.tileControlLayoutItem)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.buttonHide)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.simpleLabelItem2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControl2)).EndInit();
            this.layoutControl2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.printEmployeeListButton.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.printEmployeeDirectoryButton.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.printEmployeeProfile.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.printEmployeeProfileItem)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.printEmployeeDirectoryItem)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.printEmployeeListItem)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private XtraEditors.TileControl filterTileControl;
        private XtraEditors.TileGroup tileGroup2;
        private XtraEditors.TileItem tileItemAll;
        private XtraEditors.TileItem tileItemSalaried;
        private XtraEditors.TileItem tileItemCommission;
        private XtraEditors.TileItem tileItemContract;
        private XtraEditors.TileItem tileItemTerminated;
        private XtraEditors.TileItem tileItemOnLeave;
        private XtraLayout.LayoutControl layoutControl1;
        private XtraLayout.LayoutControlGroup layoutControlGroup1;
        private XtraLayout.LayoutControlItem tileControlLayoutItem;
        private XtraLayout.SimpleLabelItem buttonHide;
        private XtraLayout.SimpleLabelItem simpleLabelItem2;
        private System.Windows.Forms.BindingSource employeeBindingSource;
        private DevExpress.Utils.FlyoutPanel flyoutPanel1;
        private XtraLayout.LayoutControl layoutControl2;
        private XtraEditors.PictureEdit printEmployeeListButton;
        private XtraEditors.PictureEdit printEmployeeDirectoryButton;
        private XtraEditors.PictureEdit printEmployeeProfile;
        private XtraLayout.LayoutControlGroup layoutControlGroup2;
        private XtraLayout.LayoutControlItem printEmployeeProfileItem;
        private XtraLayout.LayoutControlItem printEmployeeDirectoryItem;
        private XtraLayout.LayoutControlItem printEmployeeListItem;
        private XtraLayout.EmptySpaceItem emptySpaceItem1;
        private XtraGrid.GridControl gridControl1;
        private XtraLayout.LayoutControlItem layoutControlItem1;
        private XtraGrid.Views.Tile.TileView tileView1;
        private XtraGrid.Columns.TileViewColumn colDepartment;
        private XtraGrid.Columns.TileViewColumn colTitle;
        private XtraGrid.Columns.TileViewColumn colStatus;
        private XtraGrid.Columns.TileViewColumn colHireDate;
        private XtraGrid.Columns.TileViewColumn colPersonalProfile;
        private XtraGrid.Columns.TileViewColumn colProbationReason;
        private XtraGrid.Columns.TileViewColumn colFirstName;
        private XtraGrid.Columns.TileViewColumn colLastName;
        private XtraGrid.Columns.TileViewColumn colFullName;
        private XtraGrid.Columns.TileViewColumn colPrefix;
        private XtraGrid.Columns.TileViewColumn colHomePhone;
        private XtraGrid.Columns.TileViewColumn colMobilePhone;
        private XtraGrid.Columns.TileViewColumn colEmail;
        private XtraGrid.Columns.TileViewColumn colSkype;
        private XtraGrid.Columns.TileViewColumn colBirthDate;
        private XtraGrid.Columns.TileViewColumn colPicture;
        private XtraGrid.Columns.TileViewColumn colPictureId;
        private XtraGrid.Columns.TileViewColumn colAddress;
        private XtraGrid.Columns.TileViewColumn colPhoto;
        private XtraGrid.Columns.TileViewColumn colFullNameBindable;
        private XtraGrid.Columns.TileViewColumn colId;
    }
}
