namespace DevExpress.DevAV.Modules {
    public partial class CustomersModule {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing) {
            if(disposing && (components != null)) {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent() {
            this.components = new System.ComponentModel.Container();
            DevExpress.XtraGrid.Views.Tile.TileViewItemElement tileViewItemElement1 = new DevExpress.XtraGrid.Views.Tile.TileViewItemElement();
            DevExpress.XtraGrid.Views.Tile.TileViewItemElement tileViewItemElement2 = new DevExpress.XtraGrid.Views.Tile.TileViewItemElement();
            DevExpress.XtraGrid.Views.Tile.TileViewItemElement tileViewItemElement3 = new DevExpress.XtraGrid.Views.Tile.TileViewItemElement();
            DevExpress.XtraGrid.Views.Tile.TileViewItemElement tileViewItemElement4 = new DevExpress.XtraGrid.Views.Tile.TileViewItemElement();
            DevExpress.XtraGrid.Views.Tile.TileViewItemElement tileViewItemElement5 = new DevExpress.XtraGrid.Views.Tile.TileViewItemElement();
            DevExpress.XtraGrid.Views.Tile.TileViewItemElement tileViewItemElement6 = new DevExpress.XtraGrid.Views.Tile.TileViewItemElement();
            DevExpress.XtraGrid.Views.Tile.TileViewItemElement tileViewItemElement7 = new DevExpress.XtraGrid.Views.Tile.TileViewItemElement();
            DevExpress.XtraGrid.Views.Tile.TileViewItemElement tileViewItemElement8 = new DevExpress.XtraGrid.Views.Tile.TileViewItemElement();
            DevExpress.XtraGrid.Views.Tile.TileViewItemElement tileViewItemElement9 = new DevExpress.XtraGrid.Views.Tile.TileViewItemElement();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(CustomersModule));
            DevExpress.Sparkline.BarSparklineView barSparklineView1 = new DevExpress.Sparkline.BarSparklineView();
            this.colCrestImage = new DevExpress.XtraGrid.Columns.TileViewColumn();
            this.colCityName = new DevExpress.XtraGrid.Columns.TileViewColumn();
            this.colAddressLine = new DevExpress.XtraGrid.Columns.TileViewColumn();
            this.colAddressCityLine = new DevExpress.XtraGrid.Columns.TileViewColumn();
            this.colPhoto = new DevExpress.XtraGrid.Columns.TileViewColumn();
            this.colFullName = new DevExpress.XtraGrid.Columns.TileViewColumn();
            this.colPosition = new DevExpress.XtraGrid.Columns.TileViewColumn();
            this.colAddress = new DevExpress.XtraGrid.Columns.TileViewColumn();
            this.layoutControl1 = new DevExpress.XtraLayout.LayoutControl();
            this.gridControlStores = new DevExpress.XtraGrid.GridControl();
            this.customerStoreBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.tileViewStores = new DevExpress.XtraGrid.Views.Tile.TileView();
            this.barManager1 = new DevExpress.XtraBars.BarManager(this.components);
            this.barDockControlTop = new DevExpress.XtraBars.BarDockControl();
            this.barDockControlBottom = new DevExpress.XtraBars.BarDockControl();
            this.barDockControlLeft = new DevExpress.XtraBars.BarDockControl();
            this.barDockControlRight = new DevExpress.XtraBars.BarDockControl();
            this.barButtonItemContacts = new DevExpress.XtraBars.BarButtonItem();
            this.barButtonItemStores = new DevExpress.XtraBars.BarButtonItem();
            this.gridView2 = new DevExpress.XtraGrid.Views.Grid.GridView();
            this.gridControlEmployee = new DevExpress.XtraGrid.GridControl();
            this.customerEmployeeBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.tileViewEmployee = new DevExpress.XtraGrid.Views.Tile.TileView();
            this.gridView1 = new DevExpress.XtraGrid.Views.Grid.GridView();
            this.dropDownButton1 = new DevExpress.XtraEditors.DropDownButton();
            this.popupMenu1 = new DevExpress.XtraBars.PopupMenu(this.components);
            this.labelControl1 = new DevExpress.XtraEditors.LabelControl();
            this.gridCustomers = new DevExpress.XtraGrid.GridControl();
            this.customerBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.viewCustomers = new DevExpress.XtraGrid.Views.Grid.GridView();
            this.colName = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colPhone = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colFax = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumnAddress = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumnCity = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumnState = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumnZipCode = new DevExpress.XtraGrid.Columns.GridColumn();
            this.repositoryItemTextEdit3 = new DevExpress.XtraEditors.Repository.RepositoryItemTextEdit();
            this.colMonthlySales = new DevExpress.XtraGrid.Columns.GridColumn();
            this.repositoryItemSparklineEdit1 = new DevExpress.XtraEditors.Repository.RepositoryItemSparklineEdit();
            this.layoutControlGroup1 = new DevExpress.XtraLayout.LayoutControlGroup();
            this.layoutControlItem2 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem3 = new DevExpress.XtraLayout.LayoutControlItem();
            this.emptySpaceItem1 = new DevExpress.XtraLayout.EmptySpaceItem();
            this.simpleLabelItem1 = new DevExpress.XtraLayout.SimpleLabelItem();
            this.layoutControlItem1 = new DevExpress.XtraLayout.LayoutControlItem();
            this.employeeGridLCI = new DevExpress.XtraLayout.LayoutControlItem();
            this.storesGridLCI = new DevExpress.XtraLayout.LayoutControlItem();
            this.repositoryItemPictureEdit2 = new DevExpress.XtraEditors.Repository.RepositoryItemPictureEdit();
            this.layoutViewCard2 = new DevExpress.XtraGrid.Views.Layout.LayoutViewCard();
            this.repositoryItemTextEdit1 = new DevExpress.XtraEditors.Repository.RepositoryItemTextEdit();
            this.repositoryItemTextEdit2 = new DevExpress.XtraEditors.Repository.RepositoryItemTextEdit();
            this.repositoryItemPictureEdit1 = new DevExpress.XtraEditors.Repository.RepositoryItemPictureEdit();
            this.layoutViewCard1 = new DevExpress.XtraGrid.Views.Layout.LayoutViewCard();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControl1)).BeginInit();
            this.layoutControl1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.gridControlStores)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.customerStoreBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.tileViewStores)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.barManager1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridView2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridControlEmployee)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.customerEmployeeBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.tileViewEmployee)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridView1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.popupMenu1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridCustomers)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.customerBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.viewCustomers)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.repositoryItemTextEdit3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.repositoryItemSparklineEdit1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.simpleLabelItem1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.employeeGridLCI)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.storesGridLCI)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.repositoryItemPictureEdit2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutViewCard2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.repositoryItemTextEdit1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.repositoryItemTextEdit2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.repositoryItemPictureEdit1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutViewCard1)).BeginInit();
            this.SuspendLayout();
            this.colCrestImage.Caption = "colCrestImage";
            this.colCrestImage.FieldName = "Crest.LargeImageEx";
            this.colCrestImage.Name = "colCrestImage";
            this.colCrestImage.Visible = true;
            this.colCrestImage.VisibleIndex = 0;
            this.colCityName.Caption = "colCityName";
            this.colCityName.FieldName = "Crest.CityName";
            this.colCityName.Name = "colCityName";
            this.colCityName.Visible = true;
            this.colCityName.VisibleIndex = 1;
            this.colAddressLine.Caption = "colAddressLine";
            this.colAddressLine.FieldName = "Address.Line";
            this.colAddressLine.Name = "colAddressLine";
            this.colAddressLine.Visible = true;
            this.colAddressLine.VisibleIndex = 2;
            this.colAddressCityLine.Caption = "colAddressCityLine";
            this.colAddressCityLine.FieldName = "Address.CityLine";
            this.colAddressCityLine.Name = "colAddressCityLine";
            this.colAddressCityLine.Visible = true;
            this.colAddressCityLine.VisibleIndex = 3;
            this.colPhoto.FieldName = "Photo";
            this.colPhoto.Name = "colPhoto";
            this.colPhoto.Visible = true;
            this.colPhoto.VisibleIndex = 3;
            this.colFullName.Caption = "colFullName";
            this.colFullName.FieldName = "FullName";
            this.colFullName.Name = "colFullName";
            this.colFullName.Visible = true;
            this.colFullName.VisibleIndex = 0;
            this.colPosition.FieldName = "Position";
            this.colPosition.Name = "colPosition";
            this.colPosition.Visible = true;
            this.colPosition.VisibleIndex = 1;
            this.colAddress.Caption = "colAddress";
            this.colAddress.DisplayFormat.FormatString = "({0})";
            this.colAddress.DisplayFormat.FormatType = DevExpress.Utils.FormatType.Custom;
            this.colAddress.FieldName = "Address.City";
            this.colAddress.Name = "colAddress";
            this.colAddress.OptionsColumn.ReadOnly = true;
            this.colAddress.Visible = true;
            this.colAddress.VisibleIndex = 2;
            this.layoutControl1.BackColor = System.Drawing.Color.Transparent;
            this.layoutControl1.Controls.Add(this.gridControlStores);
            this.layoutControl1.Controls.Add(this.gridControlEmployee);
            this.layoutControl1.Controls.Add(this.dropDownButton1);
            this.layoutControl1.Controls.Add(this.labelControl1);
            this.layoutControl1.Controls.Add(this.gridCustomers);
            this.layoutControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.layoutControl1.Location = new System.Drawing.Point(0, 0);
            this.layoutControl1.Name = "layoutControl1";
            this.layoutControl1.AllowCustomization = false;
            this.layoutControl1.OptionsCustomizationForm.DesignTimeCustomizationFormPositionAndSize = new System.Drawing.Rectangle(74, 51, 930, 751);
            this.layoutControl1.OptionsView.UseParentAutoScaleFactor = true;
            this.layoutControl1.Root = this.layoutControlGroup1;
            this.layoutControl1.Size = new System.Drawing.Size(1105, 582);
            this.layoutControl1.TabIndex = 0;
            this.layoutControl1.Text = "layoutControl1";
            this.gridControlStores.DataSource = this.customerStoreBindingSource;
            this.gridControlStores.Location = new System.Drawing.Point(550, 384);
            this.gridControlStores.MainView = this.tileViewStores;
            this.gridControlStores.MenuManager = this.barManager1;
            this.gridControlStores.Name = "gridControlStores";
            this.gridControlStores.Size = new System.Drawing.Size(513, 208);
            this.gridControlStores.TabIndex = 9;
            this.gridControlStores.ViewCollection.AddRange(new DevExpress.XtraGrid.Views.Base.BaseView[] {
            this.tileViewStores,
            this.gridView2});
            this.customerStoreBindingSource.DataSource = typeof(DevExpress.DevAV.CustomerStore);
            this.tileViewStores.Appearance.ItemNormal.BorderColor = System.Drawing.Color.Transparent;
            this.tileViewStores.Appearance.ItemNormal.FontSizeDelta = -1;
            this.tileViewStores.Appearance.ItemNormal.Options.UseBorderColor = true;
            this.tileViewStores.Appearance.ItemNormal.Options.UseFont = true;
            this.tileViewStores.Columns.AddRange(new DevExpress.XtraGrid.Columns.GridColumn[] {
            this.colCrestImage,
            this.colCityName,
            this.colAddressLine,
            this.colAddressCityLine});
            this.tileViewStores.FocusBorderColor = System.Drawing.Color.Transparent;
            this.tileViewStores.GridControl = this.gridControlStores;
            this.tileViewStores.Name = "tileViewStores";
            this.tileViewStores.OptionsTiles.AllowPressAnimation = false;
            this.tileViewStores.OptionsTiles.HorizontalContentAlignment = DevExpress.Utils.HorzAlignment.Near;
            this.tileViewStores.OptionsTiles.IndentBetweenItems = 14;
            this.tileViewStores.OptionsTiles.ItemPadding = new System.Windows.Forms.Padding(0);
            this.tileViewStores.OptionsTiles.ItemSize = new System.Drawing.Size(122, 175);
            this.tileViewStores.OptionsTiles.Padding = new System.Windows.Forms.Padding(0);
            this.tileViewStores.OptionsTiles.ShowGroupText = false;
            this.tileViewStores.OptionsTiles.VerticalContentAlignment = DevExpress.Utils.VertAlignment.Top;
            tileViewItemElement1.Column = this.colCrestImage;
            tileViewItemElement1.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopCenter;
            tileViewItemElement1.ImageBorder = DevExpress.XtraEditors.TileItemElementImageBorderMode.None;
            tileViewItemElement1.ImageBorderColor = System.Drawing.Color.Empty;
            tileViewItemElement1.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomInside;
            tileViewItemElement1.ImageSize = new System.Drawing.Size(120, 120);
            tileViewItemElement1.Text = "colCrestImage";
            tileViewItemElement2.AnchorIndent = 0;
            tileViewItemElement2.Column = this.colCityName;
            tileViewItemElement2.ImageBorderColor = System.Drawing.Color.Empty;
            tileViewItemElement2.Text = "colCityName";
            tileViewItemElement2.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileViewItemElement2.TextLocation = new System.Drawing.Point(0, 45);
            tileViewItemElement3.Appearance.Normal.ForeColor = System.Drawing.Color.Gray;
            tileViewItemElement3.Appearance.Normal.Options.UseForeColor = true;
            tileViewItemElement3.Appearance.Normal.Options.UseTextOptions = true;
            tileViewItemElement3.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileViewItemElement3.Column = this.colAddressLine;
            tileViewItemElement3.ImageBorderColor = System.Drawing.Color.Empty;
            tileViewItemElement3.MaxWidth = 120;
            tileViewItemElement3.Text = "colAddressLine";
            tileViewItemElement3.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileViewItemElement3.TextLocation = new System.Drawing.Point(0, 60);
            tileViewItemElement4.Appearance.Normal.ForeColor = System.Drawing.Color.Gray;
            tileViewItemElement4.Appearance.Normal.Options.UseForeColor = true;
            tileViewItemElement4.Appearance.Normal.Options.UseTextOptions = true;
            tileViewItemElement4.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileViewItemElement4.Column = this.colAddressCityLine;
            tileViewItemElement4.ImageBorderColor = System.Drawing.Color.Empty;
            tileViewItemElement4.MaxWidth = 120;
            tileViewItemElement4.Text = "colAddressCityLine";
            tileViewItemElement4.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileViewItemElement4.TextLocation = new System.Drawing.Point(0, 75);
            this.tileViewStores.TileTemplate.Add(tileViewItemElement1);
            this.tileViewStores.TileTemplate.Add(tileViewItemElement2);
            this.tileViewStores.TileTemplate.Add(tileViewItemElement3);
            this.tileViewStores.TileTemplate.Add(tileViewItemElement4);
            this.barManager1.DockControls.Add(this.barDockControlTop);
            this.barManager1.DockControls.Add(this.barDockControlBottom);
            this.barManager1.DockControls.Add(this.barDockControlLeft);
            this.barManager1.DockControls.Add(this.barDockControlRight);
            this.barManager1.Form = this;
            this.barManager1.Items.AddRange(new DevExpress.XtraBars.BarItem[] {
            this.barButtonItemContacts,
            this.barButtonItemStores});
            this.barManager1.MaxItemId = 2;
            this.barDockControlTop.CausesValidation = false;
            this.barDockControlTop.Dock = System.Windows.Forms.DockStyle.Top;
            this.barDockControlTop.Location = new System.Drawing.Point(0, 0);
            this.barDockControlTop.Size = new System.Drawing.Size(1105, 0);
            this.barDockControlBottom.CausesValidation = false;
            this.barDockControlBottom.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.barDockControlBottom.Location = new System.Drawing.Point(0, 582);
            this.barDockControlBottom.Size = new System.Drawing.Size(1105, 0);
            this.barDockControlLeft.CausesValidation = false;
            this.barDockControlLeft.Dock = System.Windows.Forms.DockStyle.Left;
            this.barDockControlLeft.Location = new System.Drawing.Point(0, 0);
            this.barDockControlLeft.Size = new System.Drawing.Size(0, 582);
            this.barDockControlRight.CausesValidation = false;
            this.barDockControlRight.Dock = System.Windows.Forms.DockStyle.Right;
            this.barDockControlRight.Location = new System.Drawing.Point(1105, 0);
            this.barDockControlRight.Size = new System.Drawing.Size(0, 582);
            this.barButtonItemContacts.Caption = "Contacts";
            this.barButtonItemContacts.Id = 0;
            this.barButtonItemContacts.Name = "barButtonItemContacts";
            this.barButtonItemContacts.ItemClick += new DevExpress.XtraBars.ItemClickEventHandler(this.barButtonItemContacts_ItemClick);
            this.barButtonItemStores.Caption = "Stores";
            this.barButtonItemStores.Id = 1;
            this.barButtonItemStores.Name = "barButtonItemStores";
            this.barButtonItemStores.ItemClick += new DevExpress.XtraBars.ItemClickEventHandler(this.barButtonItemStores_ItemClick);
            this.gridView2.GridControl = this.gridControlStores;
            this.gridView2.Name = "gridView2";
            this.gridControlEmployee.DataSource = this.customerEmployeeBindingSource;
            this.gridControlEmployee.Location = new System.Drawing.Point(40, 384);
            this.gridControlEmployee.MainView = this.tileViewEmployee;
            this.gridControlEmployee.MenuManager = this.barManager1;
            this.gridControlEmployee.Name = "gridControlEmployee";
            this.gridControlEmployee.Size = new System.Drawing.Size(508, 208);
            this.gridControlEmployee.TabIndex = 8;
            this.gridControlEmployee.ViewCollection.AddRange(new DevExpress.XtraGrid.Views.Base.BaseView[] {
            this.tileViewEmployee,
            this.gridView1});
            this.customerEmployeeBindingSource.DataSource = typeof(DevExpress.DevAV.CustomerEmployee);
            this.tileViewEmployee.Appearance.ItemNormal.BorderColor = System.Drawing.Color.Transparent;
            this.tileViewEmployee.Appearance.ItemNormal.FontSizeDelta = -1;
            this.tileViewEmployee.Appearance.ItemNormal.Options.UseBorderColor = true;
            this.tileViewEmployee.Appearance.ItemNormal.Options.UseFont = true;
            this.tileViewEmployee.Columns.AddRange(new DevExpress.XtraGrid.Columns.GridColumn[] {
            this.colFullName,
            this.colPosition,
            this.colAddress,
            this.colPhoto});
            this.tileViewEmployee.FocusBorderColor = System.Drawing.Color.Transparent;
            this.tileViewEmployee.GridControl = this.gridControlEmployee;
            this.tileViewEmployee.Name = "tileViewEmployee";
            this.tileViewEmployee.OptionsTiles.AllowPressAnimation = false;
            this.tileViewEmployee.OptionsTiles.HorizontalContentAlignment = DevExpress.Utils.HorzAlignment.Near;
            this.tileViewEmployee.OptionsTiles.IndentBetweenItems = 14;
            this.tileViewEmployee.OptionsTiles.ItemPadding = new System.Windows.Forms.Padding(0);
            this.tileViewEmployee.OptionsTiles.ItemSize = new System.Drawing.Size(122, 175);
            this.tileViewEmployee.OptionsTiles.Padding = new System.Windows.Forms.Padding(0);
            this.tileViewEmployee.OptionsTiles.ShowGroupText = false;
            this.tileViewEmployee.OptionsTiles.VerticalContentAlignment = DevExpress.Utils.VertAlignment.Top;
            tileViewItemElement5.Column = this.colPhoto;
            tileViewItemElement5.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopCenter;
            tileViewItemElement5.ImageBorder = DevExpress.XtraEditors.TileItemElementImageBorderMode.None;
            tileViewItemElement5.ImageBorderColor = System.Drawing.Color.Empty;
            tileViewItemElement5.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomInside;
            tileViewItemElement5.ImageSize = new System.Drawing.Size(120, 120);
            tileViewItemElement5.Text = "colPhoto";
            tileViewItemElement6.AnchorIndent = 0;
            tileViewItemElement6.Column = this.colFullName;
            tileViewItemElement6.ImageBorderColor = System.Drawing.Color.Empty;
            tileViewItemElement6.Text = "colFullName";
            tileViewItemElement6.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileViewItemElement6.TextLocation = new System.Drawing.Point(0, 45);
            tileViewItemElement7.Appearance.Normal.ForeColor = System.Drawing.Color.Gray;
            tileViewItemElement7.Appearance.Normal.Options.UseForeColor = true;
            tileViewItemElement7.Column = this.colPosition;
            tileViewItemElement7.ImageBorderColor = System.Drawing.Color.Empty;
            tileViewItemElement7.Text = "colPosition";
            tileViewItemElement7.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileViewItemElement7.TextLocation = new System.Drawing.Point(0, 60);
            tileViewItemElement8.Appearance.Normal.ForeColor = System.Drawing.Color.Gray;
            tileViewItemElement8.Appearance.Normal.Options.UseForeColor = true;
            tileViewItemElement8.Column = this.colAddress;
            tileViewItemElement8.ImageBorderColor = System.Drawing.Color.Empty;
            tileViewItemElement8.Text = "colAddress";
            tileViewItemElement8.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileViewItemElement8.TextLocation = new System.Drawing.Point(0, 75);
            tileViewItemElement9.Column = null;
            tileViewItemElement9.Image = ((System.Drawing.Image)(resources.GetObject("tileViewItemElement9.Image")));
            tileViewItemElement9.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopCenter;
            tileViewItemElement9.ImageBorder = DevExpress.XtraEditors.TileItemElementImageBorderMode.SingleBorder;
            tileViewItemElement9.ImageBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            tileViewItemElement9.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.Stretch;
            tileViewItemElement9.ImageSize = new System.Drawing.Size(120, 120);
            tileViewItemElement9.Text = "";
            this.tileViewEmployee.TileTemplate.Add(tileViewItemElement5);
            this.tileViewEmployee.TileTemplate.Add(tileViewItemElement6);
            this.tileViewEmployee.TileTemplate.Add(tileViewItemElement7);
            this.tileViewEmployee.TileTemplate.Add(tileViewItemElement8);
            this.tileViewEmployee.TileTemplate.Add(tileViewItemElement9);
            this.gridView1.GridControl = this.gridControlEmployee;
            this.gridView1.Name = "gridView1";
            this.dropDownButton1.Appearance.FontSizeDelta = 3;
            this.dropDownButton1.Appearance.Options.UseFont = true;
            this.dropDownButton1.Appearance.Options.UseTextOptions = true;
            this.dropDownButton1.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Near;
            this.dropDownButton1.DropDownControl = this.popupMenu1;
            this.dropDownButton1.Location = new System.Drawing.Point(186, 348);
            this.dropDownButton1.Name = "dropDownButton1";
            this.dropDownButton1.Size = new System.Drawing.Size(108, 32);
            this.dropDownButton1.StyleController = this.layoutControl1;
            this.dropDownButton1.TabIndex = 7;
            this.dropDownButton1.Text = "Contacts";
            this.dropDownButton1.ShowDropDownControl += new DevExpress.XtraEditors.ShowDropDownControlEventHandler(this.dropDownButton1_ShowDropDownControl);
            this.dropDownButton1.Click += new System.EventHandler(this.dropDownButton1_Click);
            this.popupMenu1.LinksPersistInfo.AddRange(new DevExpress.XtraBars.LinkPersistInfo[] {
            new DevExpress.XtraBars.LinkPersistInfo(this.barButtonItemContacts),
            new DevExpress.XtraBars.LinkPersistInfo(this.barButtonItemStores)});
            this.popupMenu1.Manager = this.barManager1;
            this.popupMenu1.Name = "popupMenu1";
            this.labelControl1.Appearance.FontSizeDelta = 3;
            this.labelControl1.Appearance.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(81)))), ((int)(((byte)(165)))));
            this.labelControl1.Location = new System.Drawing.Point(42, 351);
            this.labelControl1.Name = "labelControl1";
            this.labelControl1.Size = new System.Drawing.Size(140, 25);
            this.labelControl1.StyleController = this.layoutControl1;
            this.labelControl1.TabIndex = 6;
            this.labelControl1.Text = "Store of America";
            this.gridCustomers.DataSource = this.customerBindingSource;
            this.gridCustomers.Location = new System.Drawing.Point(42, 47);
            this.gridCustomers.MainView = this.viewCustomers;
            this.gridCustomers.Name = "gridCustomers";
            this.gridCustomers.RepositoryItems.AddRange(new DevExpress.XtraEditors.Repository.RepositoryItem[] {
            this.repositoryItemSparklineEdit1,
            this.repositoryItemTextEdit3});
            this.gridCustomers.ShowOnlyPredefinedDetails = true;
            this.gridCustomers.Size = new System.Drawing.Size(1021, 297);
            this.gridCustomers.TabIndex = 0;
            this.gridCustomers.ViewCollection.AddRange(new DevExpress.XtraGrid.Views.Base.BaseView[] {
            this.viewCustomers});
            this.customerBindingSource.DataSource = typeof(DevExpress.DevAV.Customer);
            this.viewCustomers.Appearance.FooterPanel.Options.UseTextOptions = true;
            this.viewCustomers.Appearance.FooterPanel.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            this.viewCustomers.Columns.AddRange(new DevExpress.XtraGrid.Columns.GridColumn[] {
            this.colName,
            this.colPhone,
            this.colFax,
            this.gridColumnAddress,
            this.gridColumnCity,
            this.gridColumnState,
            this.gridColumnZipCode,
            this.colMonthlySales});
            this.viewCustomers.FocusRectStyle = DevExpress.XtraGrid.Views.Grid.DrawFocusRectStyle.None;
            this.viewCustomers.FooterPanelHeight = 59;
            this.viewCustomers.GridControl = this.gridCustomers;
            this.viewCustomers.GroupSummary.AddRange(new DevExpress.XtraGrid.GridSummaryItem[] {
            new DevExpress.XtraGrid.GridGroupSummaryItem(DevExpress.Data.SummaryItemType.Sum, "TotalEmployees", this.colName, "CUSTOMER COUNT {1}"),
            new DevExpress.XtraGrid.GridGroupSummaryItem(DevExpress.Data.SummaryItemType.Sum, "Orders", null, "TOTAL SALES")});
            this.viewCustomers.Name = "viewCustomers";
            this.viewCustomers.OptionsBehavior.Editable = false;
            this.viewCustomers.OptionsCustomization.AllowGroup = false;
            this.viewCustomers.OptionsCustomization.AllowQuickHideColumns = false;
            this.viewCustomers.OptionsDetail.EnableMasterViewMode = false;
            this.viewCustomers.OptionsFind.AllowFindPanel = false;
            this.viewCustomers.OptionsMenu.EnableFooterMenu = false;
            this.viewCustomers.OptionsMenu.ShowAddNewSummaryItem = DevExpress.Utils.DefaultBoolean.False;
            this.viewCustomers.OptionsSelection.EnableAppearanceFocusedCell = false;
            this.viewCustomers.OptionsView.ShowFilterPanelMode = DevExpress.XtraGrid.Views.Base.ShowFilterPanelMode.Never;
            this.viewCustomers.OptionsView.ShowFooter = true;
            this.viewCustomers.OptionsView.ShowGroupPanel = false;
            this.viewCustomers.OptionsView.ShowIndicator = false;
            this.viewCustomers.RowClick += new DevExpress.XtraGrid.Views.Grid.RowClickEventHandler(this.viewCustomers_RowClick);
            this.viewCustomers.CustomDrawFooterCell += new DevExpress.XtraGrid.Views.Grid.FooterCellCustomDrawEventHandler(this.gridView1_CustomDrawFooterCell);
            this.viewCustomers.CustomSummaryCalculate += new DevExpress.Data.CustomSummaryEventHandler(this.gridView1_CustomSummaryCalculate);
            this.viewCustomers.FocusedRowObjectChanged += new DevExpress.XtraGrid.Views.Base.FocusedRowObjectChangedEventHandler(this.viewCustomers_FocusedRowObjectChanged);
            this.viewCustomers.CustomUnboundColumnData += new DevExpress.XtraGrid.Views.Base.CustomColumnDataEventHandler(this.gridView1_CustomUnboundColumnData);
            this.colName.FieldName = "Name";
            this.colName.Name = "colName";
            this.colName.Summary.AddRange(new DevExpress.XtraGrid.GridSummaryItem[] {
            new DevExpress.XtraGrid.GridColumnSummaryItem(DevExpress.Data.SummaryItemType.Count, "Name", "<color=Gray>CUSTOMER COUNT</color><br><b>{0}</b>")});
            this.colName.Visible = true;
            this.colName.VisibleIndex = 0;
            this.colName.Width = 137;
            this.colPhone.FieldName = "Phone";
            this.colPhone.Name = "colPhone";
            this.colPhone.Visible = true;
            this.colPhone.VisibleIndex = 5;
            this.colPhone.Width = 136;
            this.colFax.FieldName = "Fax";
            this.colFax.Name = "colFax";
            this.colFax.Visible = true;
            this.colFax.VisibleIndex = 6;
            this.colFax.Width = 129;
            this.gridColumnAddress.Caption = "Address";
            this.gridColumnAddress.FieldName = "HomeOffice.Line";
            this.gridColumnAddress.Name = "gridColumnAddress";
            this.gridColumnAddress.Visible = true;
            this.gridColumnAddress.VisibleIndex = 1;
            this.gridColumnAddress.Width = 145;
            this.gridColumnCity.Caption = "City";
            this.gridColumnCity.FieldName = "HomeOffice.City";
            this.gridColumnCity.Name = "gridColumnCity";
            this.gridColumnCity.Visible = true;
            this.gridColumnCity.VisibleIndex = 2;
            this.gridColumnCity.Width = 95;
            this.gridColumnState.AppearanceCell.Options.UseTextOptions = true;
            this.gridColumnState.AppearanceCell.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Near;
            this.gridColumnState.Caption = "State";
            this.gridColumnState.FieldName = "HomeOffice.State";
            this.gridColumnState.Name = "gridColumnState";
            this.gridColumnState.SortMode = DevExpress.XtraGrid.ColumnSortMode.DisplayText;
            this.gridColumnState.Visible = true;
            this.gridColumnState.VisibleIndex = 3;
            this.gridColumnState.Width = 59;
            this.gridColumnZipCode.Caption = "Zip Code";
            this.gridColumnZipCode.ColumnEdit = this.repositoryItemTextEdit3;
            this.gridColumnZipCode.FieldName = "HomeOffice.ZipCode";
            this.gridColumnZipCode.Name = "gridColumnZipCode";
            this.gridColumnZipCode.OptionsColumn.FixedWidth = true;
            this.gridColumnZipCode.Visible = true;
            this.gridColumnZipCode.VisibleIndex = 4;
            this.gridColumnZipCode.Width = 101;
            this.repositoryItemTextEdit3.AutoHeight = false;
            this.repositoryItemTextEdit3.Name = "repositoryItemTextEdit3";
            this.colMonthlySales.Caption = "Monthly Sales (FY2013)";
            this.colMonthlySales.ColumnEdit = this.repositoryItemSparklineEdit1;
            this.colMonthlySales.FieldName = "MonthlySales";
            this.colMonthlySales.MaxWidth = 300;
            this.colMonthlySales.MinWidth = 30;
            this.colMonthlySales.Name = "colMonthlySales";
            this.colMonthlySales.OptionsFilter.AllowFilter = false;
            this.colMonthlySales.Summary.AddRange(new DevExpress.XtraGrid.GridSummaryItem[] {
            new DevExpress.XtraGrid.GridColumnSummaryItem(DevExpress.Data.SummaryItemType.Custom, "AnnualRevenue", "<color=Gray>TOTAL SALES (FY2013)</color><br><b>{0:c}</b>", "FY2013")});
            this.colMonthlySales.UnboundType = DevExpress.Data.UnboundColumnType.Object;
            this.colMonthlySales.Visible = true;
            this.colMonthlySales.VisibleIndex = 7;
            this.colMonthlySales.Width = 217;
            this.repositoryItemSparklineEdit1.Name = "repositoryItemSparklineEdit1";
            barSparklineView1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(81)))), ((int)(((byte)(165)))));
            this.repositoryItemSparklineEdit1.View = barSparklineView1;
            this.layoutControlGroup1.CustomizationFormText = "Root";
            this.layoutControlGroup1.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True;
            this.layoutControlGroup1.GroupBordersVisible = false;
            this.layoutControlGroup1.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.layoutControlItem2,
            this.layoutControlItem3,
            this.emptySpaceItem1,
            this.simpleLabelItem1,
            this.layoutControlItem1,
            this.employeeGridLCI,
            this.storesGridLCI});
            this.layoutControlGroup1.Location = new System.Drawing.Point(0, 0);
            this.layoutControlGroup1.Name = "Root";
            this.layoutControlGroup1.Padding = new DevExpress.XtraLayout.Utils.Padding(40, 40, 0, 20);
            this.layoutControlGroup1.Size = new System.Drawing.Size(1105, 582);
            this.layoutControlGroup1.TextVisible = false;
            this.layoutControlItem2.Control = this.gridCustomers;
            this.layoutControlItem2.CustomizationFormText = "layoutControlItem2";
            this.layoutControlItem2.Location = new System.Drawing.Point(0, 45);
            this.layoutControlItem2.Name = "layoutControlItem2";
            this.layoutControlItem2.Size = new System.Drawing.Size(1025, 301);
            this.layoutControlItem2.TextSize = new System.Drawing.Size(0, 0);
            this.layoutControlItem2.TextVisible = false;
            this.layoutControlItem3.Control = this.labelControl1;
            this.layoutControlItem3.ControlAlignment = System.Drawing.ContentAlignment.MiddleLeft;
            this.layoutControlItem3.CustomizationFormText = "layoutControlItem3";
            this.layoutControlItem3.Location = new System.Drawing.Point(0, 346);
            this.layoutControlItem3.Name = "layoutControlItem3";
            this.layoutControlItem3.Size = new System.Drawing.Size(144, 36);
            this.layoutControlItem3.TextSize = new System.Drawing.Size(0, 0);
            this.layoutControlItem3.TextVisible = false;
            this.layoutControlItem3.TrimClientAreaToControl = false;
            this.emptySpaceItem1.AllowHotTrack = false;
            this.emptySpaceItem1.CustomizationFormText = "emptySpaceItem1";
            this.emptySpaceItem1.Location = new System.Drawing.Point(256, 346);
            this.emptySpaceItem1.Name = "emptySpaceItem1";
            this.emptySpaceItem1.Size = new System.Drawing.Size(769, 36);
            this.emptySpaceItem1.TextSize = new System.Drawing.Size(0, 0);
            this.simpleLabelItem1.AllowHotTrack = false;
            this.simpleLabelItem1.AppearanceItemCaption.FontSizeDelta = 3;
            this.simpleLabelItem1.AppearanceItemCaption.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(81)))), ((int)(((byte)(165)))));
            this.simpleLabelItem1.AppearanceItemCaption.Options.UseFont = true;
            this.simpleLabelItem1.AppearanceItemCaption.Options.UseForeColor = true;
            this.simpleLabelItem1.CustomizationFormText = "CUSTOMERS";
            this.simpleLabelItem1.Location = new System.Drawing.Point(0, 0);
            this.simpleLabelItem1.Name = "simpleLabelItem1";
            this.simpleLabelItem1.Padding = new DevExpress.XtraLayout.Utils.Padding(2, 2, 10, 10);
            this.simpleLabelItem1.Size = new System.Drawing.Size(1025, 45);
            this.simpleLabelItem1.Text = "CUSTOMERS";
            this.simpleLabelItem1.TextSize = new System.Drawing.Size(107, 25);
            this.layoutControlItem1.Control = this.dropDownButton1;
            this.layoutControlItem1.ControlAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.layoutControlItem1.CustomizationFormText = "layoutControlItem1";
            this.layoutControlItem1.FillControlToClientArea = false;
            this.layoutControlItem1.Location = new System.Drawing.Point(144, 346);
            this.layoutControlItem1.Name = "layoutControlItem1";
            this.layoutControlItem1.OptionsPrint.AllowPrint = false;
            this.layoutControlItem1.Size = new System.Drawing.Size(112, 36);
            this.layoutControlItem1.TextSize = new System.Drawing.Size(0, 0);
            this.layoutControlItem1.TextVisible = false;
            this.layoutControlItem1.TrimClientAreaToControl = false;
            this.employeeGridLCI.Control = this.gridControlEmployee;
            this.employeeGridLCI.Location = new System.Drawing.Point(0, 382);
            this.employeeGridLCI.MaxSize = new System.Drawing.Size(0, 180);
            this.employeeGridLCI.MinSize = new System.Drawing.Size(104, 180);
            this.employeeGridLCI.Name = "employeeGridLCI";
            this.employeeGridLCI.Padding = new DevExpress.XtraLayout.Utils.Padding(0, 2, 2, -30);
            this.employeeGridLCI.Size = new System.Drawing.Size(510, 180);
            this.employeeGridLCI.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.employeeGridLCI.TextSize = new System.Drawing.Size(0, 0);
            this.employeeGridLCI.TextVisible = false;
            this.storesGridLCI.Control = this.gridControlStores;
            this.storesGridLCI.Location = new System.Drawing.Point(510, 382);
            this.storesGridLCI.MaxSize = new System.Drawing.Size(0, 180);
            this.storesGridLCI.MinSize = new System.Drawing.Size(104, 180);
            this.storesGridLCI.Name = "storesGridLCI";
            this.storesGridLCI.Padding = new DevExpress.XtraLayout.Utils.Padding(0, 2, 2, -30);
            this.storesGridLCI.Size = new System.Drawing.Size(515, 180);
            this.storesGridLCI.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.storesGridLCI.TextSize = new System.Drawing.Size(0, 0);
            this.storesGridLCI.TextVisible = false;
            this.storesGridLCI.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never;
            this.repositoryItemPictureEdit2.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.UltraFlat;
            this.repositoryItemPictureEdit2.Name = "repositoryItemPictureEdit2";
            this.repositoryItemPictureEdit2.SizeMode = DevExpress.XtraEditors.Controls.PictureSizeMode.Zoom;
            this.layoutViewCard2.CustomizationFormText = "TemplateCard";
            this.layoutViewCard2.HeaderButtonsLocation = DevExpress.Utils.GroupElementLocation.AfterText;
            this.layoutViewCard2.GroupBordersVisible = false;
            this.layoutViewCard2.Name = "layoutViewTemplateCard";
            this.layoutViewCard2.OptionsItemText.TextToControlDistance = 5;
            this.layoutViewCard2.Text = "TemplateCard";
            this.repositoryItemTextEdit1.Appearance.Options.UseTextOptions = true;
            this.repositoryItemTextEdit1.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;
            this.repositoryItemTextEdit1.AutoHeight = false;
            this.repositoryItemTextEdit1.Name = "repositoryItemTextEdit1";
            this.repositoryItemTextEdit2.AutoHeight = false;
            this.repositoryItemTextEdit2.Name = "repositoryItemTextEdit2";
            this.repositoryItemPictureEdit1.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.HotFlat;
            this.repositoryItemPictureEdit1.Name = "repositoryItemPictureEdit1";
            this.repositoryItemPictureEdit1.SizeMode = DevExpress.XtraEditors.Controls.PictureSizeMode.Zoom;
            this.layoutViewCard1.CustomizationFormText = "TemplateCard";
            this.layoutViewCard1.HeaderButtonsLocation = DevExpress.Utils.GroupElementLocation.AfterText;
            this.layoutViewCard1.GroupBordersVisible = false;
            this.layoutViewCard1.Name = "layoutViewTemplateCard";
            this.layoutViewCard1.OptionsItemText.TextToControlDistance = 5;
            this.layoutViewCard1.Text = "TemplateCard";
            this.Appearance.BackColor = System.Drawing.Color.White;
            this.Appearance.Options.UseBackColor = true;
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 20F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.layoutControl1);
            this.Controls.Add(this.barDockControlLeft);
            this.Controls.Add(this.barDockControlRight);
            this.Controls.Add(this.barDockControlBottom);
            this.Controls.Add(this.barDockControlTop);
            this.Name = "CustomersModule";
            this.Size = new System.Drawing.Size(1105, 582);
            ((System.ComponentModel.ISupportInitialize)(this.layoutControl1)).EndInit();
            this.layoutControl1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.gridControlStores)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.customerStoreBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.tileViewStores)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.barManager1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridView2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridControlEmployee)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.customerEmployeeBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.tileViewEmployee)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridView1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.popupMenu1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridCustomers)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.customerBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.viewCustomers)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.repositoryItemTextEdit3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.repositoryItemSparklineEdit1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.simpleLabelItem1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.employeeGridLCI)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.storesGridLCI)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.repositoryItemPictureEdit2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutViewCard2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.repositoryItemTextEdit1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.repositoryItemTextEdit2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.repositoryItemPictureEdit1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutViewCard1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private XtraLayout.LayoutControl layoutControl1;
        private XtraLayout.LayoutControlGroup layoutControlGroup1;
        private XtraEditors.LabelControl labelControl1;
        private XtraGrid.GridControl gridCustomers;
        private XtraGrid.Views.Grid.GridView viewCustomers;
        private XtraLayout.LayoutControlItem layoutControlItem2;
        private XtraLayout.LayoutControlItem layoutControlItem3;
        private XtraLayout.EmptySpaceItem emptySpaceItem1;
        private XtraLayout.SimpleLabelItem simpleLabelItem1;
        private System.Windows.Forms.BindingSource customerBindingSource;
        private XtraGrid.Columns.GridColumn colName;
        private XtraGrid.Columns.GridColumn colPhone;
        private XtraGrid.Columns.GridColumn colFax;
        private System.Windows.Forms.BindingSource customerEmployeeBindingSource;
        private XtraEditors.Repository.RepositoryItemPictureEdit repositoryItemPictureEdit1;
        private XtraEditors.Repository.RepositoryItemTextEdit repositoryItemTextEdit1;
        private XtraGrid.Columns.GridColumn gridColumnAddress;
        private XtraGrid.Columns.GridColumn gridColumnCity;
        private XtraGrid.Columns.GridColumn gridColumnState;
        private XtraGrid.Columns.GridColumn gridColumnZipCode;
        private System.Windows.Forms.BindingSource customerStoreBindingSource;
        private XtraEditors.Repository.RepositoryItemPictureEdit repositoryItemPictureEdit2;
        private XtraGrid.Views.Layout.LayoutViewCard layoutViewCard2;
        private XtraGrid.Columns.GridColumn colMonthlySales;
        private XtraEditors.Repository.RepositoryItemSparklineEdit repositoryItemSparklineEdit1;
        private XtraGrid.Views.Layout.LayoutViewCard layoutViewCard1;
        private XtraEditors.Repository.RepositoryItemTextEdit repositoryItemTextEdit2;
        private XtraEditors.DropDownButton dropDownButton1;
        private XtraLayout.LayoutControlItem layoutControlItem1;
        private XtraBars.PopupMenu popupMenu1;
        private XtraBars.BarButtonItem barButtonItemContacts;
        private XtraBars.BarButtonItem barButtonItemStores;
        private XtraBars.BarManager barManager1;
        private XtraBars.BarDockControl barDockControlTop;
        private XtraBars.BarDockControl barDockControlBottom;
        private XtraBars.BarDockControl barDockControlLeft;
        private XtraBars.BarDockControl barDockControlRight;
        private XtraEditors.Repository.RepositoryItemTextEdit repositoryItemTextEdit3;
        private XtraGrid.GridControl gridControlStores;
        private XtraGrid.Views.Grid.GridView gridView2;
        private XtraGrid.GridControl gridControlEmployee;
        private XtraGrid.Views.Grid.GridView gridView1;
        private XtraLayout.LayoutControlItem employeeGridLCI;
        private XtraLayout.LayoutControlItem storesGridLCI;
        private XtraGrid.Views.Tile.TileView tileViewStores;
        private XtraGrid.Views.Tile.TileView tileViewEmployee;
        private XtraGrid.Columns.TileViewColumn colFullName;
        private XtraGrid.Columns.TileViewColumn colPosition;
        private XtraGrid.Columns.TileViewColumn colAddress;
        private XtraGrid.Columns.TileViewColumn colPhoto;
        private XtraGrid.Columns.TileViewColumn colCrestImage;
        private XtraGrid.Columns.TileViewColumn colCityName;
        private XtraGrid.Columns.TileViewColumn colAddressLine;
        private XtraGrid.Columns.TileViewColumn colAddressCityLine;

    }
}
