namespace DevExpress.DevAV.Modules {
    public partial class Products {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing) {
            if(disposing && (components != null)) {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent() {
            this.components = new System.ComponentModel.Container();
            DevExpress.XtraEditors.TileItemElement tileItemElement1 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement2 = new DevExpress.XtraEditors.TileItemElement();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Products));
            DevExpress.XtraEditors.TileItemElement tileItemElement3 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement4 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement5 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement6 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement7 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement8 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement9 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement10 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement11 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement12 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.Sparkline.BarSparklineView barSparklineView1 = new DevExpress.Sparkline.BarSparklineView();
            this.layoutControl1 = new DevExpress.XtraLayout.LayoutControl();
            this.tileControl = new DevExpress.XtraEditors.TileControl();
            this.tileGroup = new DevExpress.XtraEditors.TileGroup();
            this.tileItemAll = new DevExpress.XtraEditors.TileItem();
            this.tileItemTelevisions = new DevExpress.XtraEditors.TileItem();
            this.tileItemMonitors = new DevExpress.XtraEditors.TileItem();
            this.tileItemVideoPlayers = new DevExpress.XtraEditors.TileItem();
            this.tileItemProjectors = new DevExpress.XtraEditors.TileItem();
            this.tileItemAutomation = new DevExpress.XtraEditors.TileItem();
            this.gridProducts = new DevExpress.XtraGrid.GridControl();
            this.productsSource = new System.Windows.Forms.BindingSource(this.components);
            this.viewProducts = new DevExpress.XtraGrid.Views.Grid.GridView();
            this.colName = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colCost = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colSalePrice = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colRetailPrice = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colInventory = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colBackOrder = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colMonthlySales = new DevExpress.XtraGrid.Columns.GridColumn();
            this.repositoryItemSparklineEdit1 = new DevExpress.XtraEditors.Repository.RepositoryItemSparklineEdit();
            this.layoutControlGroup1 = new DevExpress.XtraLayout.LayoutControlGroup();
            this.layoutControlItem2 = new DevExpress.XtraLayout.LayoutControlItem();
            this.tileControlLCI = new DevExpress.XtraLayout.LayoutControlItem();
            this.hideButton = new DevExpress.XtraLayout.SimpleLabelItem();
            this.productsSLI = new DevExpress.XtraLayout.SimpleLabelItem();
            this.collapseButton = new DevExpress.XtraLayout.SimpleLabelItem();
            this.simpleLabelItem2 = new DevExpress.XtraLayout.SimpleLabelItem();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControl1)).BeginInit();
            this.layoutControl1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.gridProducts)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.productsSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.viewProducts)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.repositoryItemSparklineEdit1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.tileControlLCI)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.hideButton)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.productsSLI)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.collapseButton)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.simpleLabelItem2)).BeginInit();
            this.SuspendLayout();
            this.layoutControl1.AllowCustomization = false;
            this.layoutControl1.BackColor = System.Drawing.Color.White;
            this.layoutControl1.Controls.Add(this.tileControl);
            this.layoutControl1.Controls.Add(this.gridProducts);
            this.layoutControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.layoutControl1.Location = new System.Drawing.Point(0, 0);
            this.layoutControl1.Name = "layoutControl1";
            this.layoutControl1.OptionsCustomizationForm.DesignTimeCustomizationFormPositionAndSize = new System.Drawing.Rectangle(593, 271, 930, 751);
            this.layoutControl1.Root = this.layoutControlGroup1;
            this.layoutControl1.Size = new System.Drawing.Size(1104, 582);
            this.layoutControl1.TabIndex = 0;
            this.layoutControl1.Text = "layoutControl1";
            this.tileControl.AllowDrag = false;
            this.tileControl.AllowGlyphSkinning = true;
            this.tileControl.AllowSelectedItem = true;
            this.tileControl.AppearanceItem.Hovered.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(78)))), ((int)(((byte)(114)))), ((int)(((byte)(191)))));
            this.tileControl.AppearanceItem.Hovered.Options.UseBackColor = true;
            this.tileControl.AppearanceItem.Normal.BackColor = System.Drawing.Color.White;
            this.tileControl.AppearanceItem.Normal.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(195)))), ((int)(((byte)(195)))), ((int)(((byte)(195)))));
            this.tileControl.AppearanceItem.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(89)))), ((int)(((byte)(89)))), ((int)(((byte)(89)))));
            this.tileControl.AppearanceItem.Normal.Options.UseBackColor = true;
            this.tileControl.AppearanceItem.Normal.Options.UseBorderColor = true;
            this.tileControl.AppearanceItem.Normal.Options.UseForeColor = true;
            this.tileControl.AppearanceItem.Pressed.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(69)))), ((int)(((byte)(148)))));
            this.tileControl.AppearanceItem.Pressed.Options.UseBackColor = true;
            this.tileControl.AppearanceItem.Selected.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(81)))), ((int)(((byte)(165)))));
            this.tileControl.AppearanceItem.Selected.BorderColor = System.Drawing.Color.Transparent;
            this.tileControl.AppearanceItem.Selected.ForeColor = System.Drawing.Color.White;
            this.tileControl.AppearanceItem.Selected.Options.UseBackColor = true;
            this.tileControl.AppearanceItem.Selected.Options.UseBorderColor = true;
            this.tileControl.AppearanceItem.Selected.Options.UseForeColor = true;
            this.tileControl.DragSize = new System.Drawing.Size(0, 0);
            this.tileControl.Groups.Add(this.tileGroup);
            this.tileControl.IndentBetweenItems = 5;
            this.tileControl.ItemPadding = new System.Windows.Forms.Padding(7, 7, 7, 4);
            this.tileControl.ItemSize = 80;
            this.tileControl.Location = new System.Drawing.Point(42, 47);
            this.tileControl.Margin = new System.Windows.Forms.Padding(0);
            this.tileControl.MaxId = 8;
            this.tileControl.Name = "tileControl";
            this.tileControl.Orientation = System.Windows.Forms.Orientation.Vertical;
            this.tileControl.Padding = new System.Windows.Forms.Padding(0, 6, 0, 0);
            this.tileControl.SelectedItem = this.tileItemAll;
            this.tileControl.Size = new System.Drawing.Size(236, 533);
            this.tileControl.TabIndex = 26;
            this.tileControl.Text = "tileControl";
            this.tileControl.ItemClick += new DevExpress.XtraEditors.TileItemClickEventHandler(this.tileControl_ItemClick);
            this.tileGroup.Items.Add(this.tileItemAll);
            this.tileGroup.Items.Add(this.tileItemTelevisions);
            this.tileGroup.Items.Add(this.tileItemMonitors);
            this.tileGroup.Items.Add(this.tileItemVideoPlayers);
            this.tileGroup.Items.Add(this.tileItemProjectors);
            this.tileGroup.Items.Add(this.tileItemAutomation);
            this.tileGroup.Name = "tileGroup";
            this.tileGroup.Text = null;
            tileItemElement1.Appearance.Normal.FontSizeDelta = 128;
            tileItemElement1.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(171)))), ((int)(((byte)(171)))), ((int)(((byte)(171)))));
            tileItemElement1.Appearance.Normal.Options.UseFont = true;
            tileItemElement1.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement1.Appearance.Selected.FontSizeDelta = 128;
            tileItemElement1.Appearance.Selected.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(168)))), ((int)(((byte)(209)))));
            tileItemElement1.Appearance.Selected.Options.UseFont = true;
            tileItemElement1.Appearance.Selected.Options.UseForeColor = true;
            tileItemElement1.ImageBorderColor = System.Drawing.Color.Empty;
            tileItemElement1.Text = "5";
            tileItemElement1.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopRight;
            tileItemElement1.TextLocation = new System.Drawing.Point(-2, -12);
            tileItemElement2.Image = ((System.Drawing.Image)(resources.GetObject("tileItemElement2.Image")));
            tileItemElement2.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopLeft;
            tileItemElement2.ImageBorderColor = System.Drawing.Color.Empty;
            tileItemElement2.Text = "All";
            tileItemElement2.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomLeft;
            this.tileItemAll.Elements.Add(tileItemElement1);
            this.tileItemAll.Elements.Add(tileItemElement2);
            this.tileItemAll.Id = 7;
            this.tileItemAll.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItemAll.Name = "tileItemAll";
            this.tileItemAll.Tag = "!= null";
            tileItemElement3.Appearance.Normal.FontSizeDelta = 128;
            tileItemElement3.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(171)))), ((int)(((byte)(171)))), ((int)(((byte)(171)))));
            tileItemElement3.Appearance.Normal.Options.UseFont = true;
            tileItemElement3.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement3.Appearance.Selected.FontSizeDelta = 128;
            tileItemElement3.Appearance.Selected.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(168)))), ((int)(((byte)(209)))));
            tileItemElement3.Appearance.Selected.Options.UseFont = true;
            tileItemElement3.Appearance.Selected.Options.UseForeColor = true;
            tileItemElement3.ImageBorderColor = System.Drawing.Color.Empty;
            tileItemElement3.Text = "183";
            tileItemElement3.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopRight;
            tileItemElement3.TextLocation = new System.Drawing.Point(-2, -12);
            tileItemElement4.Image = ((System.Drawing.Image)(resources.GetObject("tileItemElement4.Image")));
            tileItemElement4.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopLeft;
            tileItemElement4.ImageBorderColor = System.Drawing.Color.Empty;
            tileItemElement4.Text = "TVs";
            tileItemElement4.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomLeft;
            this.tileItemTelevisions.Elements.Add(tileItemElement3);
            this.tileItemTelevisions.Elements.Add(tileItemElement4);
            this.tileItemTelevisions.Id = 0;
            this.tileItemTelevisions.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItemTelevisions.Name = "tileItemTelevisions";
            this.tileItemTelevisions.Tag = "Televisions";
            tileItemElement5.Appearance.Normal.FontSizeDelta = 128;
            tileItemElement5.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(171)))), ((int)(((byte)(171)))), ((int)(((byte)(171)))));
            tileItemElement5.Appearance.Normal.Options.UseFont = true;
            tileItemElement5.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement5.Appearance.Selected.FontSizeDelta = 128;
            tileItemElement5.Appearance.Selected.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(168)))), ((int)(((byte)(209)))));
            tileItemElement5.Appearance.Selected.Options.UseFont = true;
            tileItemElement5.Appearance.Selected.Options.UseForeColor = true;
            tileItemElement5.ImageBorderColor = System.Drawing.Color.Empty;
            tileItemElement5.Text = "5";
            tileItemElement5.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopRight;
            tileItemElement5.TextLocation = new System.Drawing.Point(-2, -12);
            tileItemElement6.Image = ((System.Drawing.Image)(resources.GetObject("tileItemElement6.Image")));
            tileItemElement6.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopLeft;
            tileItemElement6.ImageBorderColor = System.Drawing.Color.Empty;
            tileItemElement6.Text = "Monitors";
            tileItemElement6.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomLeft;
            this.tileItemMonitors.Elements.Add(tileItemElement5);
            this.tileItemMonitors.Elements.Add(tileItemElement6);
            this.tileItemMonitors.Id = 1;
            this.tileItemMonitors.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItemMonitors.Name = "tileItemMonitors";
            this.tileItemMonitors.Tag = "Monitors";
            tileItemElement7.Appearance.Normal.FontSizeDelta = 128;
            tileItemElement7.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(171)))), ((int)(((byte)(171)))), ((int)(((byte)(171)))));
            tileItemElement7.Appearance.Normal.Options.UseFont = true;
            tileItemElement7.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement7.Appearance.Selected.FontSizeDelta = 128;
            tileItemElement7.Appearance.Selected.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(168)))), ((int)(((byte)(209)))));
            tileItemElement7.Appearance.Selected.Options.UseFont = true;
            tileItemElement7.Appearance.Selected.Options.UseForeColor = true;
            tileItemElement7.ImageBorderColor = System.Drawing.Color.Empty;
            tileItemElement7.Text = "5";
            tileItemElement7.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopRight;
            tileItemElement7.TextLocation = new System.Drawing.Point(-2, -12);
            tileItemElement8.Image = ((System.Drawing.Image)(resources.GetObject("tileItemElement8.Image")));
            tileItemElement8.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopLeft;
            tileItemElement8.ImageBorderColor = System.Drawing.Color.Empty;
            tileItemElement8.Text = "Video Players";
            tileItemElement8.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomLeft;
            this.tileItemVideoPlayers.Elements.Add(tileItemElement7);
            this.tileItemVideoPlayers.Elements.Add(tileItemElement8);
            this.tileItemVideoPlayers.Id = 2;
            this.tileItemVideoPlayers.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItemVideoPlayers.Name = "tileItemVideoPlayers";
            this.tileItemVideoPlayers.Tag = "VideoPlayers";
            tileItemElement9.Appearance.Normal.FontSizeDelta = 128;
            tileItemElement9.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(171)))), ((int)(((byte)(171)))), ((int)(((byte)(171)))));
            tileItemElement9.Appearance.Normal.Options.UseFont = true;
            tileItemElement9.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement9.Appearance.Selected.FontSizeDelta = 128;
            tileItemElement9.Appearance.Selected.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(168)))), ((int)(((byte)(209)))));
            tileItemElement9.Appearance.Selected.Options.UseFont = true;
            tileItemElement9.Appearance.Selected.Options.UseForeColor = true;
            tileItemElement9.ImageBorderColor = System.Drawing.Color.Empty;
            tileItemElement9.Text = "5";
            tileItemElement9.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopRight;
            tileItemElement9.TextLocation = new System.Drawing.Point(-2, -12);
            tileItemElement10.Image = ((System.Drawing.Image)(resources.GetObject("tileItemElement10.Image")));
            tileItemElement10.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopLeft;
            tileItemElement10.ImageBorderColor = System.Drawing.Color.Empty;
            tileItemElement10.Text = "Projectors";
            tileItemElement10.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomLeft;
            this.tileItemProjectors.Elements.Add(tileItemElement9);
            this.tileItemProjectors.Elements.Add(tileItemElement10);
            this.tileItemProjectors.Id = 3;
            this.tileItemProjectors.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItemProjectors.Name = "tileItemProjectors";
            this.tileItemProjectors.Tag = "Projectors";
            tileItemElement11.Appearance.Normal.FontSizeDelta = 128;
            tileItemElement11.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(171)))), ((int)(((byte)(171)))), ((int)(((byte)(171)))));
            tileItemElement11.Appearance.Normal.Options.UseFont = true;
            tileItemElement11.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement11.Appearance.Selected.FontSizeDelta = 128;
            tileItemElement11.Appearance.Selected.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(168)))), ((int)(((byte)(209)))));
            tileItemElement11.Appearance.Selected.Options.UseFont = true;
            tileItemElement11.Appearance.Selected.Options.UseForeColor = true;
            tileItemElement11.ImageBorderColor = System.Drawing.Color.Empty;
            tileItemElement11.Text = "5";
            tileItemElement11.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopRight;
            tileItemElement11.TextLocation = new System.Drawing.Point(-2, -12);
            tileItemElement12.Image = ((System.Drawing.Image)(resources.GetObject("tileItemElement12.Image")));
            tileItemElement12.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopLeft;
            tileItemElement12.ImageBorderColor = System.Drawing.Color.Empty;
            tileItemElement12.Text = "Automation";
            tileItemElement12.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomLeft;
            this.tileItemAutomation.Elements.Add(tileItemElement11);
            this.tileItemAutomation.Elements.Add(tileItemElement12);
            this.tileItemAutomation.Id = 4;
            this.tileItemAutomation.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItemAutomation.Name = "tileItemAutomation";
            this.tileItemAutomation.Tag = "Automation";
            this.gridProducts.DataSource = this.productsSource;
            this.gridProducts.Location = new System.Drawing.Point(310, 53);
            this.gridProducts.MainView = this.viewProducts;
            this.gridProducts.Name = "gridProducts";
            this.gridProducts.RepositoryItems.AddRange(new DevExpress.XtraEditors.Repository.RepositoryItem[] {
            this.repositoryItemSparklineEdit1});
            this.gridProducts.ShowOnlyPredefinedDetails = true;
            this.gridProducts.Size = new System.Drawing.Size(752, 527);
            this.gridProducts.TabIndex = 1;
            this.gridProducts.ViewCollection.AddRange(new DevExpress.XtraGrid.Views.Base.BaseView[] {
            this.viewProducts});
            this.productsSource.DataSource = typeof(DevExpress.DevAV.Product);
            this.viewProducts.Appearance.FooterPanel.Options.UseTextOptions = true;
            this.viewProducts.Appearance.FooterPanel.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            this.viewProducts.Columns.AddRange(new DevExpress.XtraGrid.Columns.GridColumn[] {
            this.colName,
            this.colCost,
            this.colSalePrice,
            this.colRetailPrice,
            this.colInventory,
            this.colBackOrder,
            this.colMonthlySales});
            this.viewProducts.FocusRectStyle = DevExpress.XtraGrid.Views.Grid.DrawFocusRectStyle.None;
            this.viewProducts.FooterPanelHeight = 60;
            this.viewProducts.GridControl = this.gridProducts;
            this.viewProducts.GroupSummary.AddRange(new DevExpress.XtraGrid.GridSummaryItem[] {
            new DevExpress.XtraGrid.GridGroupSummaryItem(DevExpress.Data.SummaryItemType.Sum, "TotalEmployees", this.colName, "Product COUNT {1}"),
            new DevExpress.XtraGrid.GridGroupSummaryItem(DevExpress.Data.SummaryItemType.Sum, "Orders", null, "TOTAL SALES")});
            this.viewProducts.Name = "viewProducts";
            this.viewProducts.OptionsBehavior.Editable = false;
            this.viewProducts.OptionsCustomization.AllowColumnMoving = false;
            this.viewProducts.OptionsCustomization.AllowGroup = false;
            this.viewProducts.OptionsCustomization.AllowQuickHideColumns = false;
            this.viewProducts.OptionsMenu.EnableColumnMenu = false;
            this.viewProducts.OptionsSelection.EnableAppearanceFocusedCell = false;
            this.viewProducts.OptionsView.ShowFilterPanelMode = DevExpress.XtraGrid.Views.Base.ShowFilterPanelMode.Never;
            this.viewProducts.OptionsView.ShowFooter = true;
            this.viewProducts.OptionsView.ShowGroupPanel = false;
            this.viewProducts.OptionsView.ShowIndicator = false;
            this.viewProducts.RowClick += new DevExpress.XtraGrid.Views.Grid.RowClickEventHandler(this.viewProducts_RowClick);
            this.viewProducts.FocusedRowObjectChanged += new DevExpress.XtraGrid.Views.Base.FocusedRowObjectChangedEventHandler(this.viewProducts_FocusedRowObjectChanged);
            this.viewProducts.CustomUnboundColumnData += new DevExpress.XtraGrid.Views.Base.CustomColumnDataEventHandler(this.gridView1_CustomUnboundColumnData);
            this.colName.FieldName = "Name";
            this.colName.Name = "colName";
            this.colName.Visible = true;
            this.colName.VisibleIndex = 0;
            this.colName.Width = 209;
            this.colCost.Caption = "Cost";
            this.colCost.DisplayFormat.FormatString = "c";
            this.colCost.DisplayFormat.FormatType = DevExpress.Utils.FormatType.Numeric;
            this.colCost.FieldName = "Cost";
            this.colCost.Name = "colCost";
            this.colCost.Visible = true;
            this.colCost.VisibleIndex = 1;
            this.colCost.Width = 103;
            this.colSalePrice.Caption = "Sale Price";
            this.colSalePrice.DisplayFormat.FormatString = "c";
            this.colSalePrice.DisplayFormat.FormatType = DevExpress.Utils.FormatType.Numeric;
            this.colSalePrice.FieldName = "SalePrice";
            this.colSalePrice.Name = "colSalePrice";
            this.colSalePrice.Visible = true;
            this.colSalePrice.VisibleIndex = 2;
            this.colSalePrice.Width = 103;
            this.colRetailPrice.Caption = "Retail Price";
            this.colRetailPrice.DisplayFormat.FormatString = "c";
            this.colRetailPrice.DisplayFormat.FormatType = DevExpress.Utils.FormatType.Numeric;
            this.colRetailPrice.FieldName = "RetailPrice";
            this.colRetailPrice.Name = "colRetailPrice";
            this.colRetailPrice.Visible = true;
            this.colRetailPrice.VisibleIndex = 3;
            this.colRetailPrice.Width = 103;
            this.colInventory.Caption = "Inventory";
            this.colInventory.FieldName = "CurrentInventory";
            this.colInventory.Name = "colInventory";
            this.colInventory.Summary.AddRange(new DevExpress.XtraGrid.GridSummaryItem[] {
            new DevExpress.XtraGrid.GridColumnSummaryItem(DevExpress.Data.SummaryItemType.Sum, "CurrentInventory", "<color=gray>TOTAL INVENTORY</color><br><b>{0}</b>")});
            this.colInventory.Visible = true;
            this.colInventory.VisibleIndex = 4;
            this.colInventory.Width = 103;
            this.colBackOrder.Caption = "Backorder";
            this.colBackOrder.FieldName = "Backorder";
            this.colBackOrder.Name = "colBackOrder";
            this.colBackOrder.Visible = true;
            this.colBackOrder.VisibleIndex = 5;
            this.colBackOrder.Width = 103;
            this.colMonthlySales.Caption = "Monthly Sales (FY2013)";
            this.colMonthlySales.ColumnEdit = this.repositoryItemSparklineEdit1;
            this.colMonthlySales.FieldName = "MonthlySales";
            this.colMonthlySales.MaxWidth = 300;
            this.colMonthlySales.MinWidth = 30;
            this.colMonthlySales.Name = "colMonthlySales";
            this.colMonthlySales.OptionsFilter.AllowAutoFilter = false;
            this.colMonthlySales.OptionsFilter.AllowFilter = false;
            this.colMonthlySales.Summary.AddRange(new DevExpress.XtraGrid.GridSummaryItem[] {
            new DevExpress.XtraGrid.GridColumnSummaryItem(DevExpress.Data.SummaryItemType.Sum, "RetailPrice", "<color=gray>TOTAL SALES</color><br><b>{0:c}</b>")});
            this.colMonthlySales.UnboundType = DevExpress.Data.UnboundColumnType.Object;
            this.colMonthlySales.Visible = true;
            this.colMonthlySales.VisibleIndex = 6;
            this.colMonthlySales.Width = 255;
            this.repositoryItemSparklineEdit1.Name = "repositoryItemSparklineEdit1";
            barSparklineView1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(81)))), ((int)(((byte)(165)))));
            this.repositoryItemSparklineEdit1.View = barSparklineView1;
            this.layoutControlGroup1.CustomizationFormText = "Root";
            this.layoutControlGroup1.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True;
            this.layoutControlGroup1.GroupBordersVisible = false;
            this.layoutControlGroup1.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.layoutControlItem2,
            this.tileControlLCI,
            this.hideButton,
            this.productsSLI});
            this.layoutControlGroup1.Location = new System.Drawing.Point(0, 0);
            this.layoutControlGroup1.Name = "Root";
            this.layoutControlGroup1.Padding = new DevExpress.XtraLayout.Utils.Padding(40, 40, 0, 0);
            this.layoutControlGroup1.Size = new System.Drawing.Size(1104, 582);
            this.layoutControlGroup1.TextVisible = false;
            this.layoutControlItem2.Control = this.gridProducts;
            this.layoutControlItem2.CustomizationFormText = "layoutControlItem2";
            this.layoutControlItem2.Location = new System.Drawing.Point(268, 45);
            this.layoutControlItem2.Name = "layoutControlItem2";
            this.layoutControlItem2.Padding = new DevExpress.XtraLayout.Utils.Padding(2, 2, 8, 2);
            this.layoutControlItem2.Size = new System.Drawing.Size(756, 537);
            this.layoutControlItem2.TextSize = new System.Drawing.Size(0, 0);
            this.layoutControlItem2.TextVisible = false;
            this.tileControlLCI.Control = this.tileControl;
            this.tileControlLCI.CustomizationFormText = "tileControlLCI";
            this.tileControlLCI.Location = new System.Drawing.Point(0, 45);
            this.tileControlLCI.MaxSize = new System.Drawing.Size(240, 0);
            this.tileControlLCI.MinSize = new System.Drawing.Size(240, 24);
            this.tileControlLCI.Name = "tileControlLCI";
            this.tileControlLCI.OptionsPrint.AllowPrint = false;
            this.tileControlLCI.Size = new System.Drawing.Size(240, 537);
            this.tileControlLCI.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.tileControlLCI.TextSize = new System.Drawing.Size(0, 0);
            this.tileControlLCI.TextVisible = false;
            this.hideButton.AllowHotTrack = false;
            this.hideButton.CustomizationFormText = " ";
            this.hideButton.Image = ((System.Drawing.Image)(resources.GetObject("hideButton.Image")));
            this.hideButton.Location = new System.Drawing.Point(240, 45);
            this.hideButton.MaxSize = new System.Drawing.Size(28, 0);
            this.hideButton.MinSize = new System.Drawing.Size(28, 1);
            this.hideButton.Name = "hideButton";
            this.hideButton.Size = new System.Drawing.Size(28, 537);
            this.hideButton.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.hideButton.Text = " ";
            this.hideButton.TextSize = new System.Drawing.Size(179, 25);
            this.hideButton.Click += new System.EventHandler(this.hideButton_Click);
            this.productsSLI.AllowHotTrack = false;
            this.productsSLI.AllowHtmlStringInCaption = true;
            this.productsSLI.AppearanceItemCaption.FontSizeDelta = 3;
            this.productsSLI.AppearanceItemCaption.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(140)))), ((int)(((byte)(140)))), ((int)(((byte)(140)))));
            this.productsSLI.AppearanceItemCaption.Options.UseFont = true;
            this.productsSLI.AppearanceItemCaption.Options.UseForeColor = true;
            this.productsSLI.CustomizationFormText = "PRODUCTS";
            this.productsSLI.Location = new System.Drawing.Point(0, 0);
            this.productsSLI.Name = "productsSLI";
            this.productsSLI.Padding = new DevExpress.XtraLayout.Utils.Padding(2, 2, 10, 10);
            this.productsSLI.Size = new System.Drawing.Size(1024, 45);
            this.productsSLI.Text = "PRODUCT <color=47, 81, 165>Categories";
            this.productsSLI.TextSize = new System.Drawing.Size(179, 25);
            this.collapseButton.AllowHotTrack = false;
            this.collapseButton.CustomizationFormText = " ";
            this.collapseButton.Location = new System.Drawing.Point(168, 34);
            this.collapseButton.MaxSize = new System.Drawing.Size(28, 0);
            this.collapseButton.MinSize = new System.Drawing.Size(28, 1);
            this.collapseButton.Name = "collapseButton";
            this.collapseButton.Size = new System.Drawing.Size(28, 551);
            this.collapseButton.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.collapseButton.Text = " ";
            this.collapseButton.TextSize = new System.Drawing.Size(73, 28);
            this.simpleLabelItem2.AllowHotTrack = false;
            this.simpleLabelItem2.AppearanceItemCaption.FontSizeDelta = 5;
            this.simpleLabelItem2.AppearanceItemCaption.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(81)))), ((int)(((byte)(165)))));
            this.simpleLabelItem2.AppearanceItemCaption.Options.UseFont = true;
            this.simpleLabelItem2.AppearanceItemCaption.Options.UseForeColor = true;
            this.simpleLabelItem2.CustomizationFormText = "PRODUCT";
            this.simpleLabelItem2.Location = new System.Drawing.Point(0, 0);
            this.simpleLabelItem2.Name = "simpleLabelItem1";
            this.simpleLabelItem2.Padding = new DevExpress.XtraLayout.Utils.Padding(2, 2, 10, 10);
            this.simpleLabelItem2.Size = new System.Drawing.Size(1044, 50);
            this.simpleLabelItem2.Text = "Categories";
            this.simpleLabelItem2.TextSize = new System.Drawing.Size(116, 30);
            this.Appearance.BackColor = System.Drawing.Color.White;
            this.Appearance.Options.UseBackColor = true;
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 20F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.layoutControl1);
            this.Name = "Products";
            this.Size = new System.Drawing.Size(1104, 582);
            ((System.ComponentModel.ISupportInitialize)(this.layoutControl1)).EndInit();
            this.layoutControl1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.gridProducts)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.productsSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.viewProducts)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.repositoryItemSparklineEdit1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.tileControlLCI)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.hideButton)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.productsSLI)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.collapseButton)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.simpleLabelItem2)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private XtraLayout.LayoutControl layoutControl1;
        private XtraLayout.LayoutControlGroup layoutControlGroup1;
        private XtraGrid.GridControl gridProducts;
        private XtraGrid.Views.Grid.GridView viewProducts;
        private XtraLayout.LayoutControlItem layoutControlItem2;
        private System.Windows.Forms.BindingSource productsSource;
        private XtraGrid.Columns.GridColumn colName;
        private XtraGrid.Columns.GridColumn colCost;
        private XtraGrid.Columns.GridColumn colSalePrice;
        private XtraGrid.Columns.GridColumn colRetailPrice;
        private XtraGrid.Columns.GridColumn colInventory;
        private XtraGrid.Columns.GridColumn colBackOrder;
        private XtraEditors.TileControl tileControl;
        private XtraEditors.TileGroup tileGroup;
        private XtraEditors.TileItem tileItemTelevisions;
        private XtraEditors.TileItem tileItemMonitors;
        private XtraEditors.TileItem tileItemVideoPlayers;
        private XtraEditors.TileItem tileItemProjectors;
        private XtraEditors.TileItem tileItemAutomation;
        private XtraLayout.LayoutControlItem tileControlLCI;
        private XtraLayout.SimpleLabelItem collapseButton;
        private XtraLayout.SimpleLabelItem hideButton;
        private XtraLayout.SimpleLabelItem productsSLI;
        private XtraLayout.SimpleLabelItem simpleLabelItem2;
        private XtraEditors.TileItem tileItemAll;
        private XtraGrid.Columns.GridColumn colMonthlySales;
        private XtraEditors.Repository.RepositoryItemSparklineEdit repositoryItemSparklineEdit1;

    }
}
